import type {
  BusinessUserAnalyticsBreakdownItem,
  BusinessUserAnalyticsTrendPoint,
} from './common.types'

export interface BusinessUserAnalyticsAiAdoption {
  totalConversations: number
  totalMessages: number
  userMessages: number
  liaMessages: number
  adoptionScore: number
  questionRate: number
  offTopicRate: number
  redirectRate: number
  averageResponseTimeSeconds: number
  averageSentiment: number
  questionQualityScore: number
  contextBreakdown: BusinessUserAnalyticsBreakdownItem[]
  messagesTrend: BusinessUserAnalyticsTrendPoint[]
}

export interface BusinessUserAnalyticsNotes {
  totalNotes: number
  manualNotes: number
  autoGeneratedNotes: number
  lessonsWithNotes: number
  adoptionRate: number
  averageLength: number
  notesScore: number
  bySource: BusinessUserAnalyticsBreakdownItem[]
  notesTrend: BusinessUserAnalyticsTrendPoint[]
}

export interface BusinessUserAnalyticsActivities {
  totalSubmissions: number
  submitted: number
  validated: number
  needsRevision: number
  passRate: number
  averageQualityScore: number
  averageResponseLength: number
  withSofliaFeedback: number
  statusBreakdown: BusinessUserAnalyticsBreakdownItem[]
  submissionsTrend: BusinessUserAnalyticsTrendPoint[]
}

export interface BusinessUserAnalyticsQuizzes {
  /** Lecciones del scope que tienen quiz (denominador de contexto). */
  lessonsWithQuiz: number
  /** Quizzes presentados (lecciones con quiz_completed). */
  quizzesTaken: number
  /** Quizzes aprobados (lecciones con quiz_passed). */
  quizzesPassed: number
  /** quizzesPassed / quizzesTaken. */
  passRate: number
  /** Intentos totales registrados (filas en user_quiz_attempts). */
  totalAttempts: number
  /** Intentos extra más allá del primero (attempt_number > 1). */
  retries: number
  /** Aprobación al primer intento, sobre los intentos registrados. */
  firstTryPassRate: number
  /** Nº de quizzes con calificación detallada registrada (submissions). */
  scoredCount: number
  averageScore: number
  bestScore: number
  latestScore: number
  trend: BusinessUserAnalyticsTrendPoint[]
}

export interface BusinessUserAnalyticsQuality {
  overallScore: number
  courseScore: number
  activityScore: number
  sofliaQuestionScore: number
  notesScore: number
  quizScore: number
  evidenceCount: number
  radar: BusinessUserAnalyticsBreakdownItem[]
}

export interface BusinessUserAnalyticsAiSample {
  source: 'soflia_message' | 'activity_response' | 'quiz_response' | 'note'
  text: string
  courseTitle?: string
  signals: Record<string, string | number | boolean | null>
}
