export const fallbackTextEs = {
  learningTitle: 'Aprendizaje y finalización', adoptionTitle: 'Adopción de IA y notas', qualityTitle: 'Calidad de respuestas',
  metricProgress: 'Progreso y cierre', metricSoflia: 'Adopción SofLIA', metricQuality: 'Calidad operativa', actionPlanTitle: 'Plan de acción sugerido',
  noHierarchy: 'No hay jerarquía suficiente para comparar regiones, zonas o áreas.', noRiskCourse: 'No hay cursos con señales críticas en el periodo filtrado.', noSegment: 'No hay segmentos suficientes para comparar calidad.',
  recommendSoflia: 'Refuerza el uso de SofLIA en los segmentos con menor adopción y cruza el seguimiento con avance de curso.',
  recommendHierarchy: 'Usa el cuadro de honor por región, zona y área para replicar prácticas de los equipos con mejor score.',
  recommendQuality: 'Revisa actividades con baja calidad y alto uso de ayuda para ajustar instrucciones, ejemplos y criterios.',
  actionPlanSegment: 'Prioriza segmentos con baja calidad o bajo avance antes de ampliar nuevas asignaciones.',
  actionPlanCourse: 'Revisa cursos con mayor riesgo operativo y cruza avance, vencimientos y ayuda solicitada.',
  actionPlanData: 'Completa datos demográficos faltantes para mejorar precisión estadística de RRHH.',
  summary: (quality: number, progress: number) => 'Lectura automática: la calidad global es ' + quality + '% y el progreso promedio es ' + progress + '%.',
  metricProgressDetail: (completion: number, days: number) => 'Finalización ' + completion + '% y mediana de cierre ' + days + ' días.',
  metricSofliaDetail: (conversations: number, messages: number) => conversations + ' conversaciones y ' + messages + ' mensajes analizados.',
  metricQualityDetail: (quiz: number, activity: number, soflia: number) => 'Evaluaciones ' + quiz + '%, actividades ' + activity + '% y SofLIA ' + soflia + '%.',
  learningPoint: (completion: number, days: number) => 'La finalización global es ' + completion + '% y el tiempo promedio de cierre es ' + days + ' días.',
  riskCourse: (title: string, overdue: number) => title + ' concentra riesgo operativo con ' + overdue + ' vencimientos.',
  adoptionPoint: (soflia: number, notes: number) => 'La adopción de SofLIA es ' + soflia + '% y la adopción de notas es ' + notes + '%.',
  bestRegion: (name: string, score: number) => name + ' lidera el ranking regional con score ' + score + '%.',
  qualityPoint: (quality: number, offTopic: number) => 'El score de calidad es ' + quality + '% y la tasa fuera de tema es ' + offTopic + '%.',
  segmentPoint: (label: string, score: number) => label + ' requiere revisión: registra score de calidad ' + score + '%.',
  riskQuality: (help: number) => 'Usuarios que piden ayuda en actividades: ' + help + '%.',
  riskData: (completion: number) => 'Demografía completa: ' + completion + '%. Los faltantes reducen precisión estadística.',
}
