export const fallbackTextPt = {
  learningTitle: 'Aprendizagem e conclusão', adoptionTitle: 'Adoção de IA e notas', qualityTitle: 'Qualidade das respostas',
  metricProgress: 'Progresso e fechamento', metricSoflia: 'Adoção SofLIA', metricQuality: 'Qualidade operacional', actionPlanTitle: 'Plano de ação sugerido',
  noHierarchy: 'Não há hierarquia suficiente para comparar regiões, zonas ou áreas.', noRiskCourse: 'Nenhum curso mostra sinais críticos no período filtrado.', noSegment: 'Não há segmentos suficientes para comparar qualidade.',
  recommendSoflia: 'Reforce o uso do SofLIA nos segmentos com menor adoção e cruze com progresso de curso.',
  recommendHierarchy: 'Use o quadro de honra por região, zona e área para replicar práticas dos melhores times.',
  recommendQuality: 'Revise atividades com baixa qualidade e alto uso de ajuda para ajustar instruções, exemplos e critérios.',
  actionPlanSegment: 'Priorize segmentos com baixa qualidade ou baixo progresso antes de ampliar novas atribuições.',
  actionPlanCourse: 'Revise cursos de maior risco e compare progresso, vencimentos e pedidos de ajuda.',
  actionPlanData: 'Complete dados demográficos faltantes para melhorar a precisão estatística de RH.',
  summary: (quality: number, progress: number) => 'Leitura automática: a qualidade global é ' + quality + '% e o progresso médio é ' + progress + '%.',
  metricProgressDetail: (completion: number, days: number) => 'Conclusão ' + completion + '% e mediana de fechamento ' + days + ' dias.',
  metricSofliaDetail: (conversations: number, messages: number) => conversations + ' conversas e ' + messages + ' mensagens analisadas.',
  metricQualityDetail: (quiz: number, activity: number, soflia: number) => 'Avaliações ' + quiz + '%, atividades ' + activity + '% e SofLIA ' + soflia + '%.',
  learningPoint: (completion: number, days: number) => 'A conclusão global é ' + completion + '% e o tempo médio de fechamento é ' + days + ' dias.',
  riskCourse: (title: string, overdue: number) => title + ' concentra risco operacional com ' + overdue + ' vencimentos.',
  adoptionPoint: (soflia: number, notes: number) => 'A adoção do SofLIA é ' + soflia + '% e a adoção de notas é ' + notes + '%.',
  bestRegion: (name: string, score: number) => name + ' lidera o ranking regional com score ' + score + '%.',
  qualityPoint: (quality: number, offTopic: number) => 'O score de qualidade é ' + quality + '% e a taxa fora de tema é ' + offTopic + '%.',
  segmentPoint: (label: string, score: number) => label + ' requer revisão: registra score de qualidade ' + score + '%.',
  riskQuality: (help: number) => 'Usuários que pedem ajuda em atividades: ' + help + '%.',
  riskData: (completion: number) => 'Demografia completa: ' + completion + '%. Campos faltantes reduzem a precisão estatística.',
}
