'use client'

import {
  BookOpen,
  FileText,
  Gauge,
  MessageSquare,
  MonitorSmartphone,
  NotebookPen,
  PencilLine,
  Sparkles,
} from 'lucide-react'
import { useTranslation } from 'react-i18next'
import type { ForensicAggregates } from '@/features/admin/services/user-forensics/user-forensics.types'

interface AuditAggregatesProps {
  aggregates: ForensicAggregates
}

/**
 * Resumen "maquillado" por sección: una tarjeta por área con una frase en lenguaje
 * claro y conteos, para que un auditor no técnico entienda qué hizo el usuario.
 */
export function AuditAggregates({ aggregates }: AuditAggregatesProps) {
  const { t } = useTranslation('admin')

  const cards: Array<{ icon: React.ReactNode; title: string; lines: string[] }> = [
    {
      icon: <MonitorSmartphone className="h-4 w-4 text-blue-500" />,
      title: t('users.masterPanel.audit.agg.access.title'),
      lines: [
        t('users.masterPanel.audit.agg.access.summary', {
          logins: aggregates.access.totalLogins,
          ips: aggregates.access.distinctIps,
          devices: aggregates.access.distinctDevices,
        }),
      ],
    },
    {
      icon: <BookOpen className="h-4 w-4 text-indigo-500" />,
      title: t('users.masterPanel.audit.agg.courses.title'),
      lines: [
        t('users.masterPanel.audit.agg.courses.summary', {
          enrolled: aggregates.courses.enrolled,
          completed: aggregates.courses.completed,
          certificates: aggregates.courses.certificatesIssued,
        }),
      ],
    },
    {
      icon: <Gauge className="h-4 w-4 text-cyan-500" />,
      title: t('users.masterPanel.audit.agg.lessons.title'),
      lines: [
        t('users.masterPanel.audit.agg.lessons.summary', {
          started: aggregates.lessons.started,
          completed: aggregates.lessons.completed,
          minutes: aggregates.lessons.totalVideoMinutes,
        }),
        t('users.masterPanel.audit.agg.lessons.videos', {
          watched: aggregates.lessons.videosWatchedFull,
          spedUp: aggregates.lessons.videosSpedUp,
          barely: aggregates.lessons.videosBarelyWatched,
        }),
      ],
    },
    {
      icon: <Sparkles className="h-4 w-4 text-teal-500" />,
      title: t('users.masterPanel.audit.agg.dialogues.title'),
      lines: [
        t('users.masterPanel.audit.agg.dialogues.summary', {
          total: aggregates.dialogues.total,
          available: aggregates.dialogues.available,
          completed: aggregates.dialogues.completed,
          abandoned: aggregates.dialogues.abandoned,
          avg: aggregates.dialogues.averageScore ?? 0,
        }),
      ],
    },
    {
      icon: <FileText className="h-4 w-4 text-orange-500" />,
      title: t('users.masterPanel.audit.agg.quizzes.title'),
      lines: [
        t('users.masterPanel.audit.agg.quizzes.summary', {
          attempts: aggregates.quizzes.totalAttempts,
          quizzes: aggregates.quizzes.distinctQuizzes,
          passed: aggregates.quizzes.passed,
          max: aggregates.quizzes.maxAttemptsOnSingleQuiz,
        }),
      ],
    },
    {
      icon: <PencilLine className="h-4 w-4 text-fuchsia-500" />,
      title: t('users.masterPanel.audit.agg.activities.title'),
      lines: [
        t('users.masterPanel.audit.agg.activities.summary', {
          submitted: aggregates.activities.submitted,
          validated: aggregates.activities.validated,
        }),
      ],
    },
    {
      icon: <NotebookPen className="h-4 w-4 text-rose-500" />,
      title: t('users.masterPanel.audit.agg.notes.title'),
      lines: [
        t('users.masterPanel.audit.agg.notes.summary', {
          total: aggregates.notes.total,
          written: aggregates.notes.userWritten,
          auto: aggregates.notes.autoGenerated,
        }),
      ],
    },
    {
      icon: <MessageSquare className="h-4 w-4 text-sky-500" />,
      title: t('users.masterPanel.audit.agg.lia.title'),
      lines: [
        t('users.masterPanel.audit.agg.lia.summary', {
          conversations: aggregates.lia.conversations,
          messages: aggregates.lia.totalMessages,
          abandoned: aggregates.lia.abandonedConversations,
        }),
      ],
    },
  ]

  return (
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
      {cards.map((card) => (
        <div
          key={card.title}
          className="rounded-xl border border-gray-200 bg-white px-3.5 py-3 dark:border-white/10 dark:bg-white/[0.02]"
        >
          <div className="mb-1.5 flex items-center gap-2">
            {card.icon}
            <p className="text-xs font-semibold text-gray-900 dark:text-white">{card.title}</p>
          </div>
          {card.lines.map((line, index) => (
            <p key={index} className="text-xs leading-relaxed text-gray-600 dark:text-gray-300">
              {line}
            </p>
          ))}
        </div>
      ))}
    </div>
  )
}
