'use client'

import { useState } from 'react'
import { ChevronRight } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import {
  formatForensicTimestamp,
  type ForensicTimeZone,
} from '@/shared/utils/forensic-timestamp'
import { NoteContentView } from '@/features/notebook/components/NoteContentView'
import type { ForensicNote } from '@/features/admin/services/user-forensics/user-forensics.types'

interface AuditNotesProps {
  notes: ForensicNote[]
  zone: ForensicTimeZone
}

export function AuditNotes({ notes, zone }: AuditNotesProps) {
  const { t } = useTranslation('admin')
  const [expandedId, setExpandedId] = useState<string | null>(null)

  if (notes.length === 0) {
    return (
      <p className="rounded-lg border border-gray-200 bg-gray-50/70 px-3 py-4 text-center text-xs text-gray-400 dark:border-white/10 dark:bg-white/5">
        {t('users.masterPanel.audit.notes.empty')}
      </p>
    )
  }

  return (
    <div className="max-h-[440px] space-y-1.5 overflow-y-auto pr-1">
      {notes.map((note) => {
        const isExpanded = expandedId === note.id
        const isAuto = note.isAutoGenerated && !note.isUserEdited
        return (
          <div
            key={note.id}
            className="rounded-lg border border-gray-200 bg-white dark:border-white/10 dark:bg-white/[0.02]"
          >
            <button
              type="button"
              onClick={() => setExpandedId(isExpanded ? null : note.id)}
              className="flex w-full items-center gap-2 px-3 py-2 text-left"
            >
              <ChevronRight
                className={`h-4 w-4 flex-shrink-0 text-gray-400 transition-transform ${
                  isExpanded ? 'rotate-90' : ''
                }`}
              />
              <span className="min-w-0 flex-1 truncate text-sm font-medium text-gray-900 dark:text-white">
                {note.title || t('users.masterPanel.audit.notes.untitled')}
              </span>
              <span
                className={`flex-shrink-0 rounded-full px-2 py-0.5 text-[10px] font-semibold ${
                  isAuto
                    ? 'bg-gray-200 text-gray-500 dark:bg-white/10 dark:text-gray-400'
                    : 'bg-rose-500/10 text-rose-500'
                }`}
              >
                {isAuto
                  ? t('users.masterPanel.audit.notes.auto')
                  : t('users.masterPanel.audit.notes.written')}
              </span>
              <span className="hidden flex-shrink-0 whitespace-nowrap font-mono text-[11px] text-gray-400 sm:inline">
                {formatForensicTimestamp(note.createdAtUtc, zone)}
              </span>
            </button>
            {isExpanded ? (
              <div className="border-t border-gray-100 px-3 py-2 dark:border-white/5">
                <NoteContentView
                  html={note.content}
                  source={isAuto ? 'lesson_auto_note' : undefined}
                  className="max-h-[360px] overflow-y-auto text-xs"
                />
              </div>
            ) : null}
          </div>
        )
      })}
    </div>
  )
}
