import { describe, expect, it } from 'vitest'

import { buildForensicTimelineCsv } from '../user-forensics.export'
import type { UserForensicSummary } from '../user-forensics.types'

function summary(): UserForensicSummary {
  return {
    identity: {
      id: 'u1',
      email: 'a@b.com',
      role: 'Business',
      emailVerified: true,
      organizationNames: ['Art in Technology'],
      createdAtUtc: '2026-07-17T18:36:00.000Z',
      lastLoginAtUtc: '2026-07-18T14:38:00.000Z',
      lastActivityAtUtc: '2026-07-18T14:38:00.000Z',
      isBanned: false,
      bannedAtUtc: null,
      banReason: null,
    },
    sessions: [],
    derivedLastActivityAtUtc: '2026-07-18T16:33:00.000Z',
    firstActivityAtUtc: '2026-07-18T14:38:00.000Z',
    aggregates: {
      access: { totalLogins: 0, distinctIps: 0, ipAddresses: [], distinctDevices: 0, concurrentSessions: 0, firstLoginAtUtc: null, lastLoginAtUtc: null },
      courses: { enrolled: 0, completed: 0, certificatesIssued: 0, lastCertificateAtUtc: null },
      lessons: { started: 0, completed: 0, videosWithProgress: 0, videosWatchedFull: 0, videosSpedUp: 0, videosBarelyWatched: 0, totalVideoMinutes: 0, maxPlaybackRate: null },
      dialogues: { total: 0, completed: 0, abandoned: 0, passed: 0, averageScore: null, available: 0 },
      quizzes: { totalAttempts: 0, distinctQuizzes: 0, passed: 0, maxAttemptsOnSingleQuiz: 0 },
      activities: { submitted: 0, validated: 0 },
      notes: { total: 0, userWritten: 0, autoGenerated: 0 },
      lia: { conversations: 0, abandonedConversations: 0, totalMessages: 0 },
    },
    flags: [],
    notes: [],
    timeline: [
      {
        id: 'quiz-1',
        type: 'quiz_attempt',
        atUtc: '2026-07-18T15:10:00.000Z',
        title: 'Intento de quiz #1',
        detail: 'Lección "A, B", 40%',
        score: 40,
        refIds: { lessonId: 'l1' },
      },
    ],
    eventTypeCounts: [{ type: 'quiz_attempt', count: 1 }],
    totalEvents: 1,
    truncated: false,
  }
}

describe('buildForensicTimelineCsv', () => {
  it('emits a header row and escapes fields containing commas/quotes', () => {
    const csv = buildForensicTimelineCsv(summary())
    const lines = csv.replace(new RegExp(`^${String.fromCharCode(0xfeff)}`), '').split('\r\n')
    expect(lines[0]).toBe('timestamp_utc,tipo,titulo,detalle,score,refs')
    // El detalle tiene comas y comillas → debe ir entrecomillado y con "" escapadas.
    expect(lines[1]).toContain('"Lección ""A, B"", 40%"')
    expect(lines[1]).toContain('2026-07-18T15:10:00.000Z')
    expect(lines[1]).toContain('lessonId=l1')
  })

  it('prepends a UTF-8 BOM for Excel', () => {
    expect(buildForensicTimelineCsv(summary()).charCodeAt(0)).toBe(0xfeff)
  })
})
