import { describe, expect, it } from 'vitest'

import {
  computeForensicAggregates,
  computeForensicFlags,
  type AggregatesInput,
} from '../user-forensics.aggregates'
import type { ForensicEvent } from '../user-forensics.types'
import type { VideoTrackingStat } from '../user-forensics.queries.content'

function event(partial: Partial<ForensicEvent> & { type: ForensicEvent['type'] }): ForensicEvent {
  return {
    id: partial.id ?? Math.random().toString(36),
    type: partial.type,
    atUtc: partial.atUtc ?? '2026-07-18T15:00:00.000Z',
    title: partial.title ?? partial.type,
    detail: partial.detail,
    score: partial.score,
    refIds: partial.refIds,
    meta: partial.meta,
  }
}

const videoStats: VideoTrackingStat[] = [
  { lessonId: 'l1', hasProgress: true, watchedPct: 1, playbackRate: 1, spedUp: false, barelyWatched: false, watchedFull: true, videoMinutes: 10 },
  { lessonId: 'l2', hasProgress: true, watchedPct: 0.05, playbackRate: 2, spedUp: true, barelyWatched: true, watchedFull: false, videoMinutes: 1 },
]

const input: AggregatesInput = {
  events: [
    event({ type: 'lesson_started', id: 'ls1' }),
    event({ type: 'lesson_started', id: 'ls2' }),
    event({ type: 'lesson_completed', id: 'lc1' }),
    // Un mismo quiz con 3 intentos, ninguno aprobado.
    event({ type: 'quiz_attempt', refIds: { lessonId: 'l1' }, meta: { isPassed: false } }),
    event({ type: 'quiz_attempt', refIds: { lessonId: 'l1' }, meta: { isPassed: false } }),
    event({ type: 'quiz_attempt', refIds: { lessonId: 'l1' }, meta: { isPassed: false } }),
    // Diálogo iniciado sin resultado → abandonado.
    event({ type: 'dialogue_started', refIds: { sessionId: 's1' } }),
    event({ type: 'course_enrolled', meta: { completed: true } }),
    event({ type: 'activity_submission', meta: { status: 'validated' } }),
  ],
  sessions: [
    { id: 'a', ipAddress: '1.1.1.1', userAgent: 'UA', deviceFingerprint: 'd1', createdAtUtc: '2026-07-18T14:00:00.000Z', lastUsedAtUtc: null, expiresAtUtc: null, isRevoked: false, revokedAtUtc: null, revokedReason: null },
    { id: 'b', ipAddress: '2.2.2.2', userAgent: 'UA', deviceFingerprint: 'd1', createdAtUtc: '2026-07-18T16:00:00.000Z', lastUsedAtUtc: null, expiresAtUtc: null, isRevoked: false, revokedAtUtc: null, revokedReason: null },
  ],
  accessIps: [],
  dialoguesAvailable: 0,
  videoStats,
  notes: [
    { id: 'n1', title: 'x', content: 'c', isAutoGenerated: false, isUserEdited: false, lessonId: null, createdAtUtc: '2026-07-18T15:00:00.000Z', updatedAtUtc: null },
    { id: 'n2', title: 'y', content: 'c', isAutoGenerated: true, isUserEdited: false, lessonId: null, createdAtUtc: '2026-07-18T15:00:00.000Z', updatedAtUtc: null },
  ],
  certificate: { count: 1, lastIssuedAtUtc: '2026-07-18T17:00:00.000Z' },
  lia: { conversations: 2, abandoned: 1, totalMessages: 20 },
}

describe('computeForensicAggregates', () => {
  const aggregates = computeForensicAggregates(input)

  it('humanizes access from sessions (distinct IPs, one device)', () => {
    expect(aggregates.access.totalLogins).toBe(2)
    expect(aggregates.access.distinctIps).toBe(2)
    expect(aggregates.access.distinctDevices).toBe(1)
  })

  it('detects sped-up and barely-watched videos', () => {
    expect(aggregates.lessons.videosSpedUp).toBe(1)
    expect(aggregates.lessons.videosBarelyWatched).toBe(1)
    expect(aggregates.lessons.videosWatchedFull).toBe(1)
    expect(aggregates.lessons.maxPlaybackRate).toBe(2)
  })

  it('counts quiz attempts and the max on a single quiz', () => {
    expect(aggregates.quizzes.totalAttempts).toBe(3)
    expect(aggregates.quizzes.distinctQuizzes).toBe(1)
    expect(aggregates.quizzes.passed).toBe(0)
    expect(aggregates.quizzes.maxAttemptsOnSingleQuiz).toBe(3)
  })

  it('counts a started dialogue with no result as abandoned', () => {
    expect(aggregates.dialogues.total).toBe(1)
    expect(aggregates.dialogues.abandoned).toBe(1)
  })

  it('counts notes, courses and activities', () => {
    expect(aggregates.notes.userWritten).toBe(1)
    expect(aggregates.notes.autoGenerated).toBe(1)
    expect(aggregates.courses.completed).toBe(1)
    expect(aggregates.activities.validated).toBe(1)
  })
})

describe('computeForensicFlags', () => {
  it('raises flags for sped-up video, barely watched and brute-forced quiz — but NOT for IPs at different times', () => {
    const flags = computeForensicFlags(computeForensicAggregates(input))
    const keys = flags.map((f) => f.key)
    expect(keys).toContain('videosSpedUp')
    expect(keys).toContain('videosBarelyWatched')
    expect(keys).toContain('manyQuizAttempts')
    expect(keys).toContain('dialoguesAbandoned')
    // Las 2 IPs del input están a 2 horas → NO es concurrencia → sin flag de acceso.
    expect(keys).not.toContain('concurrentSessions')
    expect(keys).not.toContain('multipleIps')
  })

  it('flags concurrent sessions only when two IPs occur within the window', () => {
    const concurrentInput: AggregatesInput = {
      ...input,
      sessions: [
        { id: 'a', ipAddress: '1.1.1.1', userAgent: 'UA', deviceFingerprint: 'd1', createdAtUtc: '2026-07-18T14:00:00.000Z', lastUsedAtUtc: null, expiresAtUtc: null, isRevoked: false, revokedAtUtc: null, revokedReason: null },
        { id: 'b', ipAddress: '9.9.9.9', userAgent: 'UA', deviceFingerprint: 'd2', createdAtUtc: '2026-07-18T14:05:00.000Z', lastUsedAtUtc: null, expiresAtUtc: null, isRevoked: false, revokedAtUtc: null, revokedReason: null },
      ],
    }
    const aggregates = computeForensicAggregates(concurrentInput)
    expect(aggregates.access.concurrentSessions).toBeGreaterThan(0)
    expect(computeForensicFlags(aggregates).map((f) => f.key)).toContain('concurrentSessions')
  })
})
