import type { TourConfig } from '@/features/tours'

export const businessPanelReportsTour: TourConfig = {
  id: 'business-panel-reports',
  autoStart: true,
  steps: [
    {
      target: '#tour-reports-hero',
      titleKey: 'tours.businessPanelReports.hero.title',
      contentKey: 'tours.businessPanelReports.hero.content',
      placement: 'bottom',
      disableBeacon: true,
    },
    {
      target: '#tour-reports-filters',
      titleKey: 'tours.businessPanelReports.filters.title',
      contentKey: 'tours.businessPanelReports.filters.content',
      placement: 'bottom',
      disableBeacon: true,
    },
    {
      target: '#tour-reports-kpi',
      titleKey: 'tours.businessPanelReports.kpi.title',
      contentKey: 'tours.businessPanelReports.kpi.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-workforce',
      titleKey: 'tours.businessPanelReports.workforce.title',
      contentKey: 'tours.businessPanelReports.workforce.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-radar',
      titleKey: 'tours.businessPanelReports.radar.title',
      contentKey: 'tours.businessPanelReports.radar.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-compliance',
      titleKey: 'tours.businessPanelReports.compliance.title',
      contentKey: 'tours.businessPanelReports.compliance.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-risk-users',
      titleKey: 'tours.businessPanelReports.riskUsers.title',
      contentKey: 'tours.businessPanelReports.riskUsers.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-funnel',
      titleKey: 'tours.businessPanelReports.funnel.title',
      contentKey: 'tours.businessPanelReports.funnel.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-course-risk',
      titleKey: 'tours.businessPanelReports.courseRisk.title',
      contentKey: 'tours.businessPanelReports.courseRisk.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-scatter',
      titleKey: 'tours.businessPanelReports.scatter.title',
      contentKey: 'tours.businessPanelReports.scatter.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-ranking',
      titleKey: 'tours.businessPanelReports.ranking.title',
      contentKey: 'tours.businessPanelReports.ranking.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-segments',
      titleKey: 'tours.businessPanelReports.segments.title',
      contentKey: 'tours.businessPanelReports.segments.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-trend',
      titleKey: 'tours.businessPanelReports.trend.title',
      contentKey: 'tours.businessPanelReports.trend.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-academic',
      titleKey: 'tours.businessPanelReports.academic.title',
      contentKey: 'tours.businessPanelReports.academic.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-soflia-quality',
      titleKey: 'tours.businessPanelReports.sofliaQuality.title',
      contentKey: 'tours.businessPanelReports.sofliaQuality.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-planner',
      titleKey: 'tours.businessPanelReports.planner.title',
      contentKey: 'tours.businessPanelReports.planner.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-notes',
      titleKey: 'tours.businessPanelReports.notes.title',
      contentKey: 'tours.businessPanelReports.notes.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
    {
      target: '#tour-reports-insights',
      titleKey: 'tours.businessPanelReports.insights.title',
      contentKey: 'tours.businessPanelReports.insights.content',
      placement: 'top',
      disableBeacon: true,
      optional: true,
    },
  ],
}
