import type { BusinessUserAnalyticsAiSample } from '../../../types/business-user-analytics.types'
import { ActivityEvaluationRecord } from './activity-evaluation-record'
import { extractSubmissionText } from './extract-submission-text'
import { normalizeQuizScore } from './normalize-quiz-score'
import { pushSample } from './push-sample'
import { QueryData } from './query-data'
import { resolveCourseTitle } from './resolve-course-title'
import { stringifySampleContent } from './stringify-sample-content'

export function buildAiSamples(
  data: QueryData,
  courseTitleById: Map<string, string>,
  enrollmentCourseById: Map<string, string>,
  evaluationsBySubmission: Map<string, ActivityEvaluationRecord>,
): BusinessUserAnalyticsAiSample[] {
  const samples: BusinessUserAnalyticsAiSample[] = []

  for (const message of data.liaMessages.filter((item) => item.role === 'user')) {
    if (samples.length >= 35) break
    const conversation = data.liaConversations.find((item) => item.conversation_id === message.conversation_id)
    pushSample(samples, {
      source: 'soflia_message',
      text: message.content,
      courseTitle: conversation?.course_id ? resolveCourseTitle(courseTitleById, conversation.course_id) : undefined,
      signals: {
        containsQuestion: message.contains_question,
        offTopic: message.is_off_topic,
        sentiment: message.sentiment_score,
      },
    })
  }

  for (const submission of data.activitySubmissions) {
    if (samples.length >= 55) break
    const evaluation = evaluationsBySubmission.get(submission.submission_id)
    pushSample(samples, {
      source: 'activity_response',
      text: extractSubmissionText(submission),
      courseTitle: resolveCourseTitle(courseTitleById, submission.course_id),
      signals: {
        status: submission.status,
        evaluation: evaluation?.result_status || null,
      },
    })
  }

  for (const quiz of data.quizSubmissions) {
    if (samples.length >= 65) break
    const courseId = enrollmentCourseById.get(quiz.enrollment_id)
    pushSample(samples, {
      source: 'quiz_response',
      text: stringifySampleContent(quiz.user_answers),
      courseTitle: courseId ? resolveCourseTitle(courseTitleById, courseId) : undefined,
      signals: {
        score: normalizeQuizScore(quiz),
        passed: quiz.is_passed,
      },
    })
  }

  for (const note of data.lessonNotes) {
    if (samples.length >= 80) break
    pushSample(samples, {
      source: 'note',
      text: note.note_content,
      signals: {
        autoGenerated: note.is_auto_generated,
        source: note.source_type || null,
      },
    })
  }

  return samples
}
