import type { BusinessUserAnalyticsPeriod } from '../../../types/business-user-analytics.types'
import { buildBreakdown, calculateAverage, calculatePercentage, calculateQualityScore, clampPercentage, incrementMap } from '../../reports-analytics/reports-analytics.helpers'
import { buildTrend } from './build-trend'
import { QueryData } from './query-data'
import { roundNumber } from './round-number'

export function buildNotes(data: QueryData, period: BusinessUserAnalyticsPeriod, lessonsCompleted: number) {
  const autoGenerated = data.lessonNotes.filter((note) => note.is_auto_generated).length
  const manual = data.lessonNotes.length - autoGenerated
  const lessonsWithNotes = new Set(data.lessonNotes.map((note) => note.lesson_id)).size
  const sourceCounts = new Map<string, number>()
  data.lessonNotes.forEach((note) => incrementMap(sourceCounts, note.source_type || 'manual'))
  const averageLength = calculateAverage(data.lessonNotes.map((note) => note.note_content?.length || 0))
  const contentCompleteness = calculatePercentage(data.lessonNotes.filter((note) => Boolean(note.note_content?.trim())).length, data.lessonNotes.length)

  // CALIDAD de notas: SOLO las escritas por el alumno (no las auto-generadas por IA,
  // que son largas y de alta calidad y falseaban el score a ~100). Un usuario que no
  // toma notas propias no debe puntuar alto en esta dimensión.
  const userNotes = data.lessonNotes.filter((note) => !note.is_auto_generated)
  const lessonsWithUserNotes = new Set(userNotes.map((note) => note.lesson_id)).size
  const userContentCompleteness = calculatePercentage(
    userNotes.filter((note) => Boolean(note.note_content?.trim())).length,
    userNotes.length,
  )
  const userAverageLength = calculateAverage(userNotes.map((note) => note.note_content?.length || 0))
  const notesScore = calculateQualityScore([
    calculatePercentage(lessonsWithUserNotes, Math.max(lessonsCompleted, lessonsWithUserNotes)),
    userContentCompleteness,
    clampPercentage(userAverageLength / 4),
  ])

  return {
    totalNotes: data.lessonNotes.length,
    manualNotes: manual,
    autoGeneratedNotes: autoGenerated,
    lessonsWithNotes,
    adoptionRate: calculatePercentage(lessonsWithNotes, Math.max(lessonsCompleted, lessonsWithNotes)),
    averageLength: roundNumber(averageLength),
    notesScore,
    bySource: buildBreakdown(sourceCounts, data.lessonNotes.length),
    notesTrend: buildTrend(data.lessonNotes.map((note) => note.created_at || note.updated_at).filter((value): value is string => Boolean(value)), period),
  }
}
