import JSZip from 'jszip'
import type { Cell, Row, Workbook, Worksheet } from 'exceljs'
import type {
  ReportsAnalyticsBreakdownItem,
  ReportsAnalyticsDataset,
  ReportsAnalyticsLocale,
  ReportsAnalyticsReportBlueprint,
  ReportsAnalyticsTrendPoint,
} from '../../types/reports-analytics.types'
import { buildCsv } from './reports-analytics.helpers'

type ExportRow = Record<string, unknown>
type ExportColumn = { key: string; header: string }
type ExcelTableColumn = ExportColumn & {
  width?: number
  numberFormat?: string
  kind?: 'text' | 'integer' | 'decimal' | 'percent' | 'date'
}

interface ExportCopy {
  title: string
  generatedAt: string
  period: string
  summary: string
  dashboard: string
  trends: string
  users: string
  courses: string
  segments: string
  activities: string
  quality: string
  dataQuality: string
  risks: string
  recommendations: string
  rawData: string
  missingField: string
  connections: string
  value: string
  detail: string
  metric: string
  chart: string
  noData: string
  files: Record<string, string>
  metrics: Record<string, string>
  columns: Record<string, string>
  dimensions: Record<string, Record<string, string>>
}

const EXPORT_COPY: Record<ReportsAnalyticsLocale, ExportCopy> = {
  es: {
    title: 'Reporte ejecutivo de Analytics',
    generatedAt: 'Generado',
    period: 'Periodo',
    summary: 'Resumen ejecutivo',
    dashboard: 'Dashboard',
    trends: 'Tendencias',
    users: 'Usuarios',
    courses: 'Cursos',
    segments: 'Segmentos',
    activities: 'Actividades y evaluaciones',
    quality: 'Calidad',
    dataQuality: 'Calidad de datos',
    risks: 'Riesgos',
    recommendations: 'Recomendaciones',
    rawData: 'Datos crudos',
    missingField: 'Campo faltante',
    connections: 'Conexiones',
    value: 'Valor',
    detail: 'Detalle',
    metric: 'Indicador',
    chart: 'Vista',
    noData: 'Sin datos',
    files: {
      executive: 'resumen_ejecutivo',
      users: 'detalle_usuarios',
      demographics: 'demografia',
      courses: 'progreso_cursos',
      learningTrend: 'tendencia_aprendizaje',
      soflia: 'uso_soflia',
      sofliaTrend: 'tendencia_soflia',
      activities: 'actividades_evaluaciones',
      notes: 'uso_notas',
      planner: 'planificacion',
      heatmap: 'mapa_conexiones',
      calendar: 'calendario_conexiones',
      segments: 'analisis_segmentos',
      quality: 'calidad_respuestas',
      hierarchy: 'ranking_jerarquia',
      userRanking: 'ranking_usuarios',
      samples: 'muestras_ia_anonimizadas',
      dataQuality: 'calidad_datos',
    },
    metrics: {
      totalUsers: 'Usuarios totales',
      activeLearners: 'Usuarios activos',
      activeLearnerRate: 'Porcentaje de usuarios activos',
      averageProgress: 'Progreso promedio',
      completionRate: 'Finalizacion de cursos',
      overdueAssignments: 'Asignaciones vencidas',
      sofliaAdoptionRate: 'Adopcion SofLIA',
      notesAdoptionRate: 'Adopcion de notas',
      activityCompletionRate: 'Actividades completadas',
      plannerAdherenceRate: 'Cumplimiento de planificacion',
      quizAverageScore: 'Promedio de evaluaciones',
      qualityScore: 'Calidad global',
      totalConversations: 'Conversaciones SofLIA',
      totalMessages: 'Mensajes SofLIA',
      averageMessagesPerConversation: 'Mensajes por conversacion',
      completedConversations: 'Conversaciones completadas',
      totalActivities: 'Actividades registradas',
      completedActivities: 'Actividades completadas',
      totalEvaluations: 'Evaluaciones respondidas',
      evaluationCompletionRate: 'Aprobacion de evaluaciones',
      averageAttempts: 'Intentos promedio',
      averageTimeMinutes: 'Tiempo promedio en actividades',
      usersNeedingHelp: 'Usuarios que necesitaron ayuda',
      redirects: 'Redirecciones SofLIA',
      totalNotes: 'Notas creadas',
      usersWithNotes: 'Usuarios con notas',
      autoGenerated: 'Notas autogeneradas',
      manual: 'Notas manuales',
      plannedSessions: 'Sesiones planificadas',
      completedSessions: 'Sesiones completadas',
      missedSessions: 'Sesiones perdidas',
      rescheduledSessions: 'Sesiones reprogramadas',
      adherenceRate: 'Cumplimiento',
      averagePlannedMinutes: 'Minutos planificados promedio',
      averageActualMinutes: 'Minutos reales promedio',
    },
    columns: {
      user: 'Usuario',
      email: 'Correo',
      status: 'Estado',
      role: 'Rol',
      jobTitle: 'Puesto',
      gender: 'Genero',
      age: 'Edad',
      ageBand: 'Rango de edad',
      region: 'Region',
      zone: 'Zona',
      team: 'Area o equipo',
      assigned: 'Cursos asignados',
      completed: 'Cursos completados',
      progress: 'Progreso promedio',
      overdue: 'Vencidos',
      lessons: 'Lecciones completadas',
      minutes: 'Minutos de estudio',
      sofliaConversations: 'Conversaciones SofLIA',
      sofliaMessages: 'Mensajes SofLIA',
      notes: 'Notas',
      activities: 'Actividades completadas',
      attempts: 'Intentos de actividades',
      evaluations: 'Evaluaciones respondidas',
      score: 'Promedio evaluaciones',
      quality: 'Calidad',
      planned: 'Sesiones planificadas',
      plannerDone: 'Sesiones completadas',
      plannerMissed: 'Sesiones perdidas',
      plannerRate: 'Cumplimiento planificador',
      lastConnection: 'Ultima conexion',
      lastActivity: 'Ultima actividad',
      course: 'Curso',
      active: 'Usuarios activos',
      notesCount: 'Notas',
      category: 'Categoria',
      key: 'Clave legible',
      label: 'Etiqueta',
      value: 'Valor',
      percentage: 'Porcentaje',
      period: 'Periodo',
      granularity: 'Agrupacion',
      secondary: 'Valor secundario',
      day: 'Dia',
      hour: 'Hora',
      intensity: 'Intensidad',
      date: 'Fecha',
      segment: 'Segmento',
      segmentType: 'Tipo de segmento',
      rank: 'Ranking',
      type: 'Tipo',
      name: 'Nombre',
      source: 'Fuente',
      text: 'Texto anonimizado',
      signals: 'Senales',
    },
    dimensions: {
      gender: {
        female: 'Mujer',
        male: 'Hombre',
        non_binary: 'No binario',
        other: 'Otro',
        prefer_not_to_say: 'Prefiere no decirlo',
        unspecified: 'No especificado',
      },
      progress: {
        not_started: 'Sin iniciar',
        low: '1-25%',
        medium: '26-50%',
        high: '51-75%',
        almost_done: '76-99%',
        completed: '100%',
      },
      age: {
        under_18: 'Menor de 18',
        '18_24': '18-24',
        '25_34': '25-34',
        '35_44': '35-44',
        '45_54': '45-54',
        '55_plus': '55+',
        unspecified: 'No especificado',
      },
      source: {
        soflia_message: 'Mensaje SofLIA',
        activity_response: 'Respuesta de actividad',
        quiz_response: 'Respuesta de evaluacion',
        note: 'Nota',
      },
    },
  },
  en: {
    title: 'Executive Analytics Report',
    generatedAt: 'Generated',
    period: 'Period',
    summary: 'Executive summary',
    dashboard: 'Dashboard',
    trends: 'Trends',
    users: 'Users',
    courses: 'Courses',
    segments: 'Segments',
    activities: 'Activities and assessments',
    quality: 'Quality',
    dataQuality: 'Data quality',
    risks: 'Risks',
    recommendations: 'Recommendations',
    rawData: 'Raw data',
    missingField: 'Missing field',
    connections: 'Connections',
    value: 'Value',
    detail: 'Detail',
    metric: 'Metric',
    chart: 'View',
    noData: 'No data',
    files: {
      executive: 'executive_summary',
      users: 'user_detail',
      demographics: 'demographics',
      courses: 'course_progress',
      learningTrend: 'learning_trend',
      soflia: 'soflia_usage',
      sofliaTrend: 'soflia_trend',
      activities: 'activities_assessments',
      notes: 'notes_usage',
      planner: 'planning',
      heatmap: 'connection_heatmap',
      calendar: 'connection_calendar',
      segments: 'segment_analysis',
      quality: 'response_quality',
      hierarchy: 'hierarchy_ranking',
      userRanking: 'user_ranking',
      samples: 'anonymized_ai_samples',
      dataQuality: 'data_quality',
    },
    metrics: {
      totalUsers: 'Total users',
      activeLearners: 'Active learners',
      activeLearnerRate: 'Active learner rate',
      averageProgress: 'Average progress',
      completionRate: 'Course completion',
      overdueAssignments: 'Overdue assignments',
      sofliaAdoptionRate: 'SofLIA adoption',
      notesAdoptionRate: 'Notes adoption',
      activityCompletionRate: 'Activity completion',
      plannerAdherenceRate: 'Planning adherence',
      quizAverageScore: 'Assessment average',
      qualityScore: 'Overall quality',
      totalConversations: 'SofLIA conversations',
      totalMessages: 'SofLIA messages',
      averageMessagesPerConversation: 'Messages per conversation',
      completedConversations: 'Completed conversations',
      totalActivities: 'Recorded activities',
      completedActivities: 'Completed activities',
      totalEvaluations: 'Answered assessments',
      evaluationCompletionRate: 'Assessment pass rate',
      averageAttempts: 'Average attempts',
      averageTimeMinutes: 'Average activity minutes',
      usersNeedingHelp: 'Users needing help',
      redirects: 'SofLIA redirects',
      totalNotes: 'Created notes',
      usersWithNotes: 'Users with notes',
      autoGenerated: 'Auto-generated notes',
      manual: 'Manual notes',
      plannedSessions: 'Planned sessions',
      completedSessions: 'Completed sessions',
      missedSessions: 'Missed sessions',
      rescheduledSessions: 'Rescheduled sessions',
      adherenceRate: 'Adherence',
      averagePlannedMinutes: 'Average planned minutes',
      averageActualMinutes: 'Average actual minutes',
    },
    columns: {},
    dimensions: {},
  },
  pt: {
    title: 'Relatorio executivo de Analytics',
    generatedAt: 'Gerado',
    period: 'Periodo',
    summary: 'Resumo executivo',
    dashboard: 'Dashboard',
    trends: 'Tendencias',
    users: 'Usuarios',
    courses: 'Cursos',
    segments: 'Segmentos',
    activities: 'Atividades e avaliacoes',
    quality: 'Qualidade',
    dataQuality: 'Qualidade dos dados',
    risks: 'Riscos',
    recommendations: 'Recomendacoes',
    rawData: 'Dados brutos',
    missingField: 'Campo faltante',
    connections: 'Conexoes',
    value: 'Valor',
    detail: 'Detalhe',
    metric: 'Indicador',
    chart: 'Vista',
    noData: 'Sem dados',
    files: {
      executive: 'resumo_executivo',
      users: 'detalhe_usuarios',
      demographics: 'demografia',
      courses: 'progresso_cursos',
      learningTrend: 'tendencia_aprendizagem',
      soflia: 'uso_soflia',
      sofliaTrend: 'tendencia_soflia',
      activities: 'atividades_avaliacoes',
      notes: 'uso_notas',
      planner: 'planejamento',
      heatmap: 'mapa_conexoes',
      calendar: 'calendario_conexoes',
      segments: 'analise_segmentos',
      quality: 'qualidade_respostas',
      hierarchy: 'ranking_hierarquia',
      userRanking: 'ranking_usuarios',
      samples: 'amostras_ia_anonimizadas',
      dataQuality: 'qualidade_dados',
    },
    metrics: {},
    columns: {},
    dimensions: {},
  },
}

const PDF_COLORS = {
  primary: [10, 37, 64] as const,
  accent: [0, 180, 150] as const,
  text: [17, 24, 39] as const,
  muted: [82, 94, 112] as const,
  line: [220, 226, 235] as const,
  surface: [247, 249, 252] as const,
  success: [16, 185, 129] as const,
  warning: [245, 158, 11] as const,
}

const EXCEL_COLORS = {
  primary: 'FF0A2540',
  accent: 'FF00D4B3',
  accentSoft: 'FFD9FBF5',
  surface: 'FFF8FAFC',
  border: 'FFDCE2EB',
  text: 'FF111827',
  muted: 'FF526070',
  success: 'FF10B981',
  warning: 'FFF59E0B',
  danger: 'FFEF4444',
  white: 'FFFFFFFF',
}

export async function generateReportsAnalyticsZip(
  dataset: ReportsAnalyticsDataset,
  locale: ReportsAnalyticsLocale = 'es',
  blueprint?: ReportsAnalyticsReportBlueprint,
): Promise<Uint8Array> {
  const copy = getExportCopy(locale)
  const zip = new JSZip()
  const reportBlueprint = resolveExportBlueprint(dataset, locale, blueprint)

  zip.file(`${copy.files.executive}.csv`, buildExecutiveSummaryCsv(dataset, copy, locale, reportBlueprint))
  zip.file(`${copy.files.users}.csv`, buildUsersDetailCsv(dataset, copy))
  zip.file(`${copy.files.demographics}.csv`, buildBreakdownCsv([
    ...withCategory('Genero', dataset.demographics.gender, copy, 'gender'),
    ...withCategory('Edad', dataset.demographics.ageBands, copy, 'age'),
    ...withCategory('Puesto', dataset.demographics.jobTitles, copy),
    ...withCategory('Rol', dataset.demographics.roles, copy),
  ], copy))
  zip.file(`${copy.files.courses}.csv`, buildCourseProgressCsv(dataset, copy))
  zip.file(`${copy.files.learningTrend}.csv`, buildTrendCsv(
    dataset.learning.completionsTrend,
    copy.metrics.completionRate,
    dataset.filters.granularity,
    copy,
  ))
  zip.file(`${copy.files.soflia}.csv`, buildSofliaCsv(dataset, copy))
  zip.file(`${copy.files.sofliaTrend}.csv`, buildTrendCsv(
    dataset.soflia.conversationsTrend,
    copy.metrics.totalConversations,
    dataset.filters.granularity,
    copy,
  ))
  zip.file(`${copy.files.activities}.csv`, buildActivitiesCsv(dataset, copy))
  zip.file(`${copy.files.notes}.csv`, buildNotesCsv(dataset, copy))
  zip.file(`${copy.files.planner}.csv`, buildPlannerCsv(dataset, copy))
  zip.file(`${copy.files.heatmap}.csv`, buildLoginHeatmapCsv(dataset, copy))
  zip.file(`${copy.files.calendar}.csv`, buildConnectionCalendarCsv(dataset, copy))
  zip.file(`${copy.files.segments}.csv`, buildSegmentAnalysisCsv(dataset, copy))
  zip.file(`${copy.files.quality}.csv`, buildQualityCsv(dataset, copy))
  zip.file(`${copy.files.hierarchy}.csv`, buildHierarchyRankingCsv(dataset, copy))
  zip.file(`${copy.files.userRanking}.csv`, buildUserRankingCsv(dataset, copy))
  zip.file(`${copy.files.samples}.csv`, buildAiSamplesCsv(dataset, copy))
  zip.file(`${copy.files.dataQuality}.csv`, buildBreakdownCsv(withCategory('Campo faltante', dataset.dataQuality.missingFields, copy), copy))

  return zip.generateAsync({ type: 'uint8array' })
}

export async function generateReportsAnalyticsWorkbook(
  dataset: ReportsAnalyticsDataset,
  locale: ReportsAnalyticsLocale = 'es',
  blueprint?: ReportsAnalyticsReportBlueprint,
): Promise<Uint8Array> {
  const ExcelJS = await import('exceljs')
  const copy = getExportCopy(locale)
  const reportBlueprint = resolveExportBlueprint(dataset, locale, blueprint)
  const workbook = new ExcelJS.Workbook()

  workbook.creator = 'SofLIA'
  workbook.created = new Date()
  workbook.modified = new Date()
  workbook.properties.date1904 = false

  buildExecutiveWorkbookSheet(workbook, dataset, copy, locale, reportBlueprint)
  buildDashboardWorkbookSheet(workbook, dataset, copy, locale, reportBlueprint)
  buildTrendsWorkbookSheet(workbook, dataset, copy)
  buildCoursesWorkbookSheet(workbook, dataset, copy)
  buildUsersWorkbookSheet(workbook, dataset, copy)
  buildSegmentsWorkbookSheet(workbook, dataset, copy)
  buildQualityWorkbookSheet(workbook, dataset, copy)
  buildRawDataWorkbookSheet(workbook, dataset, copy)

  const output = await workbook.xlsx.writeBuffer()
  return output instanceof Uint8Array ? output : new Uint8Array(output)
}

export async function generateReportsAnalyticsPdf(
  dataset: ReportsAnalyticsDataset,
  locale: ReportsAnalyticsLocale,
  blueprint?: ReportsAnalyticsReportBlueprint,
): Promise<Uint8Array> {
  const JsPDF = (await import('jspdf')).default
  const pdf = new JsPDF('p', 'pt', 'a4')
  const copy = getExportCopy(locale)
  const reportBlueprint = resolveExportBlueprint(dataset, locale, blueprint)
  const page = {
    width: pdf.internal.pageSize.getWidth(),
    height: pdf.internal.pageSize.getHeight(),
    margin: 40,
  }
  let y = 0

  const ensureSpace = (height: number) => {
    if (y + height <= page.height - page.margin) return
    pdf.addPage()
    addHeader(false)
  }

  const addHeader = (firstPage: boolean) => {
    y = page.margin
    pdf.setFillColor(...PDF_COLORS.primary)
    pdf.roundedRect(page.margin, y, page.width - page.margin * 2, 86, 10, 10, 'F')
    pdf.setTextColor(255, 255, 255)
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(firstPage ? 22 : 16)
    pdf.text(copy.title, page.margin + 24, y + 34)
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(10)
    pdf.text(`${copy.generatedAt}: ${new Date(dataset.generatedAt).toLocaleString(locale)}`, page.margin + 24, y + 56)
    pdf.text(`${copy.period}: ${formatDate(dataset.period.from, locale)} - ${formatDate(dataset.period.to, locale)}`, page.margin + 24, y + 72)
    y += 112
  }

  const section = (title: string) => {
    ensureSpace(34)
    pdf.setTextColor(...PDF_COLORS.text)
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(15)
    pdf.text(title, page.margin, y)
    y += 22
  }

  const paragraph = (text: string) => {
    pdf.setTextColor(...PDF_COLORS.muted)
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(10)
    pdf.splitTextToSize(text, page.width - page.margin * 2).forEach((line: string) => {
      ensureSpace(15)
      pdf.text(line, page.margin, y)
      y += 14
    })
    y += 8
  }

  const metricGrid = (items: Array<{ label: string; value: string | number; detail?: string }>) => {
    const gap = 12
    const columns = 2
    const cardWidth = (page.width - page.margin * 2 - gap) / columns
    const cardHeight = 66
    items.forEach((item, index) => {
      const column = index % columns
      if (column === 0) ensureSpace(cardHeight + 10)
      const x = page.margin + column * (cardWidth + gap)
      const cardY = y
      pdf.setFillColor(...PDF_COLORS.surface)
      pdf.roundedRect(x, cardY, cardWidth, cardHeight, 8, 8, 'F')
      pdf.setDrawColor(...PDF_COLORS.line)
      pdf.roundedRect(x, cardY, cardWidth, cardHeight, 8, 8, 'S')
      pdf.setTextColor(...PDF_COLORS.muted)
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(8)
      pdf.text(item.label, x + 12, cardY + 18)
      pdf.setTextColor(...PDF_COLORS.text)
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(18)
      pdf.text(String(item.value), x + 12, cardY + 42)
      if (item.detail) {
        pdf.setFont('helvetica', 'normal')
        pdf.setFontSize(8)
        pdf.setTextColor(...PDF_COLORS.muted)
        pdf.text(item.detail, x + 12, cardY + 56)
      }
      if (column === columns - 1 || index === items.length - 1) y += cardHeight + 10
    })
  }

  const progressBar = (label: string, value: number) => {
    ensureSpace(30)
    const width = page.width - page.margin * 2
    pdf.setTextColor(...PDF_COLORS.text)
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(9)
    pdf.text(`${label}: ${value}%`, page.margin, y)
    y += 8
    pdf.setFillColor(...PDF_COLORS.line)
    pdf.roundedRect(page.margin, y, width, 7, 3, 3, 'F')
    pdf.setFillColor(...PDF_COLORS.accent)
    pdf.roundedRect(page.margin, y, width * clampRatio(value), 7, 3, 3, 'F')
    y += 18
  }

  const table = (headers: string[], rows: string[][], widths: number[]) => {
    const rowHeight = 22
    ensureSpace(rowHeight * (rows.length + 2))
    pdf.setFillColor(...PDF_COLORS.primary)
    pdf.rect(page.margin, y, page.width - page.margin * 2, rowHeight, 'F')
    pdf.setTextColor(255, 255, 255)
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(8)
    let x = page.margin + 8
    headers.forEach((header, index) => {
      pdf.text(header, x, y + 14)
      x += widths[index]
    })
    y += rowHeight
    rows.forEach((row, rowIndex) => {
      ensureSpace(rowHeight)
      if (rowIndex % 2 === 0) {
        pdf.setFillColor(...PDF_COLORS.surface)
        pdf.rect(page.margin, y, page.width - page.margin * 2, rowHeight, 'F')
      }
      pdf.setTextColor(...PDF_COLORS.text)
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(8)
      x = page.margin + 8
      row.forEach((cell, index) => {
        const text = pdf.splitTextToSize(String(cell), widths[index] - 10)[0] || ''
        pdf.text(text, x, y + 14)
        x += widths[index]
      })
      y += rowHeight
    })
    y += 10
  }

  addHeader(true)
  section(copy.summary)
  paragraph(reportBlueprint.summary)
  metricGrid([
    { label: copy.metrics.totalUsers, value: dataset.overview.totalUsers, detail: `${copy.metrics.activeLearners}: ${dataset.overview.activeLearners}` },
    { label: copy.metrics.averageProgress, value: `${dataset.overview.averageProgress}%`, detail: `${copy.metrics.completionRate}: ${dataset.overview.completionRate}%` },
    { label: copy.metrics.sofliaAdoptionRate, value: `${dataset.overview.sofliaAdoptionRate}%`, detail: `${dataset.soflia.totalConversations} conversaciones` },
    { label: copy.metrics.qualityScore, value: `${dataset.overview.qualityScore}%`, detail: `${dataset.activities.quizAttempts} evaluaciones` },
  ])

  section(copy.trends)
  progressBar(copy.metrics.averageProgress, dataset.overview.averageProgress)
  progressBar(copy.metrics.completionRate, dataset.overview.completionRate)
  progressBar(copy.metrics.activityCompletionRate, dataset.activities.completionRate)
  progressBar(copy.metrics.plannerAdherenceRate, dataset.overview.plannerAdherenceRate)

  section(copy.activities)
  metricGrid([
    { label: copy.metrics.totalActivities, value: dataset.activities.totalActivities },
    { label: copy.metrics.completedActivities, value: dataset.activities.completedActivities },
    { label: copy.metrics.totalEvaluations, value: dataset.activities.totalEvaluations },
    { label: copy.metrics.quizAverageScore, value: `${dataset.activities.quizAverageScore}%` },
  ])

  section(copy.courses)
  table(
    [copy.columns.course, copy.columns.assigned, copy.columns.active, copy.columns.completed, copy.columns.progress, copy.columns.overdue],
    dataset.courses.slice(0, 10).map((course) => [
      course.courseTitle,
      String(course.assignedUsers),
      String(course.activeLearners),
      String(course.completedUsers),
      `${course.averageProgress}%`,
      String(course.overdueAssignments),
    ]),
    [190, 58, 52, 64, 64, 58],
  )

  section(copy.segments)
  table(
    [copy.columns.segmentType, copy.columns.label, copy.columns.user, copy.columns.progress, copy.columns.quality],
    buildSegmentRows(dataset, copy).slice(0, 12).map((row) => [
      String(row.segmentType),
      String(row.label),
      String(row.users),
      `${row.averageProgress}%`,
      `${row.qualityScore}%`,
    ]),
    [86, 180, 60, 76, 76],
  )

  section(copy.dataQuality)
  metricGrid([
    { label: 'Demografia completa', value: `${dataset.dataQuality.demographicsCompletionRate}%` },
    { label: 'Usuarios completos', value: dataset.dataQuality.usersWithCompleteDemographics },
    { label: 'Usuarios incompletos', value: dataset.dataQuality.usersMissingDemographics },
    { label: 'Evidencias analizadas', value: dataset.quality.evidenceCount },
  ])

  return new Uint8Array(pdf.output('arraybuffer'))
}

export function buildReportsAnalyticsFilename(
  extension: 'zip' | 'xlsx' | 'pdf',
  dataset: Pick<ReportsAnalyticsDataset, 'period'>,
): string {
  const from = dataset.period.from.slice(0, 10)
  const to = dataset.period.to.slice(0, 10)
  return `soflia-analytics-${from}-${to}.${extension}`
}

function buildExecutiveSummaryCsv(
  dataset: ReportsAnalyticsDataset,
  copy: ExportCopy,
  locale: ReportsAnalyticsLocale,
  blueprint: ReportsAnalyticsReportBlueprint,
): string {
  return toCsv([
    { metric: copy.generatedAt, value: new Date(dataset.generatedAt).toLocaleString(locale), detail: '' },
    { metric: copy.period, value: `${formatDate(dataset.period.from, locale)} - ${formatDate(dataset.period.to, locale)}`, detail: '' },
    { metric: copy.summary, value: blueprint.summary, detail: blueprint.source },
    ...blueprint.featuredMetrics.map((metric) => ({
      metric: metric.label,
      value: metric.value,
      detail: metric.detail,
    })),
    ...blueprint.recommendations.slice(0, 5).map((recommendation, index) => ({
      metric: `Recomendacion ${index + 1}`,
      value: recommendation,
      detail: '',
    })),
    ...buildExecutiveMetricRows(dataset, copy),
  ], getMetricColumns(copy))
}

function buildUsersDetailCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv(buildUserDetailRows(dataset), getUserColumns(copy))
}

function buildCourseProgressCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv(buildCourseProgressRows(dataset), getCourseColumns(copy))
}

function buildSofliaCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv([
    { metric: copy.metrics.totalConversations, value: dataset.soflia.totalConversations, detail: '' },
    { metric: copy.metrics.totalMessages, value: dataset.soflia.totalMessages, detail: '' },
    { metric: copy.metrics.activeLearners, value: dataset.soflia.activeUsers, detail: '' },
    { metric: copy.metrics.averageMessagesPerConversation, value: dataset.soflia.averageMessagesPerConversation, detail: '' },
    { metric: copy.metrics.completedConversations, value: `${dataset.soflia.completionRate}%`, detail: '' },
    ...withCategory('Contexto SofLIA', dataset.soflia.contextBreakdown, copy).map((row) => ({
      metric: row.label,
      value: row.value,
      detail: `${row.percentage}%`,
    })),
  ], getMetricColumns(copy))
}

function buildActivitiesCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv(buildActivitiesRows(dataset, copy), getMetricColumns(copy))
}

function buildNotesCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv([
    { metric: copy.metrics.totalNotes, value: dataset.notes.totalNotes, detail: '' },
    { metric: copy.metrics.usersWithNotes, value: dataset.notes.usersWithNotes, detail: `${dataset.notes.adoptionRate}%` },
    { metric: copy.metrics.autoGenerated, value: dataset.notes.autoGenerated, detail: '' },
    { metric: copy.metrics.manual, value: dataset.notes.manual, detail: '' },
    ...withCategory('Curso', dataset.notes.byCourse, copy).map((row) => ({
      metric: row.label,
      value: row.value,
      detail: `${row.percentage}%`,
    })),
  ], getMetricColumns(copy))
}

function buildPlannerCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv([
    { metric: copy.metrics.plannedSessions, value: dataset.planner.plannedSessions, detail: '' },
    { metric: copy.metrics.completedSessions, value: dataset.planner.completedSessions, detail: '' },
    { metric: copy.metrics.missedSessions, value: dataset.planner.missedSessions, detail: '' },
    { metric: copy.metrics.rescheduledSessions, value: dataset.planner.rescheduledSessions, detail: '' },
    { metric: copy.metrics.adherenceRate, value: `${dataset.planner.adherenceRate}%`, detail: '' },
    { metric: copy.metrics.averagePlannedMinutes, value: dataset.planner.averagePlannedMinutes, detail: '' },
    { metric: copy.metrics.averageActualMinutes, value: dataset.planner.averageActualMinutes, detail: '' },
  ], getMetricColumns(copy))
}

function buildQualityCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv(buildQualityRows(dataset, copy), getMetricColumns(copy))
}

function buildLoginHeatmapCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv(
    dataset.loginHeatmap.map((cell) => ({
      day: translateWeekday(cell.dayKey),
      hour: cell.hourLabel,
      value: cell.value,
      percentage: cell.percentage,
    })),
    [
      { key: 'day', header: copy.columns.day },
      { key: 'hour', header: copy.columns.hour },
      { key: 'value', header: 'Conexiones' },
      { key: 'percentage', header: copy.columns.intensity },
    ],
  )
}

function buildConnectionCalendarCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv(
    dataset.connectionCalendar.map((cell) => ({
      date: cell.date,
      day: translateWeekday(cell.dayKey),
      value: cell.value,
      intensity: cell.level,
    })),
    [
      { key: 'date', header: copy.columns.date },
      { key: 'day', header: copy.columns.day },
      { key: 'value', header: 'Conexiones' },
      { key: 'intensity', header: copy.columns.intensity },
    ],
  )
}

function buildSegmentAnalysisCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv(buildSegmentRows(dataset, copy), getSegmentColumns(copy))
}

function buildHierarchyRankingCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv(
    [
      ...dataset.rankings.regions,
      ...dataset.rankings.zones,
      ...dataset.rankings.teams,
    ].map((row) => ({
      type: row.type,
      name: row.name,
      region: row.regionName || '',
      zone: row.zoneName || '',
      users: row.users,
      progress: row.averageProgress,
      completion: row.completionRate,
      soflia: row.sofliaAdoptionRate,
      notes: row.notesAdoptionRate,
      quality: row.qualityScore,
      overdue: row.overdueAssignments,
      score: row.rankScore,
    })),
    [
      { key: 'type', header: copy.columns.type },
      { key: 'name', header: copy.columns.name },
      { key: 'region', header: copy.columns.region },
      { key: 'zone', header: copy.columns.zone },
      { key: 'users', header: copy.columns.user },
      { key: 'progress', header: copy.columns.progress },
      { key: 'completion', header: 'Finalizacion' },
      { key: 'soflia', header: 'SofLIA' },
      { key: 'notes', header: copy.columns.notes },
      { key: 'quality', header: copy.columns.quality },
      { key: 'overdue', header: copy.columns.overdue },
      { key: 'score', header: copy.columns.score },
    ],
  )
}

function buildUserRankingCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv(
    dataset.rankings.users.map((row, index) => ({
      rank: index + 1,
      user: row.displayName,
      email: row.email,
      jobTitle: row.jobTitle,
      region: row.regionName,
      zone: row.zoneName,
      team: row.teamName,
      progress: row.averageProgress,
      completion: row.completionRate,
      soflia: row.sofliaConversations,
      notes: row.notesCreated,
      quality: row.qualityScore,
      overdue: row.overdueAssignments,
      score: row.rankScore,
    })),
    [
      { key: 'rank', header: copy.columns.rank },
      { key: 'user', header: copy.columns.user },
      { key: 'email', header: copy.columns.email },
      { key: 'jobTitle', header: copy.columns.jobTitle },
      { key: 'region', header: copy.columns.region },
      { key: 'zone', header: copy.columns.zone },
      { key: 'team', header: copy.columns.team },
      { key: 'progress', header: copy.columns.progress },
      { key: 'completion', header: 'Finalizacion' },
      { key: 'soflia', header: 'SofLIA' },
      { key: 'notes', header: copy.columns.notes },
      { key: 'quality', header: copy.columns.quality },
      { key: 'overdue', header: copy.columns.overdue },
      { key: 'score', header: copy.columns.score },
    ],
  )
}

function buildAiSamplesCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv(
    dataset.aiSamples.map((sample) => ({
      source: translateDimension(copy, 'source', sample.source),
      course: sample.courseTitle || '',
      ageBand: sample.segment?.ageBand || '',
      gender: translateDimension(copy, 'gender', sample.segment?.gender || ''),
      jobTitle: sample.segment?.jobTitle || '',
      region: sample.segment?.regionName || '',
      zone: sample.segment?.zoneName || '',
      team: sample.segment?.teamName || '',
      text: sample.text,
      signals: JSON.stringify(sample.signals),
    })),
    [
      { key: 'source', header: copy.columns.source },
      { key: 'course', header: copy.columns.course },
      { key: 'ageBand', header: copy.columns.ageBand },
      { key: 'gender', header: copy.columns.gender },
      { key: 'jobTitle', header: copy.columns.jobTitle },
      { key: 'region', header: copy.columns.region },
      { key: 'zone', header: copy.columns.zone },
      { key: 'team', header: copy.columns.team },
      { key: 'text', header: copy.columns.text },
      { key: 'signals', header: copy.columns.signals },
    ],
  )
}

function buildBreakdownCsv(rows: ExportRow[], copy: ExportCopy): string {
  return toCsv(rows, [
    { key: 'category', header: copy.columns.category },
    { key: 'label', header: copy.columns.label },
    { key: 'value', header: copy.columns.value },
    { key: 'percentage', header: copy.columns.percentage },
  ])
}

function buildTrendCsv(
  rows: ReportsAnalyticsTrendPoint[],
  metric: string,
  granularity: string,
  copy: ExportCopy,
): string {
  return toCsv(
    rows.map((row) => ({
      period: row.label,
      granularity,
      metric,
      value: row.value,
      secondary: row.secondaryValue ?? '',
    })),
    [
      { key: 'period', header: copy.columns.period },
      { key: 'granularity', header: copy.columns.granularity },
      { key: 'metric', header: copy.metric },
      { key: 'value', header: copy.columns.value },
      { key: 'secondary', header: copy.columns.secondary },
    ],
  )
}

function buildExecutiveWorkbookSheet(
  workbook: Workbook,
  dataset: ReportsAnalyticsDataset,
  copy: ExportCopy,
  locale: ReportsAnalyticsLocale,
  blueprint: ReportsAnalyticsReportBlueprint,
): void {
  const sheet = addStyledWorksheet(workbook, 'Resumen SofLIA')
  setColumns(sheet, [24, 18, 36, 18, 24, 18, 26, 18])
  addTitleBlock(sheet, copy.title, [
    `${copy.generatedAt}: ${new Date(dataset.generatedAt).toLocaleString(locale)}`,
    `${copy.period}: ${formatDate(dataset.period.from, locale)} - ${formatDate(dataset.period.to, locale)}`,
    `SofLIA: ${blueprint.source} (${blueprint.model})`,
  ], 8)

  sheet.mergeCells('A6:H8')
  const summaryCell = sheet.getCell('A6')
  summaryCell.value = blueprint.summary
  summaryCell.alignment = { vertical: 'middle', wrapText: true }
  summaryCell.font = { size: 12, color: { argb: EXCEL_COLORS.text } }
  summaryCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: EXCEL_COLORS.accentSoft } }
  applyBorder(summaryCell)

  addExcelTable(sheet, 'FeaturedMetricsTable', 10, 1, [
    { key: 'metric', header: copy.metric, width: 28, kind: 'text' },
    { key: 'value', header: copy.value, width: 18, kind: 'text' },
    { key: 'detail', header: copy.detail, width: 48, kind: 'text' },
  ], [
    ...blueprint.featuredMetrics.map((metric) => ({
      metric: metric.label,
      value: metric.value,
      detail: metric.detail,
    })),
    ...buildExecutiveMetricRows(dataset, copy),
  ])

  let nextRow = 10 + blueprint.featuredMetrics.length + buildExecutiveMetricRows(dataset, copy).length + 4
  nextRow = addSectionList(sheet, nextRow, copy.summary, blueprint.findings.flatMap((section) => [
    section.title,
    ...section.points.map((point) => `- ${point}`),
  ]))
  nextRow = addSectionList(sheet, nextRow + 1, 'Riesgos', blueprint.risks)
  addSectionList(sheet, nextRow + 1, 'Recomendaciones', blueprint.recommendations)
}

function buildDashboardWorkbookSheet(
  workbook: Workbook,
  dataset: ReportsAnalyticsDataset,
  copy: ExportCopy,
  locale: ReportsAnalyticsLocale,
  blueprint: ReportsAnalyticsReportBlueprint,
): void {
  const sheet = addStyledWorksheet(workbook, copy.dashboard)
  setColumns(sheet, [22, 16, 22, 16, 22, 16, 22, 16])
  addTitleBlock(sheet, copy.dashboard, [
    `${copy.period}: ${formatDate(dataset.period.from, locale)} - ${formatDate(dataset.period.to, locale)}`,
    blueprint.summary,
  ], 8)

  const cards = [
    { label: copy.metrics.totalUsers, value: dataset.overview.totalUsers, detail: `${copy.metrics.activeLearners}: ${dataset.overview.activeLearners}` },
    { label: copy.metrics.averageProgress, value: `${dataset.overview.averageProgress}%`, detail: `${copy.metrics.completionRate}: ${dataset.overview.completionRate}%` },
    { label: copy.metrics.sofliaAdoptionRate, value: `${dataset.overview.sofliaAdoptionRate}%`, detail: `${dataset.soflia.totalConversations} conversaciones` },
    { label: copy.metrics.qualityScore, value: `${dataset.overview.qualityScore}%`, detail: `${dataset.quality.evidenceCount} evidencias` },
  ]
  cards.forEach((card, index) => {
    const startCol = index % 2 === 0 ? 1 : 5
    const startRow = index < 2 ? 6 : 10
    addMetricCard(sheet, startRow, startCol, card.label, card.value, card.detail)
  })

  addExcelTable(sheet, 'DashboardMetricsTable', 15, 1, [
    { key: 'metric', header: copy.metric, width: 32, kind: 'text' },
    { key: 'value', header: copy.value, width: 18, kind: 'text' },
    { key: 'detail', header: copy.detail, width: 48, kind: 'text' },
  ], buildExecutiveMetricRows(dataset, copy))

  addExcelTable(sheet, 'DashboardCourseRiskTable', 15, 5, [
    { key: 'course', header: copy.columns.course, width: 38, kind: 'text' },
    { key: 'progress', header: copy.columns.progress, width: 16, kind: 'percent' },
    { key: 'overdue', header: copy.columns.overdue, width: 12, kind: 'integer' },
  ], dataset.courses
    .slice()
    .sort((a, b) => b.overdueAssignments - a.overdueAssignments || a.averageProgress - b.averageProgress)
    .slice(0, 10)
    .map((course) => ({
      course: course.courseTitle,
      progress: course.averageProgress,
      overdue: course.overdueAssignments,
    })))
}

function buildTrendsWorkbookSheet(
  workbook: Workbook,
  dataset: ReportsAnalyticsDataset,
  copy: ExportCopy,
): void {
  const sheet = addStyledWorksheet(workbook, copy.trends)
  setColumns(sheet, [18, 22, 22, 22, 22, 22])
  addTitleBlock(sheet, copy.trends, [copy.metrics.completionRate, copy.metrics.totalConversations], 6)
  addExcelTable(sheet, 'TrendsTable', 6, 1, [
    { key: 'period', header: copy.columns.period, width: 18, kind: 'text' },
    { key: 'completionRate', header: copy.metrics.completionRate, width: 20, kind: 'integer' },
    { key: 'sofliaConversations', header: copy.metrics.totalConversations, width: 22, kind: 'integer' },
    { key: 'granularity', header: copy.columns.granularity, width: 18, kind: 'text' },
  ], dataset.learning.completionsTrend.map((point, index) => ({
    period: point.label,
    completionRate: point.value,
    sofliaConversations: dataset.soflia.conversationsTrend[index]?.value || 0,
    granularity: dataset.filters.granularity,
  })))
}

function buildCoursesWorkbookSheet(
  workbook: Workbook,
  dataset: ReportsAnalyticsDataset,
  copy: ExportCopy,
): void {
  const sheet = addStyledWorksheet(workbook, copy.courses)
  addTitleBlock(sheet, copy.courses, [copy.columns.progress, copy.columns.overdue], 11)
  addExcelTable(sheet, 'CoursesTable', 6, 1, getWorkbookCourseColumns(copy), buildCourseProgressRows(dataset))
}

function buildUsersWorkbookSheet(
  workbook: Workbook,
  dataset: ReportsAnalyticsDataset,
  copy: ExportCopy,
): void {
  const sheet = addStyledWorksheet(workbook, copy.users)
  addTitleBlock(sheet, copy.users, [copy.columns.email, copy.columns.progress], 12)
  addExcelTable(sheet, 'UsersTable', 6, 1, getWorkbookUserColumns(copy), buildUserDetailRows(dataset))
}

function buildSegmentsWorkbookSheet(
  workbook: Workbook,
  dataset: ReportsAnalyticsDataset,
  copy: ExportCopy,
): void {
  const sheet = addStyledWorksheet(workbook, copy.segments)
  addTitleBlock(sheet, copy.segments, [copy.columns.segmentType, copy.columns.quality], 10)
  addExcelTable(sheet, 'SegmentsTable', 6, 1, getWorkbookSegmentColumns(copy), buildSegmentRows(dataset, copy))
}

function buildQualityWorkbookSheet(
  workbook: Workbook,
  dataset: ReportsAnalyticsDataset,
  copy: ExportCopy,
): void {
  const sheet = addStyledWorksheet(workbook, copy.quality)
  setColumns(sheet, [34, 18, 44, 24, 18, 18])
  addTitleBlock(sheet, copy.quality, [copy.metrics.qualityScore], 6)
  const nextRow = addExcelTable(sheet, 'QualityMetricsTable', 6, 1, [
    { key: 'metric', header: copy.metric, width: 34, kind: 'text' },
    { key: 'value', header: copy.value, width: 18, kind: 'text' },
    { key: 'detail', header: copy.detail, width: 44, kind: 'text' },
  ], buildQualityRows(dataset, copy))
  addExcelTable(sheet, 'DataQualityTable', nextRow + 2, 1, [
    { key: 'category', header: copy.columns.category, width: 32, kind: 'text' },
    { key: 'label', header: copy.columns.label, width: 36, kind: 'text' },
    { key: 'value', header: copy.columns.value, width: 16, kind: 'integer' },
    { key: 'percentage', header: copy.columns.percentage, width: 18, kind: 'percent' },
  ], withCategory('Campo faltante', dataset.dataQuality.missingFields, copy))
}

function buildRawDataWorkbookSheet(
  workbook: Workbook,
  dataset: ReportsAnalyticsDataset,
  copy: ExportCopy,
): void {
  const sheet = addStyledWorksheet(workbook, 'Datos crudos')
  setColumns(sheet, [28, 22, 22, 22, 22, 22, 22, 22])
  addTitleBlock(sheet, 'Datos crudos', [copy.dataQuality], 8)
  let nextRow = addExcelTable(sheet, 'RawOverviewTable', 6, 1, [
    { key: 'metric', header: copy.metric, width: 34, kind: 'text' },
    { key: 'value', header: copy.value, width: 18, kind: 'text' },
    { key: 'detail', header: copy.detail, width: 44, kind: 'text' },
  ], buildExecutiveMetricRows(dataset, copy))
  nextRow = addExcelTable(sheet, 'RawActivitiesTable', nextRow + 2, 1, getMetricColumns(copy), buildActivitiesRows(dataset, copy))
  addExcelTable(sheet, 'RawAiSamplesTable', nextRow + 2, 1, [
    { key: 'source', header: copy.columns.source, width: 24, kind: 'text' },
    { key: 'course', header: copy.columns.course, width: 36, kind: 'text' },
    { key: 'text', header: copy.columns.text, width: 72, kind: 'text' },
  ], dataset.aiSamples.slice(0, 30).map((sample) => ({
    source: translateDimension(copy, 'source', sample.source),
    course: sample.courseTitle || '',
    text: sample.text,
  })))
}

function buildExecutiveMetricRows(dataset: ReportsAnalyticsDataset, copy: ExportCopy): ExportRow[] {
  return [
    { metric: copy.metrics.totalUsers, value: dataset.overview.totalUsers, rawValue: dataset.overview.totalUsers, detail: `${copy.metrics.activeLearners}: ${dataset.overview.activeLearners} (${dataset.overview.activeLearnerRate}%)` },
    { metric: copy.metrics.averageProgress, value: `${dataset.overview.averageProgress}%`, rawValue: dataset.overview.averageProgress, detail: `${copy.metrics.completionRate}: ${dataset.overview.completionRate}%` },
    { metric: copy.metrics.sofliaAdoptionRate, value: `${dataset.overview.sofliaAdoptionRate}%`, rawValue: dataset.overview.sofliaAdoptionRate, detail: `${dataset.soflia.totalConversations} conversaciones, ${dataset.soflia.totalMessages} mensajes` },
    { metric: copy.metrics.notesAdoptionRate, value: `${dataset.overview.notesAdoptionRate}%`, rawValue: dataset.overview.notesAdoptionRate, detail: `${dataset.notes.totalNotes} notas` },
    { metric: copy.metrics.activityCompletionRate, value: `${dataset.activities.completionRate}%`, rawValue: dataset.activities.completionRate, detail: `${dataset.activities.completedActivities}/${dataset.activities.totalActivities}` },
    { metric: copy.metrics.quizAverageScore, value: `${dataset.activities.quizAverageScore}%`, rawValue: dataset.activities.quizAverageScore, detail: `${dataset.activities.quizAttempts} evaluaciones` },
    { metric: copy.metrics.plannerAdherenceRate, value: `${dataset.overview.plannerAdherenceRate}%`, rawValue: dataset.overview.plannerAdherenceRate, detail: `${dataset.planner.completedSessions}/${dataset.planner.plannedSessions}` },
    { metric: copy.metrics.qualityScore, value: `${dataset.overview.qualityScore}%`, rawValue: dataset.overview.qualityScore, detail: `${dataset.quality.evidenceCount} evidencias` },
  ]
}

function buildUserDetailRows(dataset: ReportsAnalyticsDataset): ExportRow[] {
  return dataset.userDetails.map((user) => ({
    user: user.displayName,
    email: user.email,
    status: user.status,
    role: user.role,
    jobTitle: user.jobTitle,
    gender: user.gender,
    age: user.age ?? '',
    ageBand: user.ageBand,
    region: user.regionName,
    zone: user.zoneName,
    team: user.teamName,
    assigned: user.coursesAssigned,
    completed: user.coursesCompleted,
    progress: user.averageProgress,
    overdue: user.overdueAssignments,
    lessons: user.completedLessons,
    minutes: user.timeSpentMinutes,
    sofliaConversations: user.sofliaConversations,
    sofliaMessages: user.sofliaMessages,
    notes: user.notesCreated,
    activities: user.activitiesCompleted,
    attempts: user.activityAttempts,
    evaluations: user.quizAttempts,
    score: user.quizAverageScore,
    quality: user.qualityScore,
    planned: user.plannedSessions,
    plannerDone: user.completedSessions,
    plannerMissed: user.missedSessions,
    plannerRate: user.plannerAdherenceRate,
    lastConnection: user.lastConnectionAt || '',
    lastActivity: user.lastActivityAt || '',
  }))
}

function buildCourseProgressRows(dataset: ReportsAnalyticsDataset): ExportRow[] {
  return dataset.courses.map((course) => ({
    course: course.courseTitle,
    assigned: course.assignedUsers,
    active: course.activeLearners,
    completed: course.completedUsers,
    progress: course.averageProgress,
    overdue: course.overdueAssignments,
    notesCount: course.notesCount,
    sofliaConversations: course.sofliaConversations,
    activities: course.activityCompletionRate,
    score: course.quizAverageScore,
  }))
}

function buildActivitiesRows(dataset: ReportsAnalyticsDataset, copy: ExportCopy): ExportRow[] {
  return [
    { metric: copy.metrics.totalActivities, value: dataset.activities.totalActivities, detail: '' },
    { metric: copy.metrics.completedActivities, value: dataset.activities.completedActivities, detail: `${dataset.activities.completionRate}%` },
    { metric: copy.metrics.totalEvaluations, value: dataset.activities.totalEvaluations, detail: `${copy.metrics.quizAverageScore}: ${dataset.activities.quizAverageScore}%` },
    { metric: copy.metrics.evaluationCompletionRate, value: `${dataset.activities.evaluationCompletionRate}%`, detail: '' },
    { metric: copy.metrics.averageAttempts, value: dataset.activities.averageAttempts, detail: '' },
    { metric: copy.metrics.averageTimeMinutes, value: dataset.activities.averageTimeMinutes, detail: '' },
    { metric: copy.metrics.usersNeedingHelp, value: dataset.activities.usersNeedingHelp, detail: '' },
    { metric: copy.metrics.redirects, value: dataset.activities.redirects, detail: '' },
    ...withCategory('Tipo de actividad', dataset.activities.byType, copy).map((row) => ({
      metric: row.label,
      value: row.value,
      detail: `${row.percentage}%`,
    })),
  ]
}

function buildQualityRows(dataset: ReportsAnalyticsDataset, copy: ExportCopy): ExportRow[] {
  return [
    { metric: copy.metrics.qualityScore, value: `${dataset.quality.overallScore}%`, detail: `${dataset.quality.evidenceCount} evidencias` },
    { metric: 'Calidad de evaluaciones', value: `${dataset.quality.quizScore}%`, detail: `${dataset.quality.quizPassRate}% aprobacion` },
    { metric: 'Calidad de actividades', value: `${dataset.quality.activityScore}%`, detail: `${dataset.quality.activityCompletionRate}% completadas` },
    { metric: 'Calidad SofLIA', value: `${dataset.quality.sofliaScore}%`, detail: `${dataset.quality.questionRate}% preguntas` },
    { metric: 'Calidad de notas', value: `${dataset.quality.notesScore}%`, detail: '' },
    { metric: 'Ayuda requerida', value: `${dataset.quality.helpRate}%`, detail: '' },
    { metric: 'Fuera de tema', value: `${dataset.quality.offTopicRate}%`, detail: '' },
    { metric: 'Tiempo promedio de respuesta', value: `${dataset.quality.averageResponseTimeSeconds}s`, detail: '' },
  ]
}

function buildSegmentRows(dataset: ReportsAnalyticsDataset, copy: ExportCopy): ExportRow[] {
  return [
    ...withSegment('Edad', dataset.segments.ageBands, copy, 'age'),
    ...withSegment('Genero', dataset.segments.gender, copy, 'gender'),
    ...withSegment('Puesto', dataset.segments.jobTitles, copy),
    ...withSegment('Rol', dataset.segments.roles, copy),
  ]
}

function getMetricColumns(copy: ExportCopy): ExportColumn[] {
  return [
    { key: 'metric', header: copy.metric },
    { key: 'value', header: copy.value },
    { key: 'detail', header: copy.detail },
  ]
}

function getUserColumns(copy: ExportCopy): ExportColumn[] {
  return [
    'user',
    'email',
    'status',
    'role',
    'jobTitle',
    'gender',
    'age',
    'ageBand',
    'region',
    'zone',
    'team',
    'assigned',
    'completed',
    'progress',
    'overdue',
    'lessons',
    'minutes',
    'sofliaConversations',
    'sofliaMessages',
    'notes',
    'activities',
    'attempts',
    'evaluations',
    'score',
    'quality',
    'planned',
    'plannerDone',
    'plannerMissed',
    'plannerRate',
    'lastConnection',
    'lastActivity',
  ].map((key) => ({ key, header: copy.columns[key] || key }))
}

function getCourseColumns(copy: ExportCopy): ExportColumn[] {
  return [
    'course',
    'assigned',
    'active',
    'completed',
    'progress',
    'overdue',
    'notesCount',
    'sofliaConversations',
    'activities',
    'score',
  ].map((key) => ({ key, header: copy.columns[key] || key }))
}

function getSegmentColumns(copy: ExportCopy): ExportColumn[] {
  return [
    { key: 'segmentType', header: copy.columns.segmentType },
    { key: 'label', header: copy.columns.label },
    { key: 'users', header: copy.columns.user },
    { key: 'averageProgress', header: copy.columns.progress },
    { key: 'completionRate', header: 'Finalizacion' },
    { key: 'averageCompletionDays', header: 'Dias promedio' },
    { key: 'sofliaAdoptionRate', header: 'SofLIA' },
    { key: 'notesAdoptionRate', header: copy.columns.notes },
    { key: 'quizAverageScore', header: copy.columns.score },
    { key: 'qualityScore', header: copy.columns.quality },
  ]
}

function getWorkbookCourseColumns(copy: ExportCopy): ExcelTableColumn[] {
  return getCourseColumns(copy).map((column) => ({
    ...column,
    width: {
      course: 46,
      assigned: 16,
      active: 16,
      completed: 18,
      progress: 18,
      overdue: 14,
      notesCount: 14,
      sofliaConversations: 20,
      activities: 22,
      score: 20,
    }[column.key] || 18,
    kind: ['progress', 'activities', 'score'].includes(column.key) ? 'percent' : 'integer',
  }))
}

function getWorkbookUserColumns(copy: ExportCopy): ExcelTableColumn[] {
  return getUserColumns(copy).map((column) => ({
    ...column,
    width: {
      user: 28,
      email: 34,
      jobTitle: 26,
      region: 22,
      zone: 22,
      team: 24,
      lastConnection: 22,
      lastActivity: 22,
    }[column.key] || 16,
    kind: ['progress', 'score', 'quality', 'plannerRate'].includes(column.key)
      ? 'percent'
      : ['lastConnection', 'lastActivity'].includes(column.key)
        ? 'date'
        : ['user', 'email', 'status', 'role', 'jobTitle', 'gender', 'ageBand', 'region', 'zone', 'team'].includes(column.key)
          ? 'text'
          : 'integer',
  }))
}

function getWorkbookSegmentColumns(copy: ExportCopy): ExcelTableColumn[] {
  return getSegmentColumns(copy).map((column) => ({
    ...column,
    width: {
      segmentType: 22,
      label: 32,
      users: 14,
    }[column.key] || 18,
    kind: ['averageProgress', 'completionRate', 'sofliaAdoptionRate', 'notesAdoptionRate', 'quizAverageScore', 'qualityScore'].includes(column.key)
      ? 'percent'
      : column.key === 'users'
        ? 'integer'
        : 'text',
  }))
}

function addStyledWorksheet(workbook: Workbook, name: string): Worksheet {
  const sheet = workbook.addWorksheet(sanitizeSheetName(name))
  sheet.properties.defaultRowHeight = 20
  sheet.views = [{ state: 'frozen', ySplit: 5 }]
  sheet.pageSetup = {
    orientation: 'landscape',
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
  }
  sheet.eachRow((row) => {
    row.alignment = { vertical: 'middle' }
  })
  return sheet
}

function setColumns(sheet: Worksheet, widths: number[]): void {
  sheet.columns = widths.map((width) => ({ width }))
}

function addTitleBlock(sheet: Worksheet, title: string, lines: string[], columnSpan: number): void {
  const endColumn = getColumnLetter(columnSpan)
  sheet.mergeCells(`A1:${endColumn}1`)
  sheet.getCell('A1').value = title
  sheet.getCell('A1').font = { bold: true, size: 18, color: { argb: EXCEL_COLORS.white } }
  sheet.getCell('A1').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: EXCEL_COLORS.primary } }
  sheet.getCell('A1').alignment = { vertical: 'middle' }
  sheet.getRow(1).height = 30

  lines.slice(0, 3).forEach((line, index) => {
    const rowNumber = index + 2
    sheet.mergeCells(`A${rowNumber}:${endColumn}${rowNumber}`)
    const cell = sheet.getCell(rowNumber, 1)
    cell.value = line
    cell.font = { color: { argb: EXCEL_COLORS.muted }, size: 10 }
    cell.alignment = { wrapText: true }
  })
}

function addMetricCard(
  sheet: Worksheet,
  row: number,
  column: number,
  label: string,
  value: string | number,
  detail: string,
): void {
  const endColumn = column + 2
  sheet.mergeCells(row, column, row, endColumn)
  sheet.mergeCells(row + 1, column, row + 1, endColumn)
  sheet.mergeCells(row + 2, column, row + 2, endColumn)
  const labelCell = sheet.getCell(row, column)
  const valueCell = sheet.getCell(row + 1, column)
  const detailCell = sheet.getCell(row + 2, column)
  labelCell.value = label
  valueCell.value = value
  detailCell.value = detail
  labelCell.font = { bold: true, color: { argb: EXCEL_COLORS.muted }, size: 9 }
  valueCell.font = { bold: true, color: { argb: EXCEL_COLORS.primary }, size: 18 }
  detailCell.font = { color: { argb: EXCEL_COLORS.muted }, size: 9 }
  for (let rowIndex = row; rowIndex <= row + 2; rowIndex += 1) {
    for (let colIndex = column; colIndex <= endColumn; colIndex += 1) {
      const cell = sheet.getCell(rowIndex, colIndex)
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: EXCEL_COLORS.surface } }
      applyBorder(cell)
    }
  }
}

function addExcelTable(
  sheet: Worksheet,
  tableName: string,
  startRow: number,
  startColumn: number,
  columns: ExcelTableColumn[],
  rows: ExportRow[],
): number {
  const safeRows = rows.length > 0 ? rows : [Object.fromEntries(columns.map((column) => [column.key, '']))]
  const tableRows = safeRows.map((row) => columns.map((column) => coerceExcelValue(row[column.key], column)))
  const ref = `${getColumnLetter(startColumn)}${startRow}`
  sheet.addTable({
    name: sanitizeTableName(tableName),
    ref,
    headerRow: true,
    totalsRow: false,
    style: {
      theme: 'TableStyleMedium2',
      showRowStripes: true,
    },
    columns: columns.map((column) => ({ name: column.header, filterButton: true })),
    rows: tableRows,
  })

  columns.forEach((column, index) => {
    const worksheetColumn = sheet.getColumn(startColumn + index)
    worksheetColumn.width = column.width || Math.min(Math.max(column.header.length + 4, 14), 42)
    for (let rowNumber = startRow + 1; rowNumber <= startRow + tableRows.length; rowNumber += 1) {
      const cell = sheet.getCell(rowNumber, startColumn + index)
      applyCellFormat(cell, column)
    }
    if (column.kind === 'percent' && tableRows.length > 0) {
      const col = getColumnLetter(startColumn + index)
      sheet.addConditionalFormatting({
        ref: `${col}${startRow + 1}:${col}${startRow + tableRows.length}`,
        rules: [
          {
            type: 'dataBar',
            priority: 1,
            showValue: true,
            cfvo: [
              { type: 'num', value: 0 },
              { type: 'num', value: 100 },
            ],
          },
        ],
      })
    }
  })

  styleTableHeader(sheet.getRow(startRow), startColumn, columns.length)
  sheet.autoFilter = {
    from: { row: startRow, column: startColumn },
    to: { row: startRow, column: startColumn + columns.length - 1 },
  }
  return startRow + tableRows.length + 1
}

function addSectionList(sheet: Worksheet, startRow: number, title: string, rows: string[]): number {
  sheet.getCell(startRow, 1).value = title
  sheet.getCell(startRow, 1).font = { bold: true, color: { argb: EXCEL_COLORS.primary }, size: 12 }
  rows.slice(0, 16).forEach((row, index) => {
    const rowNumber = startRow + index + 1
    sheet.mergeCells(`A${rowNumber}:H${rowNumber}`)
    const cell = sheet.getCell(rowNumber, 1)
    cell.value = row
    cell.alignment = { wrapText: true }
    cell.font = { color: { argb: EXCEL_COLORS.text } }
  })
  return startRow + rows.slice(0, 16).length + 1
}

function coerceExcelValue(value: unknown, column: ExcelTableColumn): string | number | Date {
  if (value === null || value === undefined) return ''
  if (column.kind === 'date') {
    const date = new Date(String(value))
    return Number.isNaN(date.getTime()) ? '' : date
  }
  if (column.kind === 'integer' || column.kind === 'decimal' || column.kind === 'percent') {
    if (typeof value === 'number') return value
    const parsed = Number.parseFloat(String(value).replace('%', ''))
    return Number.isFinite(parsed) ? parsed : String(value)
  }
  return typeof value === 'string' || typeof value === 'number' ? value : JSON.stringify(value)
}

function applyCellFormat(cell: Cell, column: ExcelTableColumn): void {
  cell.alignment = { vertical: 'middle', wrapText: column.kind === 'text' }
  applyBorder(cell)
  if (column.numberFormat) {
    cell.numFmt = column.numberFormat
    return
  }
  if (column.kind === 'integer') cell.numFmt = '#,##0'
  if (column.kind === 'decimal') cell.numFmt = '#,##0.0'
  if (column.kind === 'percent') cell.numFmt = '0.0"%"'
  if (column.kind === 'date') cell.numFmt = 'yyyy-mm-dd hh:mm'
}

function styleTableHeader(row: Row, startColumn: number, columnCount: number): void {
  row.height = 24
  for (let index = 0; index < columnCount; index += 1) {
    const cell = row.getCell(startColumn + index)
    cell.font = { bold: true, color: { argb: EXCEL_COLORS.white } }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: EXCEL_COLORS.primary } }
    cell.alignment = { vertical: 'middle', wrapText: true }
    applyBorder(cell)
  }
}

function applyBorder(cell: Cell): void {
  cell.border = {
    top: { style: 'thin', color: { argb: EXCEL_COLORS.border } },
    left: { style: 'thin', color: { argb: EXCEL_COLORS.border } },
    bottom: { style: 'thin', color: { argb: EXCEL_COLORS.border } },
    right: { style: 'thin', color: { argb: EXCEL_COLORS.border } },
  }
}

function toCsv(rows: ExportRow[], columns: ExportColumn[]): string {
  return buildCsv(rows, columns as Array<{ key: keyof ExportRow; header: string }>)
}

function withCategory(
  category: string,
  rows: ReportsAnalyticsBreakdownItem[],
  copy: ExportCopy,
  dimensionGroup?: string,
): ExportRow[] {
  return rows.map((row) => ({
    category,
    label: dimensionGroup ? translateDimension(copy, dimensionGroup, row.key, row.label) : row.label,
    value: row.value,
    percentage: row.percentage,
  }))
}

function withSegment(
  segmentType: string,
  rows: ReportsAnalyticsDataset['segments']['ageBands'],
  copy: ExportCopy,
  dimensionGroup?: string,
): ExportRow[] {
  return rows.map((row) => ({
    segmentType,
    label: dimensionGroup ? translateDimension(copy, dimensionGroup, row.key, row.label) : row.label,
    users: row.users,
    averageProgress: row.averageProgress,
    completionRate: row.completionRate,
    averageCompletionDays: row.averageCompletionDays,
    sofliaAdoptionRate: row.sofliaAdoptionRate,
    notesAdoptionRate: row.notesAdoptionRate,
    quizAverageScore: row.quizAverageScore,
    qualityScore: row.qualityScore,
  }))
}

function getExportCopy(locale: ReportsAnalyticsLocale): ExportCopy {
  const fallback = EXPORT_COPY.es
  const selected = EXPORT_COPY[locale] || fallback
  return {
    ...fallback,
    ...selected,
    files: { ...fallback.files, ...selected.files },
    metrics: { ...fallback.metrics, ...selected.metrics },
    columns: { ...fallback.columns, ...selected.columns },
    dimensions: {
      gender: { ...fallback.dimensions.gender, ...selected.dimensions.gender },
      progress: { ...fallback.dimensions.progress, ...selected.dimensions.progress },
      age: { ...fallback.dimensions.age, ...selected.dimensions.age },
      source: { ...fallback.dimensions.source, ...selected.dimensions.source },
    },
  }
}

function translateDimension(copy: ExportCopy, group: string, key: string, fallback = key): string {
  return copy.dimensions[group]?.[key] || fallback
}

function translateWeekday(dayKey: string): string {
  const days: Record<string, string> = {
    sun: 'Dom',
    mon: 'Lun',
    tue: 'Mar',
    wed: 'Mie',
    thu: 'Jue',
    fri: 'Vie',
    sat: 'Sab',
  }
  return days[dayKey] || dayKey
}

function clampRatio(value: number): number {
  if (!Number.isFinite(value)) return 0
  return Math.max(0, Math.min(1, value / 100))
}

function resolveExportBlueprint(
  dataset: ReportsAnalyticsDataset,
  locale: ReportsAnalyticsLocale,
  blueprint?: ReportsAnalyticsReportBlueprint,
): ReportsAnalyticsReportBlueprint {
  if (blueprint) return blueprint
  return {
    generatedAt: new Date().toISOString(),
    model: 'deterministic:fallback',
    source: 'fallback',
    summary: `${getExportCopy(locale).summary}: ${getExportCopy(locale).metrics.averageProgress} ${dataset.overview.averageProgress}%`,
    sections: [
      { id: 'executive', title: 'Resumen SofLIA', purpose: 'Resumen ejecutivo', priority: 1 },
      { id: 'dashboard', title: getExportCopy(locale).dashboard, purpose: 'Indicadores clave', priority: 2 },
      { id: 'trends', title: getExportCopy(locale).trends, purpose: 'Tendencias', priority: 3 },
      { id: 'courses', title: getExportCopy(locale).courses, purpose: 'Cursos', priority: 4 },
      { id: 'users', title: getExportCopy(locale).users, purpose: 'Usuarios', priority: 5 },
      { id: 'segments', title: getExportCopy(locale).segments, purpose: 'Segmentos', priority: 6 },
      { id: 'quality', title: getExportCopy(locale).quality, purpose: 'Calidad', priority: 7 },
      { id: 'rawData', title: 'Datos crudos', purpose: 'Datos base', priority: 8 },
    ],
    featuredMetrics: buildExecutiveMetricRows(dataset, getExportCopy(locale)).slice(0, 4).map((row) => ({
      label: String(row.metric || ''),
      value: String(row.value || ''),
      detail: String(row.detail || ''),
    })),
    findings: [],
    risks: [],
    recommendations: [],
    artifactPlan: [],
  }
}

function sanitizeSheetName(name: string): string {
  return name.replace(/[\][:*?/\\]/g, ' ').slice(0, 31) || 'Reporte'
}

function sanitizeTableName(name: string): string {
  const sanitized = name.replace(/[^A-Za-z0-9_]/g, '_').replace(/^(\d)/, '_$1')
  return sanitized.slice(0, 240) || 'ReportTable'
}

function getColumnLetter(index: number): string {
  let current = index
  let letters = ''
  while (current > 0) {
    const remainder = (current - 1) % 26
    letters = String.fromCharCode(65 + remainder) + letters
    current = Math.floor((current - remainder) / 26)
  }
  return letters
}

function formatDate(value: string, locale: ReportsAnalyticsLocale): string {
  return new Date(value).toLocaleDateString(locale)
}
