export type BusinessUserAnalyticsRange = '30d' | '90d' | '180d' | '365d'
export type BusinessUserAnalyticsLocale = 'es' | 'en' | 'pt'

export interface BusinessUserAnalyticsPeriod {
  from: string
  to: string
  range: BusinessUserAnalyticsRange
}

export interface BusinessUserAnalyticsTrendPoint {
  key: string
  label: string
  value: number
  secondaryValue?: number
}

export interface BusinessUserAnalyticsBreakdownItem {
  key: string
  label: string
  value: number
  percentage: number
}

export interface BusinessUserAnalyticsCalendarCell {
  date: string
  dayKey: string
  dayIndex: number
  weekIndex: number
  monthKey: string
  monthLabel: string
  value: number
  level: 0 | 1 | 2 | 3 | 4
}

export interface BusinessUserAnalyticsOverview {
  totalAssigned: number
  inProgressCourses: number
  completedCourses: number
  certificates: number
  averageProgress: number
  completionRate: number
  lessonsCompleted: number
  timeSpentMinutes: number
  activeDays: number
  currentStreak: number
  longestStreak: number
  lastActivityAt: string | null
  qualityScore: number
}

export interface BusinessUserAnalyticsCourseProgressRow {
  courseId: string
  courseTitle: string
  progress: number
  status: string
  assignedAt: string | null
  dueDate: string | null
  completedAt: string | null
  lastAccessedAt: string | null
  lessonsCompleted: number
  timeSpentMinutes: number
  hasCertificate: boolean
}

export interface BusinessUserAnalyticsLearning {
  courses: BusinessUserAnalyticsCourseProgressRow[]
  progressDistribution: BusinessUserAnalyticsBreakdownItem[]
  completionsTrend: BusinessUserAnalyticsTrendPoint[]
  lessonTrend: BusinessUserAnalyticsTrendPoint[]
}

export interface BusinessUserAnalyticsAiAdoption {
  totalConversations: number
  totalMessages: number
  userMessages: number
  liaMessages: number
  adoptionScore: number
  questionRate: number
  offTopicRate: number
  redirectRate: number
  averageResponseTimeSeconds: number
  averageSentiment: number
  questionQualityScore: number
  contextBreakdown: BusinessUserAnalyticsBreakdownItem[]
  messagesTrend: BusinessUserAnalyticsTrendPoint[]
}

export interface BusinessUserAnalyticsPlanning {
  plannedSessions: number
  completedSessions: number
  missedSessions: number
  rescheduledSessions: number
  adherenceRate: number
  averagePlannedMinutes: number
  averageActualMinutes: number
  byStatus: BusinessUserAnalyticsBreakdownItem[]
  sessionsTrend: BusinessUserAnalyticsTrendPoint[]
}

export interface BusinessUserAnalyticsNotes {
  totalNotes: number
  manualNotes: number
  autoGeneratedNotes: number
  lessonsWithNotes: number
  adoptionRate: number
  averageLength: number
  notesScore: number
  bySource: BusinessUserAnalyticsBreakdownItem[]
  notesTrend: BusinessUserAnalyticsTrendPoint[]
}

export interface BusinessUserAnalyticsActivities {
  totalSubmissions: number
  submitted: number
  validated: number
  needsRevision: number
  passRate: number
  averageQualityScore: number
  averageResponseLength: number
  withSofliaFeedback: number
  statusBreakdown: BusinessUserAnalyticsBreakdownItem[]
  submissionsTrend: BusinessUserAnalyticsTrendPoint[]
}

export interface BusinessUserAnalyticsQuizzes {
  attempts: number
  passed: number
  passRate: number
  averageScore: number
  bestScore: number
  latestScore: number
  trend: BusinessUserAnalyticsTrendPoint[]
}

export interface BusinessUserAnalyticsQuality {
  overallScore: number
  courseScore: number
  activityScore: number
  sofliaQuestionScore: number
  notesScore: number
  quizScore: number
  evidenceCount: number
  radar: BusinessUserAnalyticsBreakdownItem[]
}

export interface BusinessUserAnalyticsAiSample {
  source: 'soflia_message' | 'activity_response' | 'quiz_response' | 'note'
  text: string
  courseTitle?: string
  signals: Record<string, string | number | boolean | null>
}

export interface BusinessUserAnalyticsDataset {
  success: true
  generatedAt: string
  period: BusinessUserAnalyticsPeriod
  overview: BusinessUserAnalyticsOverview
  learning: BusinessUserAnalyticsLearning
  aiAdoption: BusinessUserAnalyticsAiAdoption
  planning: BusinessUserAnalyticsPlanning
  notes: BusinessUserAnalyticsNotes
  activities: BusinessUserAnalyticsActivities
  quizzes: BusinessUserAnalyticsQuizzes
  quality: BusinessUserAnalyticsQuality
  contributionCalendar: BusinessUserAnalyticsCalendarCell[]
  aiSamples: BusinessUserAnalyticsAiSample[]
  dataHash: string
}

export type BusinessUserAnalyticsResponse = Omit<
  BusinessUserAnalyticsDataset,
  'aiSamples' | 'dataHash'
>

export interface BusinessUserAnalyticsInsightMetric {
  label: string
  value: string
  detail: string
}

export interface BusinessUserAnalyticsInsightSection {
  title: string
  points: string[]
}

export interface BusinessUserAnalyticsInsights {
  generatedAt: string
  model: string
  cached: boolean
  expiresAt: string | null
  unavailable?: boolean
  summary: string
  metrics: BusinessUserAnalyticsInsightMetric[]
  strengths: string[]
  opportunities: string[]
  recommendations: string[]
  nextSteps: BusinessUserAnalyticsInsightSection[]
}

export interface BusinessUserAnalyticsInsightsResponse {
  success: true
  insights: BusinessUserAnalyticsInsights
}
