export type ReportsAnalyticsExportFormat = 'csv_zip' | 'xlsx' | 'pdf'
export type ReportsAnalyticsLocale = 'es' | 'en' | 'pt'
export type ReportsAnalyticsTimeGranularity = 'day' | 'month' | 'year'

export interface ReportsAnalyticsFilters {
  from: string
  to: string
  granularity: ReportsAnalyticsTimeGranularity
  courseId?: string
  gender?: string
  ageBand?: string
  jobTitle?: string
  role?: string
  status?: string
  regionId?: string
  zoneId?: string
  teamId?: string
}

export interface ReportsAnalyticsExportRequest extends ReportsAnalyticsFilters {
  format: ReportsAnalyticsExportFormat
  locale?: ReportsAnalyticsLocale
}

export interface ReportsAnalyticsBreakdownItem {
  key: string
  label: string
  value: number
  percentage: number
}

export interface ReportsAnalyticsTrendPoint {
  key: string
  label: string
  value: number
  secondaryValue?: number
}

export interface ReportsAnalyticsOverview {
  totalUsers: number
  activeLearners: number
  activeLearnerRate: number
  averageProgress: number
  completionRate: number
  averageCompletionDays: number
  overdueAssignments: number
  sofliaAdoptionRate: number
  notesAdoptionRate: number
  activityCompletionRate: number
  plannerAdherenceRate: number
  quizAverageScore: number
  qualityScore: number
}

export interface ReportsAnalyticsDemographics {
  gender: ReportsAnalyticsBreakdownItem[]
  ageBands: ReportsAnalyticsBreakdownItem[]
  jobTitles: ReportsAnalyticsBreakdownItem[]
  roles: ReportsAnalyticsBreakdownItem[]
  missingDateOfBirth: number
  missingGender: number
  missingJobTitle: number
}

export interface ReportsAnalyticsLearning {
  assignedCourses: number
  completedCourses: number
  inProgressCourses: number
  notStartedCourses: number
  overdueAssignments: number
  totalLessonsCompleted: number
  totalTimeSpentMinutes: number
  averageCompletionDays: number
  medianCompletionDays: number
  progressDistribution: ReportsAnalyticsBreakdownItem[]
  completionsTrend: ReportsAnalyticsTrendPoint[]
  completionsByMonth: ReportsAnalyticsTrendPoint[]
}

export interface ReportsAnalyticsCourseRow {
  courseId: string
  courseTitle: string
  assignedUsers: number
  activeLearners: number
  completedUsers: number
  averageProgress: number
  overdueAssignments: number
  notesCount: number
  sofliaConversations: number
  activityCompletionRate: number
  quizAverageScore: number
}

export interface ReportsAnalyticsSoflia {
  totalConversations: number
  totalMessages: number
  activeUsers: number
  averageMessagesPerConversation: number
  completionRate: number
  contextBreakdown: ReportsAnalyticsBreakdownItem[]
  conversationsTrend: ReportsAnalyticsTrendPoint[]
  conversationsByMonth: ReportsAnalyticsTrendPoint[]
}

export interface ReportsAnalyticsActivities {
  totalActivities: number
  completedActivities: number
  completionRate: number
  averageAttempts: number
  averageTimeMinutes: number
  usersNeedingHelp: number
  redirects: number
  totalEvaluations: number
  completedEvaluations: number
  evaluationCompletionRate: number
  quizAttempts: number
  quizPassRate: number
  quizAverageScore: number
  byType: ReportsAnalyticsBreakdownItem[]
}

export interface ReportsAnalyticsQuality {
  overallScore: number
  quizScore: number
  activityScore: number
  sofliaScore: number
  notesScore: number
  quizPassRate: number
  quizAverageScore: number
  activityCompletionRate: number
  helpRate: number
  redirectRate: number
  offTopicRate: number
  questionRate: number
  averageResponseTimeSeconds: number
  averageSentiment: number
  evidenceCount: number
  radar: ReportsAnalyticsBreakdownItem[]
}

export interface ReportsAnalyticsNotes {
  totalNotes: number
  usersWithNotes: number
  adoptionRate: number
  autoGenerated: number
  manual: number
  byCourse: ReportsAnalyticsBreakdownItem[]
}

export interface ReportsAnalyticsPlanner {
  plannedSessions: number
  completedSessions: number
  missedSessions: number
  rescheduledSessions: number
  adherenceRate: number
  averagePlannedMinutes: number
  averageActualMinutes: number
  byStatus: ReportsAnalyticsBreakdownItem[]
}

export interface ReportsAnalyticsLoginHeatmapCell {
  dayKey: string
  dayIndex: number
  hour: number
  hourLabel: string
  value: number
  percentage: number
}

export interface ReportsAnalyticsConnectionCalendarCell {
  date: string
  dayKey: string
  dayIndex: number
  weekIndex: number
  monthKey: string
  monthLabel: string
  value: number
  level: 0 | 1 | 2 | 3 | 4
}

export interface ReportsAnalyticsSegmentRow {
  key: string
  label: string
  users: number
  averageProgress: number
  completionRate: number
  averageCompletionDays: number
  sofliaAdoptionRate: number
  notesAdoptionRate: number
  quizAverageScore: number
  qualityScore: number
}

export interface ReportsAnalyticsSegments {
  ageBands: ReportsAnalyticsSegmentRow[]
  gender: ReportsAnalyticsSegmentRow[]
  jobTitles: ReportsAnalyticsSegmentRow[]
  roles: ReportsAnalyticsSegmentRow[]
}

export type ReportsAnalyticsHierarchyType = 'region' | 'zone' | 'team'

export interface ReportsAnalyticsHierarchyRankingRow {
  id: string
  type: ReportsAnalyticsHierarchyType
  name: string
  regionId?: string
  regionName?: string
  zoneId?: string
  zoneName?: string
  users: number
  averageProgress: number
  completionRate: number
  averageCompletionDays: number
  sofliaAdoptionRate: number
  notesAdoptionRate: number
  qualityScore: number
  overdueAssignments: number
  rankScore: number
}

export interface ReportsAnalyticsUserRankingRow {
  userId: string
  displayName: string
  email: string
  jobTitle: string
  regionName: string
  zoneName: string
  teamName: string
  averageProgress: number
  completionRate: number
  averageCompletionDays: number
  sofliaConversations: number
  notesCreated: number
  quizAverageScore: number
  qualityScore: number
  overdueAssignments: number
  rankScore: number
}

export interface ReportsAnalyticsRankings {
  regions: ReportsAnalyticsHierarchyRankingRow[]
  zones: ReportsAnalyticsHierarchyRankingRow[]
  teams: ReportsAnalyticsHierarchyRankingRow[]
  users: ReportsAnalyticsUserRankingRow[]
}

export interface ReportsAnalyticsDataQuality {
  usersWithCompleteDemographics: number
  usersMissingDemographics: number
  demographicsCompletionRate: number
  missingFields: ReportsAnalyticsBreakdownItem[]
}

export interface ReportsAnalyticsFilterOptions {
  courses: Array<{ value: string; label: string }>
  genders: Array<{ value: string; label: string }>
  ageBands: Array<{ value: string; label: string }>
  jobTitles: Array<{ value: string; label: string }>
  roles: Array<{ value: string; label: string }>
  statuses: Array<{ value: string; label: string }>
  regions: Array<{ value: string; label: string }>
  zones: Array<{ value: string; label: string; regionId?: string }>
  teams: Array<{ value: string; label: string; zoneId?: string; regionId?: string }>
}

export interface ReportsAnalyticsResponse {
  success: true
  generatedAt: string
  period: {
    from: string
    to: string
  }
  filters: ReportsAnalyticsFilters
  overview: ReportsAnalyticsOverview
  demographics: ReportsAnalyticsDemographics
  learning: ReportsAnalyticsLearning
  courses: ReportsAnalyticsCourseRow[]
  soflia: ReportsAnalyticsSoflia
  activities: ReportsAnalyticsActivities
  quality: ReportsAnalyticsQuality
  notes: ReportsAnalyticsNotes
  planner: ReportsAnalyticsPlanner
  loginHeatmap: ReportsAnalyticsLoginHeatmapCell[]
  connectionCalendar: ReportsAnalyticsConnectionCalendarCell[]
  segments: ReportsAnalyticsSegments
  rankings: ReportsAnalyticsRankings
  dataQuality: ReportsAnalyticsDataQuality
  filterOptions: ReportsAnalyticsFilterOptions
}

export interface ReportsAnalyticsUserDetailRow {
  userId: string
  displayName: string
  email: string
  status: string
  role: string
  jobTitle: string
  gender: string
  dateOfBirth: string
  age: number | null
  ageBand: string
  lastConnectionAt: string | null
  regionId: string
  regionName: string
  zoneId: string
  zoneName: string
  teamId: string
  teamName: string
  coursesAssigned: number
  coursesCompleted: number
  averageCompletionDays: number
  averageProgress: number
  overdueAssignments: number
  completedLessons: number
  timeSpentMinutes: number
  sofliaConversations: number
  sofliaMessages: number
  notesCreated: number
  activitiesCompleted: number
  activityAttempts: number
  quizAttempts: number
  quizAverageScore: number
  plannedSessions: number
  completedSessions: number
  missedSessions: number
  plannerAdherenceRate: number
  lastActivityAt: string | null
  qualityScore: number
}

export interface ReportsAnalyticsDataset extends ReportsAnalyticsResponse {
  userDetails: ReportsAnalyticsUserDetailRow[]
  aiSamples: ReportsAnalyticsAiSample[]
}

export type ReportsAnalyticsAiSampleSource =
  | 'soflia_message'
  | 'activity_response'
  | 'quiz_response'
  | 'note'

export interface ReportsAnalyticsAiSample {
  source: ReportsAnalyticsAiSampleSource
  anonymousUserId: string
  courseId?: string
  courseTitle?: string
  segment?: {
    ageBand: string
    gender: string
    jobTitle: string
    regionName: string
    zoneName: string
    teamName: string
  }
  text: string
  signals: Record<string, string | number | boolean | null>
}

export interface ReportsAnalyticsAiInsightSection {
  title: string
  points: string[]
}

export interface ReportsAnalyticsAiInsightMetric {
  label: string
  value: string
  detail: string
}

export interface ReportsAnalyticsAiInsights {
  generatedAt: string
  model: string
  summary: string
  executiveMetrics?: ReportsAnalyticsAiInsightMetric[]
  findings: ReportsAnalyticsAiInsightSection[]
  risks: string[]
  recommendations: string[]
  actionPlan?: ReportsAnalyticsAiInsightSection[]
}

export interface ReportsAnalyticsInsightsResponse {
  success: true
  insights: ReportsAnalyticsAiInsights
}
