export type SubscriptionPlan = 'team' | 'business' | 'enterprise'

export type FeatureKey =
  | 'panel_admin'
  | 'course_messaging'
  | 'custom_groups'
  | 'advanced_groups'
  | 'corporate_branding'
  | 'basic_reports'
  | 'advanced_analytics'
  | 'skills_info'
  | 'course_analysis'
  | 'custom_dashboard'
  | 'data_export'
  | 'full_catalog'
  | 'unlimited_certifications'
  | 'custom_certificates'
  | 'mobile_app'
  | 'offline_learning'
  | 'live_courses'
  | 'automatic_notifications'
  | 'smart_reminders'
  | 'external_integrations'
  | 'enterprise_sso'
  | 'calendar_integration'
  | 'data_api'
  | 'email_support'
  | 'priority_support'
  | 'dedicated_247_support'
  | 'customer_success_manager'
  | 'custom_onboarding'
  | 'strategic_consulting'
  | 'notification_email'
  | 'notification_push'
  | 'notification_sms'
  | 'notification_whatsapp'

export type FeatureAccess = Record<SubscriptionPlan, boolean>
