'use client'

import { useEffect, useRef, useState } from 'react'
import { AnimatePresence } from 'framer-motion'
import { BookOpen, FileText, Sparkles } from 'lucide-react'
import { useTranslation } from 'react-i18next'

import { cn } from '@/utils/cn'
import type { NotebookFlatNote } from '../hooks/useNotebookTree'
import type { NotebookNoteDetail } from '../types'
import { NoteHoverPreview } from './NoteHoverPreview'
import { GenerationStatusBadge } from './GenerationStatusBadge'

interface NotebookNoteCardProps {
  item: NotebookFlatNote
  preview: NotebookNoteDetail | undefined
  isPreviewLoading: boolean
  onOpen: (noteId: string) => void
  onRequestPreview: (noteId: string) => void
}

const HOVER_DELAY_MS = 280

function formatDate(value: string, locale: string): string {
  if (!value) return ''
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return ''
  return date.toLocaleDateString(locale, {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  })
}

export function NotebookNoteCard({
  item,
  preview,
  isPreviewLoading,
  onOpen,
  onRequestPreview,
}: NotebookNoteCardProps) {
  const { t, i18n } = useTranslation('notebook')
  const [showPreview, setShowPreview] = useState(false)
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => {
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current)
    }
  }, [])

  const handleEnter = () => {
    if (timerRef.current) clearTimeout(timerRef.current)
    timerRef.current = setTimeout(() => {
      onRequestPreview(item.note.noteId)
      setShowPreview(true)
    }, HOVER_DELAY_MS)
  }

  const handleLeave = () => {
    if (timerRef.current) clearTimeout(timerRef.current)
    setShowPreview(false)
  }

  const isCompendium = item.note.source === 'course_compendium'
  const isAi = item.note.isAutoGenerated || item.note.source !== 'manual'
  const generationStatus = item.note.generationState?.status ??
    (item.note.source === 'lesson_auto_note' || isCompendium ? 'ready' : null)

  return (
    <div
      className="relative"
      onMouseEnter={handleEnter}
      onMouseLeave={handleLeave}
    >
      <button
        type="button"
        onClick={() => onOpen(item.note.noteId)}
        className="flex h-full w-full flex-col gap-3 rounded-xl border border-gray-200 bg-white p-4 text-left shadow-sm transition-all hover:-translate-y-0.5 hover:border-[var(--color-accent)]/40 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)]/40 dark:border-white/10 dark:bg-white/[0.03] dark:hover:border-[var(--color-accent)]/40"
      >
        <div className="flex items-start justify-between gap-2">
          <h3 className="line-clamp-2 flex-1 text-sm font-semibold text-gray-900 dark:text-white">
            {item.note.title}
          </h3>
          {isAi && (
            <span
              title={t(`source.${item.note.source}`)}
              className="flex shrink-0 items-center gap-1 rounded-full bg-[var(--color-accent)]/15 px-2 py-0.5 text-[10px] font-semibold text-[var(--color-primary)] dark:text-[var(--color-accent)]"
            >
              <Sparkles className="h-3 w-3" />
              {t(`source.${item.note.source}`)}
            </span>
          )}
        </div>

        <div className="flex flex-col gap-1 text-xs text-gray-500 dark:text-gray-400">
          <span className="flex items-center gap-1.5">
            <BookOpen className="h-3.5 w-3.5 shrink-0" />
            <span className="truncate">{item.courseTitle}</span>
          </span>
          <span className="flex items-center gap-1.5">
            <FileText className="h-3.5 w-3.5 shrink-0" />
            <span className="truncate">
              {isCompendium ? t('compendium.label') : item.lessonTitle}
            </span>
          </span>
        </div>

        {item.note.tags.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {item.note.tags.slice(0, 3).map((tag) => (
              <span
                key={tag}
                className="rounded-full bg-gray-100 px-2 py-0.5 text-[10px] font-medium text-gray-600 dark:bg-white/10 dark:text-gray-300"
              >
                {tag}
              </span>
            ))}
            {item.note.tags.length > 3 && (
              <span className="text-[10px] text-gray-400">
                +{item.note.tags.length - 3}
              </span>
            )}
          </div>
        )}

        {generationStatus && (
          <GenerationStatusBadge status={generationStatus} className="w-fit" />
        )}

        <p className="mt-auto text-[11px] text-gray-400">
          {t('card.updatedAt', {
            date: formatDate(item.note.updatedAt, i18n.language),
          })}
        </p>
      </button>

      <AnimatePresence>
        {showPreview && (
          <NoteHoverPreview
            title={item.note.title}
            content={preview?.content}
            isLoading={isPreviewLoading || preview === undefined}
            source={preview?.source}
          />
        )}
      </AnimatePresence>
    </div>
  )
}
