'use client'

import { useEffect, useRef, useState } from 'react'
import { AnimatePresence } from 'framer-motion'
import { BookOpen, FileText, Sparkles } from 'lucide-react'
import { useTranslation } from 'react-i18next'

import type { NotebookFlatNote } from '../hooks/useNotebookTree'
import type { NotebookNoteDetail } from '../types'
import { NoteHoverPreview } from './NoteHoverPreview'
import { GenerationStatusBadge } from './GenerationStatusBadge'
import styles from './NotebookExperience.module.css'

interface NotebookNoteCardProps {
  item: NotebookFlatNote
  preview: NotebookNoteDetail | undefined
  isPreviewLoading: boolean
  onOpen: (noteId: string) => void
  onRequestPreview: (noteId: string) => void
}

const HOVER_DELAY_MS = 280

function formatDate(value: string, locale: string): string {
  if (!value) return ''
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return ''
  return date.toLocaleDateString(locale, {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  })
}

export function NotebookNoteCard({
  item,
  preview,
  isPreviewLoading,
  onOpen,
  onRequestPreview,
}: NotebookNoteCardProps) {
  const { t, i18n } = useTranslation('notebook')
  const [showPreview, setShowPreview] = useState(false)
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => {
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current)
    }
  }, [])

  const handleEnter = () => {
    if (timerRef.current) clearTimeout(timerRef.current)
    timerRef.current = setTimeout(() => {
      onRequestPreview(item.note.noteId)
      setShowPreview(true)
    }, HOVER_DELAY_MS)
  }

  const handleLeave = () => {
    if (timerRef.current) clearTimeout(timerRef.current)
    setShowPreview(false)
  }

  const isCompendium = item.note.source === 'course_compendium'
  const isAi = item.note.isAutoGenerated || item.note.source !== 'manual'
  const generationStatus = item.note.generationState?.status ??
    (item.note.source === 'lesson_auto_note' || isCompendium ? 'ready' : null)

  return (
    <div
      className={styles.noteWrapper}
      onMouseEnter={handleEnter}
      onMouseLeave={handleLeave}
    >
      <button
        type="button"
        onClick={() => onOpen(item.note.noteId)}
        className={styles.noteCard}
      >
        <div className={styles.cardTop}>
          <h3 className={styles.noteTitle}>
            {item.note.title}
          </h3>
          {isAi && (
            <span
              title={t(`source.${item.note.source}`)}
              className={styles.aiBadge}
            >
              <Sparkles className="h-3 w-3" />
              {t(`source.${item.note.source}`)}
            </span>
          )}
        </div>

        <div className={styles.cardPath}>
          <span className={styles.pathItem}>
            <BookOpen className="h-3.5 w-3.5 shrink-0" />
            <span className={styles.pathText}>{item.courseTitle}</span>
          </span>
          <span className={styles.pathItem}>
            <FileText className="h-3.5 w-3.5 shrink-0" />
            <span className={styles.pathText}>
              {isCompendium ? t('compendium.label') : item.lessonTitle}
            </span>
          </span>
        </div>

        {item.note.tags.length > 0 && (
          <div className={styles.tagList}>
            {item.note.tags.slice(0, 3).map((tag) => (
              <span
                key={tag}
                className={styles.tag}
              >
                {tag}
              </span>
            ))}
            {item.note.tags.length > 3 && (
              <span className={styles.tagMore}>
                +{item.note.tags.length - 3}
              </span>
            )}
          </div>
        )}

        {generationStatus && (
          <GenerationStatusBadge status={generationStatus} className="w-fit" />
        )}

        <p className={styles.updated}>
          {t('card.updatedAt', {
            date: formatDate(item.note.updatedAt, i18n.language),
          })}
        </p>
      </button>

      <AnimatePresence>
        {showPreview && (
          <NoteHoverPreview
            title={item.note.title}
            content={preview?.content}
            isLoading={isPreviewLoading || preview === undefined}
            source={preview?.source}
          />
        )}
      </AnimatePresence>
    </div>
  )
}
