'use client'

import { useTranslation } from 'react-i18next'
import {
  Check,
  CircleCheck,
  ListTodo,
  Loader2,
  RotateCcw,
  Sparkles,
  X,
} from 'lucide-react'

import { useBusinessPanelTheme } from '@/features/business-panel/hooks/useBusinessPanelTheme'
import { useNoteEnrichment } from '../hooks/useNoteEnrichment'
import type { NotebookDerivedTask } from '../types'
import styles from './NotebookEditor.module.css'

interface NoteEnrichmentPanelProps {
  orgSlug: string
  noteId: string
  onError: (message: string) => void
}

/**
 * Side-panel card with the AI enrichment of a note: summary, key concepts and
 * derived tasks. AI-suggested tasks require explicit confirmation; everything
 * shown here is clearly labeled as generated by SofLIA.
 */
export function NoteEnrichmentPanel({
  orgSlug,
  noteId,
  onError,
}: NoteEnrichmentPanelProps) {
  const { t } = useTranslation('notebook')
  const theme = useBusinessPanelTheme()
  const { state, isLoading, isRetrying, setTaskStatus, retryEnrichment } =
    useNoteEnrichment(orgSlug, noteId)

  const handleTaskStatus = async (
    taskId: string,
    status: 'open' | 'done' | 'dismissed',
  ) => {
    const ok = await setTaskStatus(taskId, status)
    if (!ok) onError(t('enrichment.taskActionError'))
  }

  const handleRetry = async () => {
    const result = await retryEnrichment()
    if (!result.ok) onError(result.error ?? t('enrichment.retryError'))
  }

  const isProcessing =
    state?.jobStatus === 'pending' || state?.jobStatus === 'processing'
  const hasFailed = state?.jobStatus === 'failed'
  const enrichment = state?.enrichment ?? null
  const visibleTasks = (state?.tasks ?? []).filter(
    (task) => task.status !== 'dismissed',
  )
  // El análisis puede terminar sin resultado por varias vías (reintentos
  // agotados, o el trabajo se descartó porque el apunte cambió o quedó
  // bloqueado). En todos esos casos la nota se quedaba sin forma de volver a
  // analizarse, así que la acción se ofrece siempre que no haya nada en curso.
  const canRequestAnalysis = Boolean(state) && !isProcessing && !enrichment

  return (
    <section className={styles.enrichmentCard}>
      <div className={styles.enrichmentHeader}>
        <span className={styles.enrichmentIcon}>
          <Sparkles />
        </span>
        <p
          className={styles.enrichmentTitle}
          style={{ color: theme.subtextColor }}
        >
          {t('enrichment.title')}
        </p>
        {isProcessing && (
          <Loader2
            className="h-3.5 w-3.5 animate-spin"
            style={{ color: theme.actionColor }}
          />
        )}
      </div>

      {isLoading && !state ? (
        <p className={styles.enrichmentEmpty} style={{ color: theme.mutedTextColor }}>
          {t('enrichment.loading')}
        </p>
      ) : !enrichment && isProcessing ? (
        <p className={styles.enrichmentEmpty} style={{ color: theme.mutedTextColor }}>
          {t('enrichment.processing')}
        </p>
      ) : !enrichment ? (
        <div className={styles.enrichmentEmptyState}>
          <p style={{ color: theme.mutedTextColor }}>
            {hasFailed ? t('enrichment.failed') : t('enrichment.empty')}
          </p>
          {canRequestAnalysis && (
            <button
              type="button"
              onClick={() => void handleRetry()}
              disabled={isRetrying}
              className={styles.enrichmentRetry}
              style={{ borderColor: theme.borderColor, color: theme.actionColor }}
            >
              {isRetrying ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <RotateCcw className="h-3.5 w-3.5" />
              )}
              {hasFailed ? t('enrichment.retry') : t('enrichment.analyzeNow')}
            </button>
          )}
        </div>
      ) : (
        <div className={styles.enrichmentContent}>
          <span
            className={styles.knowledgeBadge}
            style={{
              backgroundColor: `${theme.actionColor}1a`,
              color: theme.actionColor,
            }}
          >
            {t(`enrichment.knowledgeType.${enrichment.knowledgeType}`)}
          </span>

          {enrichment.summary && (
            <div className={styles.enrichmentSection}>
              <p
                className={styles.enrichmentSectionLabel}
                style={{ color: theme.mutedTextColor }}
              >
                {t('enrichment.summaryLabel')}
              </p>
              <p className={styles.enrichmentSummary} style={{ color: theme.subtextColor }}>
                {enrichment.summary}
              </p>
            </div>
          )}

          {enrichment.keyConcepts.length > 0 && (
            <div className={styles.enrichmentSection}>
              <p
                className={styles.enrichmentSectionLabel}
                style={{ color: theme.mutedTextColor }}
              >
                {t('enrichment.conceptsLabel')}
              </p>
              <div className={styles.conceptList}>
                {enrichment.keyConcepts.map((concept) => (
                  <span
                    key={concept}
                    className={styles.conceptChip}
                    style={{ borderColor: theme.borderColor, color: theme.subtextColor }}
                  >
                    {concept}
                  </span>
                ))}
              </div>
            </div>
          )}

          <p className={styles.aiDisclaimer} style={{ color: theme.mutedTextColor }}>
            {t('enrichment.aiDisclaimer')}
          </p>
        </div>
      )}

      {visibleTasks.length > 0 && (
        <div className={styles.enrichmentTasks} style={{ borderColor: theme.borderColor }}>
          <p
            className={styles.enrichmentTasksTitle}
            style={{ color: theme.mutedTextColor }}
          >
            <ListTodo className="h-3.5 w-3.5" />
            {t('enrichment.tasksLabel')}
          </p>
          <ul className={styles.taskList}>
            {visibleTasks.map((task) => (
              <TaskRow
                key={task.taskId}
                task={task}
                onStatus={handleTaskStatus}
                actionColor={theme.actionColor}
                subtextColor={theme.subtextColor}
                mutedTextColor={theme.mutedTextColor}
              />
            ))}
          </ul>
        </div>
      )}
    </section>
  )
}

function TaskRow({
  task,
  onStatus,
  actionColor,
  subtextColor,
  mutedTextColor,
}: {
  task: NotebookDerivedTask
  onStatus: (taskId: string, status: 'open' | 'done' | 'dismissed') => Promise<void>
  actionColor: string
  subtextColor: string
  mutedTextColor: string
}) {
  const { t } = useTranslation('notebook')

  return (
    <li className={styles.taskRow}>
      <span
        className={`${styles.taskText} ${task.status === 'done' ? styles.taskTextDone : ''}`}
        style={{ color: task.status === 'done' ? mutedTextColor : subtextColor }}
      >
        {task.title}
        {task.status === 'suggested' && (
          <span className="ml-1.5 text-[10px] uppercase" style={{ color: mutedTextColor }}>
            {t('enrichment.suggestedBadge')}
          </span>
        )}
      </span>

      <span className={styles.taskActions}>
        {task.status === 'suggested' && (
          <>
            <button
              type="button"
              onClick={() => void onStatus(task.taskId, 'open')}
              title={t('enrichment.taskConfirm')}
              aria-label={t('enrichment.taskConfirm')}
              className={styles.taskAction}
              style={{ color: actionColor }}
            >
              <Check className="h-4 w-4" />
            </button>
            <button
              type="button"
              onClick={() => void onStatus(task.taskId, 'dismissed')}
              title={t('enrichment.taskDismiss')}
              aria-label={t('enrichment.taskDismiss')}
              className={`${styles.taskAction} ${styles.taskActionDanger}`}
            >
              <X className="h-4 w-4" />
            </button>
          </>
        )}
        {task.status === 'open' && (
          <button
            type="button"
            onClick={() => void onStatus(task.taskId, 'done')}
            title={t('enrichment.taskComplete')}
            aria-label={t('enrichment.taskComplete')}
            className={styles.taskAction}
            style={{ color: actionColor }}
          >
            <CircleCheck className="h-4 w-4" />
          </button>
        )}
        {task.status === 'done' && (
          <button
            type="button"
            onClick={() => void onStatus(task.taskId, 'open')}
            title={t('enrichment.taskReopen')}
            aria-label={t('enrichment.taskReopen')}
            className={styles.taskAction}
            style={{ color: mutedTextColor }}
          >
            <RotateCcw className="h-4 w-4" />
          </button>
        )}
      </span>
    </li>
  )
}
