'use client'

import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import {
  Check,
  CircleCheck,
  ListTodo,
  Loader2,
  RotateCcw,
  Sparkles,
  X,
} from 'lucide-react'

import { useBusinessPanelTheme } from '@/features/business-panel/hooks/useBusinessPanelTheme'
import { useNoteEnrichment } from '../hooks/useNoteEnrichment'
import type { NotebookDerivedTask } from '../types'

interface NoteEnrichmentPanelProps {
  orgSlug: string
  noteId: string
  onTaskActionError: () => void
}

/**
 * Side-panel card with the AI enrichment of a note: summary, key concepts and
 * derived tasks. AI-suggested tasks require explicit confirmation; everything
 * shown here is clearly labeled as generated by SofLIA.
 */
export function NoteEnrichmentPanel({
  orgSlug,
  noteId,
  onTaskActionError,
}: NoteEnrichmentPanelProps) {
  const { t } = useTranslation('notebook')
  const theme = useBusinessPanelTheme()
  const { state, isLoading, setTaskStatus, retryEnrichment } = useNoteEnrichment(
    orgSlug,
    noteId,
  )
  const [isRetrying, setIsRetrying] = useState(false)

  const handleTaskStatus = async (
    taskId: string,
    status: 'open' | 'done' | 'dismissed',
  ) => {
    const ok = await setTaskStatus(taskId, status)
    if (!ok) onTaskActionError()
  }

  const handleRetry = async () => {
    setIsRetrying(true)
    try {
      await retryEnrichment()
    } catch {
      onTaskActionError()
    } finally {
      setIsRetrying(false)
    }
  }

  const isProcessing =
    state?.jobStatus === 'pending' || state?.jobStatus === 'processing'
  const enrichment = state?.enrichment ?? null
  const visibleTasks = (state?.tasks ?? []).filter(
    (task) => task.status !== 'dismissed',
  )

  return (
    <div
      className="rounded-2xl border p-4 shadow-sm"
      style={{ backgroundColor: theme.cardBg, borderColor: theme.borderColor }}
    >
      <div className="mb-3 flex items-center justify-between">
        <p
          className="inline-flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide"
          style={{ color: theme.subtextColor }}
        >
          <Sparkles className="h-3.5 w-3.5" style={{ color: theme.actionColor }} />
          {t('enrichment.title')}
        </p>
        {isProcessing && (
          <Loader2
            className="h-3.5 w-3.5 animate-spin"
            style={{ color: theme.actionColor }}
          />
        )}
      </div>

      {isLoading && !state ? (
        <p className="text-xs" style={{ color: theme.mutedTextColor }}>
          {t('enrichment.loading')}
        </p>
      ) : !enrichment && isProcessing ? (
        <p className="text-xs" style={{ color: theme.mutedTextColor }}>
          {t('enrichment.processing')}
        </p>
      ) : !enrichment ? (
        <div className="flex flex-col gap-2">
          <p className="text-xs" style={{ color: theme.mutedTextColor }}>
            {state?.jobStatus === 'failed'
              ? t('enrichment.failed')
              : t('enrichment.empty')}
          </p>
          {state?.jobStatus === 'failed' && (
            <button
              type="button"
              onClick={() => void handleRetry()}
              disabled={isRetrying}
              className="inline-flex w-fit items-center gap-1.5 rounded-lg border px-2.5 py-1.5 text-xs font-semibold transition-opacity hover:opacity-80 disabled:opacity-50"
              style={{ borderColor: theme.borderColor, color: theme.actionColor }}
            >
              {isRetrying ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <RotateCcw className="h-3.5 w-3.5" />
              )}
              {t('enrichment.retry')}
            </button>
          )}
        </div>
      ) : (
        <div className="flex flex-col gap-4">
          <span
            className="inline-flex w-fit items-center rounded-full px-2.5 py-0.5 text-[11px] font-semibold"
            style={{
              backgroundColor: `${theme.actionColor}1a`,
              color: theme.actionColor,
            }}
          >
            {t(`enrichment.knowledgeType.${enrichment.knowledgeType}`)}
          </span>

          {enrichment.summary && (
            <div>
              <p
                className="mb-1 text-[11px] font-semibold uppercase tracking-wide"
                style={{ color: theme.mutedTextColor }}
              >
                {t('enrichment.summaryLabel')}
              </p>
              <p className="text-sm leading-relaxed" style={{ color: theme.subtextColor }}>
                {enrichment.summary}
              </p>
            </div>
          )}

          {enrichment.keyConcepts.length > 0 && (
            <div>
              <p
                className="mb-1.5 text-[11px] font-semibold uppercase tracking-wide"
                style={{ color: theme.mutedTextColor }}
              >
                {t('enrichment.conceptsLabel')}
              </p>
              <div className="flex flex-wrap gap-1.5">
                {enrichment.keyConcepts.map((concept) => (
                  <span
                    key={concept}
                    className="rounded-full border px-2 py-0.5 text-xs"
                    style={{ borderColor: theme.borderColor, color: theme.subtextColor }}
                  >
                    {concept}
                  </span>
                ))}
              </div>
            </div>
          )}

          <p className="text-[11px]" style={{ color: theme.mutedTextColor }}>
            {t('enrichment.aiDisclaimer')}
          </p>
        </div>
      )}

      {visibleTasks.length > 0 && (
        <div className="mt-4 border-t pt-3" style={{ borderColor: theme.borderColor }}>
          <p
            className="mb-2 inline-flex items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wide"
            style={{ color: theme.mutedTextColor }}
          >
            <ListTodo className="h-3.5 w-3.5" />
            {t('enrichment.tasksLabel')}
          </p>
          <ul className="flex flex-col gap-2">
            {visibleTasks.map((task) => (
              <TaskRow
                key={task.taskId}
                task={task}
                onStatus={handleTaskStatus}
                actionColor={theme.actionColor}
                subtextColor={theme.subtextColor}
                mutedTextColor={theme.mutedTextColor}
              />
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}

function TaskRow({
  task,
  onStatus,
  actionColor,
  subtextColor,
  mutedTextColor,
}: {
  task: NotebookDerivedTask
  onStatus: (taskId: string, status: 'open' | 'done' | 'dismissed') => Promise<void>
  actionColor: string
  subtextColor: string
  mutedTextColor: string
}) {
  const { t } = useTranslation('notebook')

  return (
    <li className="flex items-start gap-2">
      <span
        className={`flex-1 text-sm leading-snug ${task.status === 'done' ? 'line-through' : ''}`}
        style={{ color: task.status === 'done' ? mutedTextColor : subtextColor }}
      >
        {task.title}
        {task.status === 'suggested' && (
          <span className="ml-1.5 text-[10px] uppercase" style={{ color: mutedTextColor }}>
            {t('enrichment.suggestedBadge')}
          </span>
        )}
      </span>

      <span className="flex shrink-0 items-center gap-1">
        {task.status === 'suggested' && (
          <>
            <button
              type="button"
              onClick={() => void onStatus(task.taskId, 'open')}
              title={t('enrichment.taskConfirm')}
              aria-label={t('enrichment.taskConfirm')}
              className="rounded-md p-1 transition-opacity hover:opacity-70"
              style={{ color: actionColor }}
            >
              <Check className="h-4 w-4" />
            </button>
            <button
              type="button"
              onClick={() => void onStatus(task.taskId, 'dismissed')}
              title={t('enrichment.taskDismiss')}
              aria-label={t('enrichment.taskDismiss')}
              className="rounded-md p-1 text-red-500 transition-opacity hover:opacity-70"
            >
              <X className="h-4 w-4" />
            </button>
          </>
        )}
        {task.status === 'open' && (
          <button
            type="button"
            onClick={() => void onStatus(task.taskId, 'done')}
            title={t('enrichment.taskComplete')}
            aria-label={t('enrichment.taskComplete')}
            className="rounded-md p-1 transition-opacity hover:opacity-70"
            style={{ color: actionColor }}
          >
            <CircleCheck className="h-4 w-4" />
          </button>
        )}
        {task.status === 'done' && (
          <button
            type="button"
            onClick={() => void onStatus(task.taskId, 'open')}
            title={t('enrichment.taskReopen')}
            aria-label={t('enrichment.taskReopen')}
            className="rounded-md p-1 transition-opacity hover:opacity-70"
            style={{ color: mutedTextColor }}
          >
            <RotateCcw className="h-4 w-4" />
          </button>
        )}
      </span>
    </li>
  )
}
