
import type { ReportsAnalyticsDataset } from '../../../types/reports-analytics.types'
import { getMetricColumns } from './columns-basic'
import type { ExportCopy } from './export.types'
import { buildActivitiesRows, buildQualityRows } from './rows-activities'
import { withCategory } from './rows-segments'
import { toCsv } from './csv-shared'

export function buildSofliaCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv([
    { metric: copy.metrics.totalConversations, value: dataset.soflia.totalConversations, detail: '' },
    { metric: copy.metrics.totalMessages, value: dataset.soflia.totalMessages, detail: '' },
    { metric: copy.metrics.activeLearners, value: dataset.soflia.activeUsers, detail: '' },
    { metric: copy.metrics.averageMessagesPerConversation, value: dataset.soflia.averageMessagesPerConversation, detail: '' },
    { metric: copy.metrics.completedConversations, value: `${dataset.soflia.completionRate}%`, detail: '' },
    ...withCategory('Contexto SofLIA', dataset.soflia.contextBreakdown, copy).map((row) => ({
      metric: row.label,
      value: row.value,
      detail: `${row.percentage}%`,
    })),
  ], getMetricColumns(copy))
}

export function buildActivitiesCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv(buildActivitiesRows(dataset, copy), getMetricColumns(copy))
}

export function buildNotesCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv([
    { metric: copy.metrics.totalNotes, value: dataset.notes.totalNotes, detail: '' },
    { metric: copy.metrics.usersWithNotes, value: dataset.notes.usersWithNotes, detail: `${dataset.notes.adoptionRate}%` },
    { metric: copy.metrics.autoGenerated, value: dataset.notes.autoGenerated, detail: '' },
    { metric: copy.metrics.manual, value: dataset.notes.manual, detail: '' },
    ...withCategory('Curso', dataset.notes.byCourse, copy).map((row) => ({
      metric: row.label,
      value: row.value,
      detail: `${row.percentage}%`,
    })),
  ], getMetricColumns(copy))
}

export function buildQualityCsv(dataset: ReportsAnalyticsDataset, copy: ExportCopy): string {
  return toCsv(buildQualityRows(dataset, copy), getMetricColumns(copy))
}
