import { describe, expect, it } from 'vitest'

import {
  buildNotebookNotesPage,
  decodeNotebookCursor,
} from '../notebook-pagination.service'
import type { NotebookManualNote } from '../../types'

function manualNote(id: string, updatedAt: string): NotebookManualNote {
  return {
    kind: 'manual_note',
    noteId: id,
    title: `Note ${id}`,
    contentPreview: '',
    content: '',
    tags: [],
    sourceType: 'manual',
    isAutoGenerated: false,
    lessonId: 'lesson-1',
    lessonTitle: 'Lesson',
    moduleTitle: 'Module',
    courseId: 'course-1',
    courseTitle: 'Course',
    organizationId: 'org-1',
    createdAt: updatedAt,
    updatedAt,
  }
}

describe('notebook.server.service pagination helpers', () => {
  it('sorts notebook notes deterministically by updatedAt and identity', () => {
    const notes = [
      manualNote('b', '2026-05-20T10:00:00.000Z'),
      manualNote('c', '2026-05-20T11:00:00.000Z'),
      manualNote('a', '2026-05-20T10:00:00.000Z'),
    ]

    const page = buildNotebookNotesPage(notes, 10)

    expect(page.items.map((item) => item.title)).toEqual([
      'Note c',
      'Note b',
      'Note a',
    ])
  })

  it('returns an opaque cursor that resumes after the last item on the page', () => {
    const notes = [
      manualNote('n-1', '2026-05-20T12:00:00.000Z'),
      manualNote('n-2', '2026-05-20T11:00:00.000Z'),
      manualNote('n-3', '2026-05-20T10:00:00.000Z'),
    ]

    const firstPage = buildNotebookNotesPage(notes, 2)
    const cursor = decodeNotebookCursor(firstPage.nextCursor || undefined)

    expect(firstPage.items.map((item) => item.title)).toEqual(['Note n-1', 'Note n-2'])
    expect(cursor?.id).toBe('n-2')
    expect(firstPage.nextCursor).not.toBeNull()
  })
})
