export { isDangerousKey } from './safe-merge/guards'
export { safeAssign, safeMerge } from './safe-merge/merge'
export { createSafeObject, sanitizeObject } from './safe-merge/sanitize'
export { isObjectSafe, validateObject } from './safe-merge/validation'
export type { SafeMergeRecord } from './safe-merge/types'
