import type { DeleteTarget } from './types'

export const IGNORABLE_DELETE_ERROR_CODES = new Set(['42P01', 'PGRST116'])

export const BUSINESS_USER_SIMPLE_DELETE_BATCHES: DeleteTarget[][] = [
  [
    { tableName: 'lia_user_feedback' },
    { tableName: 'lia_activity_completions' },
    { tableName: 'lia_conversations' },
    { tableName: 'user_quiz_submissions' },
    { tableName: 'lesson_tracking' },
    { tableName: 'user_lesson_progress' },
    { tableName: 'daily_progress' },
    { tableName: 'user_lesson_notes' },
    { tableName: 'notification_email_queue' },
    { tableName: 'notification_push_subscriptions' },
    { tableName: 'notification_stats' },
    { tableName: 'user_notification_preferences' },
    { tableName: 'user_notifications' },
    { tableName: 'user_calendar_events' },
    { tableName: 'calendar_subscription_tokens' },
    { tableName: 'calendar_integrations' },
    { tableName: 'audit_logs' },
    { tableName: 'audit_logs', column: 'admin_user_id' },
    { tableName: 'user_activity_log' },
    { tableName: 'ai_moderation_logs' },
    { tableName: 'user_favorites' },
    { tableName: 'notes' },
    { tableName: 'user_warnings' },
    { tableName: 'user_tour_progress' },
    { tableName: 'reportes_problemas' },
    { tableName: 'reportes_problemas', column: 'admin_asignado' },
    { tableName: 'admin_dashboard_layouts' },
    { tableName: 'admin_dashboard_preferences' },
    { tableName: 'study_preferences' },
    { tableName: 'user_streaks' },
    { tableName: 'oauth_accounts' },
    { tableName: 'password_reset_tokens' },
    { tableName: 'refresh_tokens' },
    { tableName: 'user_session' },
  ],
  [
    { tableName: 'course_question_reactions' },
    { tableName: 'course_question_responses' },
    { tableName: 'course_questions' },
    { tableName: 'course_reviews' },
    { tableName: 'lesson_feedback' },
    { tableName: 'community_post_reactions' },
    { tableName: 'community_comment_reactions' },
    { tableName: 'community_comments' },
    { tableName: 'community_posts' },
    { tableName: 'study_sessions' },
    { tableName: 'calendar_sync_history' },
    { tableName: 'study_plans' },
    { tableName: 'organization_course_purchases', column: 'purchased_by' },
    { tableName: 'transactions' },
    { tableName: 'subscriptions' },
    { tableName: 'payment_methods' },
    { tableName: 'user_course_enrollments' },
    { tableName: 'organization_course_assignments' },
    { tableName: 'organization_course_assignments', column: 'assigned_by' },
    { tableName: 'scorm_packages', column: 'created_by' },
    { tableName: 'user_invitations', column: 'created_by' },
  ],
  [
    { tableName: 'work_team_feedback', column: 'from_user_id' },
    { tableName: 'work_team_feedback', column: 'to_user_id' },
    { tableName: 'work_team_messages', column: 'sender_id' },
    { tableName: 'work_team_objectives', column: 'created_by' },
    { tableName: 'work_team_course_assignments', column: 'assigned_by' },
    { tableName: 'work_team_members' },
    { tableName: 'organization_node_users' },
  ],
]

export function isIgnorableDeleteErrorCode(code: string | null | undefined) {
  return Boolean(code && IGNORABLE_DELETE_ERROR_CODES.has(code))
}
