/**
 * Tipos del panel forense de auditoría de usuario (super-admin).
 *
 * Toda marca de tiempo se transporta como ISO UTC (`*Utc`) — la zona es decisión de
 * presentación en el cliente. Un `ForensicEvent` es una entrada normalizada de la línea
 * de tiempo, proveniente de cualquier tabla de eventos (login, diálogo, quiz, lección,
 * inscripción, actividad, LIA).
 */

export type ForensicEventType =
  | 'login'
  | 'course_assigned'
  | 'learning_path_assigned'
  | 'course_enrolled'
  | 'lesson_started'
  | 'lesson_completed'
  | 'video_watched'
  | 'dialogue_started'
  | 'dialogue_evaluation'
  | 'dialogue_result'
  | 'dialogue_event'
  | 'quiz_attempt'
  | 'activity_submission'
  | 'note_created'
  | 'lia_conversation'
  | 'lia_message'
  | 'certificate_issued'
  | 'lesson_feedback'

/** Señal de alerta forense legible (posible trampa / anomalía). */
export interface ForensicFlag {
  /** Clave i18n del mensaje (bajo users.masterPanel.audit.flags.*). */
  key: string
  severity: 'info' | 'warning' | 'danger'
  /** Interpolaciones para el i18n (p.ej. { count: 3 }). */
  params?: Record<string, string | number>
}

/**
 * Agregados "maquillados" por sección: conteos y métricas en lenguaje humano para
 * que un auditor no técnico entienda de un vistazo qué hizo el usuario.
 */
export interface ForensicAggregates {
  access: {
    totalLogins: number
    distinctIps: number
    /** Lista de IPs distintas detectadas en TODAS las fuentes (login, actividad, LIA). */
    ipAddresses: string[]
    distinctDevices: number
    /**
     * Pares de sesiones desde IP distinta iniciadas casi al mismo tiempo — la ÚNICA
     * señal de acceso realmente sospechosa (posible cuenta compartida / dos dispositivos
     * a la vez). Muchos logins en horas distintas NO cuentan.
     */
    concurrentSessions: number
    firstLoginAtUtc: string | null
    lastLoginAtUtc: string | null
  }
  courses: {
    enrolled: number
    completed: number
    certificatesIssued: number
    lastCertificateAtUtc: string | null
  }
  lessons: {
    started: number
    completed: number
    videosWithProgress: number
    videosWatchedFull: number
    videosSpedUp: number
    videosBarelyWatched: number
    totalVideoMinutes: number
    maxPlaybackRate: number | null
  }
  dialogues: {
    /** Sesiones de diálogo abiertas (soflia_dialogue_sessions). */
    total: number
    completed: number
    abandoned: number
    passed: number
    averageScore: number | null
    /** Actividades de diálogo SofLIA DISPONIBLES en los cursos del usuario (denominador). */
    available: number
  }
  quizzes: {
    totalAttempts: number
    distinctQuizzes: number
    passed: number
    maxAttemptsOnSingleQuiz: number
  }
  activities: {
    submitted: number
    validated: number
  }
  notes: {
    total: number
    userWritten: number
    autoGenerated: number
  }
  lia: {
    conversations: number
    abandonedConversations: number
    totalMessages: number
  }
}

/** Ids de contenido de los que se deduce dónde ocurrió un evento o un bloqueo. */
export interface ForensicContentRefs {
  courseId?: string | null
  lessonId?: string | null
  activityId?: string | null
  learningPathId?: string | null
}

/**
 * Ubicación legible del evento dentro del contenido: sin curso y módulo, una lección
 * suelta no le dice nada al auditor. Se resuelve en el servidor (una pasada, sin N+1).
 */
export interface ForensicContentContext {
  courseTitle: string | null
  moduleTitle: string | null
  lessonTitle: string | null
  activityTitle: string | null
  learningPathTitle: string | null
}

export interface ForensicEvent {
  /** Id estable para React keys y drill-down (no necesariamente el PK de la fila). */
  id: string
  type: ForensicEventType
  /** Momento del evento en ISO UTC. */
  atUtc: string
  /** Título corto legible (ya resuelto, sin traducción). */
  title: string
  /** Detalle secundario opcional (score, estado, duración…). */
  detail?: string | null
  /** Curso · módulo · lección · actividad donde ocurrió (resuelto en el servidor). */
  context?: ForensicContentContext | null
  /** Puntaje 0-100 cuando aplica (quiz/diálogo). */
  score?: number | null
  /** Referencias para drill-down (sessionId de diálogo, lessonId, etc.). */
  refIds?: Record<string, string | null | undefined>
  /** Metadatos crudos adicionales (no PII sensible) para inspección. */
  meta?: Record<string, unknown>
}

/** Motor de intentos que puede dejar a un alumno fuera de una actividad. */
export type ForensicLockScope = 'quiz' | 'dialogue' | 'lia_activity'

/**
 * Estado de un tope de intentos:
 *  - `cooldown` — sin intentos ahora, se recuperan solos al expirar la ventana;
 *  - `locked`   — sin intentos y sin instante de recuperación calculable (intentos sin
 *                 marca de tiempo); es el caso degradado, no la norma;
 *  - `at_risk`  — le queda un único intento (aviso temprano para el auditor);
 *  - `cleared`  — hubo un bloqueo pero un desbloqueo administrativo lo levantó.
 */
export type ForensicLockStatus = 'locked' | 'cooldown' | 'at_risk' | 'cleared'

/** Desbloqueo administrativo aplicado a un tope de intentos. */
export interface ForensicUnlockGrant {
  unlockId: string
  effectiveFromUtc: string
  grantedByEmail: string | null
  reason: string | null
}

/**
 * Tope de intentos alcanzado (o a punto de alcanzarse) por el alumno en un punto
 * concreto del contenido. Es la respuesta a "¿por qué este usuario no avanza?".
 */
export interface ForensicAttemptLock {
  /** Id estable derivado del ámbito (scope + referencias), no un PK. */
  id: string
  scope: ForensicLockScope
  status: ForensicLockStatus
  /** Intentos que consumen cupo AHORA (dentro de la ventana de enfriamiento). */
  attemptsUsed: number
  /**
   * Intentos acumulados desde el último desbloqueo, hayan salido o no de la ventana.
   * Sin este dato un bloqueo de ayer sería invisible para quien audita hoy.
   */
  attemptsSinceUnlock: number
  maxAttempts: number
  /** El alumno ya superó la evaluación: el tope dejó de importar. */
  passed: boolean
  lastAttemptAtUtc: string | null
  /** Instante en que la ventana de enfriamiento devuelve intentos. */
  retryAvailableAtUtc: string | null
  context: ForensicContentContext
  /** Referencias necesarias para conceder el desbloqueo desde el panel. */
  target: {
    lessonId: string | null
    materialId: string | null
    activityId: string | null
    enrollmentId: string | null
  }
  /** Último desbloqueo administrativo aplicado a este ámbito. */
  unlock: ForensicUnlockGrant | null
}

export interface ForensicSession {
  id: string
  ipAddress: string | null
  userAgent: string | null
  deviceFingerprint: string | null
  createdAtUtc: string | null
  lastUsedAtUtc: string | null
  expiresAtUtc: string | null
  isRevoked: boolean
  revokedAtUtc: string | null
  revokedReason: string | null
}

export interface ForensicIdentity {
  id: string
  email: string | null
  role: string | null
  emailVerified: boolean | null
  /** Organización(es) a la(s) que pertenece el usuario (contexto de la auditoría). */
  organizationNames: string[]
  createdAtUtc: string | null
  /** `users.last_login_at` (solo se mueve al re-autenticar con credenciales). */
  lastLoginAtUtc: string | null
  /** `users.last_activity_at` (throttle de 15 min — puede ir por detrás). */
  lastActivityAtUtc: string | null
  isBanned: boolean | null
  bannedAtUtc: string | null
  banReason: string | null
}

export interface ForensicEventTypeCount {
  type: ForensicEventType
  count: number
}

export interface UserForensicSummary {
  identity: ForensicIdentity
  sessions: ForensicSession[]
  /**
   * Última actividad REAL derivada del MAX de todos los eventos — fuente de verdad,
   * a diferencia de `identity.lastActivityAtUtc` que está throttleado y no cubre
   * diálogos/quizzes. Null si no hay eventos.
   */
  derivedLastActivityAtUtc: string | null
  /** Primer evento registrado (MIN) — inicio de la huella del usuario. */
  firstActivityAtUtc: string | null
  /** Agregados humanizados por sección (conteos y métricas legibles). */
  aggregates: ForensicAggregates
  /** Señales de alerta detectadas (posible trampa / anomalías). */
  flags: ForensicFlag[]
  /**
   * Topes de intentos alcanzados: dónde quedó bloqueado el alumno dentro del curso y
   * si un super-admin ya le devolvió intentos.
   */
  locks: ForensicAttemptLock[]
  /** Notas del usuario (título + contenido) para la sección de notas. */
  notes: ForensicNote[]
  timeline: ForensicEvent[]
  eventTypeCounts: ForensicEventTypeCount[]
  totalEvents: number
  /** True si algún dominio alcanzó el tope de filas (los datos podrían truncarse). */
  truncated: boolean
}

/** Ítem con título + detalle para las secciones del dictamen. */
export interface ForensicAnalysisItem {
  title: string
  detail: string
  severity?: 'info' | 'warning' | 'danger'
}

export type ForensicRuling = 'cumple' | 'cumple_con_observaciones' | 'no_cumple'

/**
 * Dictamen pericial forense generado por SofLIA (Gemini) sobre la auditoría del usuario.
 * Estructura fija para renderizar el PDF sin datos sueltos.
 */
export interface ForensicAnalysis {
  generatedAtUtc: string
  model: string
  /** Resumen ejecutivo en lenguaje claro. */
  executiveSummary: string
  /** Análisis de la conducta y el patrón de uso. */
  behaviorAnalysis: string
  /** Hallazgos relevantes de la auditoría. */
  findings: ForensicAnalysisItem[]
  /** Riesgos y complicaciones detectados. */
  risks: ForensicAnalysisItem[]
  /** Indicios de mal uso / intento de trampa. */
  misuseIndicators: ForensicAnalysisItem[]
  /** Dictamen: cumple / no cumple + justificación. */
  verdict: {
    ruling: ForensicRuling
    rationale: string
    confidence: 'alta' | 'media' | 'baja'
  }
  recommendations: string[]
  /** True si se usó el análisis determinista de respaldo (Gemini no disponible). */
  fallbackUsed: boolean
}

/** Un mensaje del chat con el asistente LIA. */
export interface ForensicLiaMessage {
  id: string
  role: 'user' | 'assistant' | 'system'
  content: string
  sequence: number
  isOffTopic: boolean
  createdAtUtc: string | null
}

export interface ForensicLiaTranscript {
  conversationId: string
  contextType: string | null
  messages: ForensicLiaMessage[]
}

/** Nota del usuario (libreta / auto-nota de lección). */
export interface ForensicNote {
  id: string
  title: string
  content: string
  isAutoGenerated: boolean
  isUserEdited: boolean
  lessonId: string | null
  createdAtUtc: string | null
  updatedAtUtc: string | null
}

/** Un turno de la transcripción de un diálogo SofLIA. */
export interface ForensicDialogueTurn {
  id: string
  role: 'user' | 'assistant' | 'system'
  content: string
  turnNumber: number
  createdAtUtc: string | null
}

export interface ForensicDialogueEvaluation {
  id: string
  overallScore: number | null
  decision: string | null
  criteriaMet: string[]
  criteriaMissing: string[]
  feedbackForTutor: string | null
  createdAtUtc: string | null
}

export interface ForensicDialogueTranscript {
  sessionId: string
  state: string | null
  currentScore: number | null
  turnsCount: number | null
  hintsUsed: number | null
  attemptNumber: number | null
  activeSeconds: number | null
  startedAtUtc: string | null
  completedAtUtc: string | null
  turns: ForensicDialogueTurn[]
  evaluations: ForensicDialogueEvaluation[]
  result: {
    activityResult: string | null
    score: number | null
    studentFeedback: string | null
  } | null
}
