"use client";

import { useRouter } from "next/navigation";
import {
  BookOpen,
  Edit2,
  Eye,
  LockKeyhole,
  Sparkles,
  Trash2,
} from "lucide-react";
import { useTranslation } from "react-i18next";
import type { LearnNoteListItem } from "../types";
import styles from "../sidebar/CourseSidebar.module.css";
import { getNotePreviewText } from "./utils";

type NoteCardProps = {
  note: LearnNoteListItem;
  onEdit: (note: LearnNoteListItem) => void;
  onDelete: (noteId: string) => void;
  /** Abre el visor de solo lectura in-page para apuntes generados por SofLIA. */
  onView?: (note: LearnNoteListItem) => void;
  editLabel: string;
  deleteLabel: string;
  notebookHref?: string;
};

export function NoteCard({
  note,
  onEdit,
  onDelete,
  onView,
  editLabel,
  deleteLabel,
  notebookHref,
}: NoteCardProps) {
  const router = useRouter();
  const { t } = useTranslation("learn");
  const source = note.source ?? "manual";
  const isGenerated =
    note.isAutoGenerated ||
    source === "lesson_auto_note" ||
    source === "course_compendium";
  const status = note.generationStatus ?? (isGenerated ? "ready" : null);
  const canOpenGenerated = Boolean(onView || notebookHref);
  const openGeneratedNote = () => {
    // El visor modal mantiene al usuario dentro del curso; navegar al editor
    // del cuaderno queda como acción secundaria dentro del propio visor.
    if (onView) {
      onView(note);
      return;
    }
    if (notebookHref) router.push(notebookHref);
  };
  const openNote = () => {
    if (isGenerated) {
      openGeneratedNote();
      return;
    }
    onEdit(note);
  };

  return (
    <div
      className={styles.noteCard}
      onClick={openNote}
      onKeyDown={(event) => {
        if ((event.key === "Enter" || event.key === " ") && (!isGenerated || canOpenGenerated)) {
          event.preventDefault();
          openNote();
        }
      }}
      role="button"
      tabIndex={!isGenerated || canOpenGenerated ? 0 : -1}
    >
      <span className={styles.noteAccent} aria-hidden="true" />

      <div className={styles.noteTop}>
        <h4 className={styles.noteTitle}>
          {note.title}
        </h4>
        <span className={styles.noteTime}>{note.timestamp}</span>
      </div>

      <div className={styles.noteActions}>
        {!isGenerated ? (
          <>
            <button
              type="button"
              onClick={(event) => {
                event.stopPropagation();
                onEdit(note);
              }}
              className={styles.noteAction}
              title={editLabel}
            >
              <Edit2 aria-hidden="true" />
            </button>
            <button
              type="button"
              onClick={(event) => {
                event.stopPropagation();
                onDelete(note.id);
              }}
              className={styles.noteActionDanger}
              title={deleteLabel}
            >
              <Trash2 aria-hidden="true" />
            </button>
          </>
        ) : canOpenGenerated ? (
          <button
            type="button"
            onClick={(event) => {
              event.stopPropagation();
              openGeneratedNote();
            }}
            className={styles.noteAction}
            title={t("leftPanel.notesSection.viewGenerated")}
            aria-label={t("leftPanel.notesSection.viewGenerated")}
          >
            <Eye aria-hidden="true" />
          </button>
        ) : null}
      </div>

      <div className={styles.noteMeta}>
        <span className={styles.noteBadge}>
          {isGenerated ? <Sparkles aria-hidden="true" /> : null}
          {t(`leftPanel.notesSection.source.${source}`)}
        </span>
        {status ? (
          <span className={styles.noteBadgeMuted}>
            <LockKeyhole aria-hidden="true" />
            {t(`leftPanel.notesSection.generationStatus.${status}`)}
          </span>
        ) : null}
      </div>

      <p className={styles.notePreview}>
        {getNotePreviewText(note)}
      </p>

      {note.lessonTitle ? (
        <div className={styles.noteLesson}>
          <BookOpen aria-hidden="true" />
          <span>{note.lessonTitle}</span>
        </div>
      ) : null}

      {note.tags && note.tags.length > 0 && (
        <div className={styles.noteTags}>
          {note.tags.slice(0, 2).map((tag) => (
            <span
              key={tag}
              className={styles.noteTag}
            >
              {tag}
            </span>
          ))}
        </div>
      )}
    </div>
  );
}
