"use client";

import type {
  LearnEditableNote,
  LearnNoteListItem,
  LearnNoteFormData,
  LearnNotesStats,
  LearnSavedNote,
} from "../types";
import {
  normalizeGeneratedNoteHtml,
  normalizeNoteContentHtml,
} from "@/lib/notes/generated-note-html";

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function getString(
  record: Record<string, unknown>,
  key: string
): string | undefined {
  const value = record[key];

  return typeof value === "string" ? value : undefined;
}

function getStringArray(
  record: Record<string, unknown>,
  key: string
): string[] | undefined {
  const value = record[key];

  if (!Array.isArray(value)) {
    return undefined;
  }

  return value.filter((item): item is string => typeof item === "string");
}

function getBoolean(
  record: Record<string, unknown>,
  key: string
): boolean | undefined {
  const value = record[key];
  return typeof value === "boolean" ? value : undefined;
}

function getNoteSource(
  record: Record<string, unknown>
): LearnSavedNote["source"] | undefined {
  const source = getString(record, "source_type") || getString(record, "source");
  return source === "manual" ||
    source === "chat" ||
    source === "import" ||
    source === "lesson_auto_note" ||
    source === "course_compendium"
    ? source
    : undefined;
}

export function getDefaultNotesStats(totalLessons: number): LearnNotesStats {
  return {
    totalNotes: 0,
    lessonsWithNotes: totalLessons > 0 ? `0/${totalLessons}` : "0/0",
    lastUpdate: "-",
  };
}

export function htmlToPlainText(
  html: string,
  addLineBreaks: boolean = true
): string {
  if (!html) {
    return "";
  }

  if (typeof document === "undefined") {
    return html
      .replace(/<[^>]*>/g, "")
      .replace(/&nbsp;/g, " ")
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"')
      .trim();
  }

  const tempDiv = document.createElement("div");
  tempDiv.innerHTML = html;

  const lists = tempDiv.querySelectorAll("ul, ol");
  lists.forEach((list) => {
    const items = list.querySelectorAll("li");

    items.forEach((item, index) => {
      const prefix = list.tagName.toLowerCase() === "ol" ? `${index + 1}. ` : "• ";
      const text = item.textContent?.trim() || "";
      item.textContent = addLineBreaks ? `${prefix}${text}\n` : `${prefix}${text}`;
    });
  });

  if (addLineBreaks) {
    const paragraphs = tempDiv.querySelectorAll("p, div");
    paragraphs.forEach((paragraph) => {
      if (paragraph.textContent && !paragraph.textContent.trim().endsWith("\n")) {
        paragraph.textContent = `${paragraph.textContent}\n`;
      }
    });
  }

  const rawText = tempDiv.textContent || tempDiv.innerText || "";
  const collapsedText = addLineBreaks
    ? rawText.replace(/\n{3,}/g, "\n\n")
    : rawText;

  return collapsedText.trim();
}

export function generateNotePreview(
  html: string,
  maxLength: number = 50
): string {
  if (!html) {
    return "";
  }

  if (typeof document === "undefined") {
    const plainText = htmlToPlainText(html, false);
    return plainText.length > maxLength
      ? `${plainText.slice(0, maxLength)}...`
      : plainText;
  }

  const tempDiv = document.createElement("div");
  tempDiv.innerHTML = html;

  const firstChild = tempDiv.firstElementChild;

  if (firstChild && ["UL", "OL"].includes(firstChild.tagName)) {
    const firstItem = firstChild.querySelector("li");

    if (firstItem) {
      const prefix = firstChild.tagName === "OL" ? "1. " : "• ";
      const preview = `${prefix}${firstItem.textContent?.trim() || ""}`;

      return preview.length > maxLength
        ? `${preview.slice(0, maxLength)}...`
        : `${preview}...`;
    }
  }

  const plainText = htmlToPlainText(html, false);

  return plainText.length > maxLength
    ? `${plainText.slice(0, maxLength)}...`
    : plainText;
}

export function formatNoteTimestamp(dateString: string): string {
  const date = new Date(dateString);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 1) {
    return "Ahora";
  }

  if (diffMins < 60) {
    return `Hace ${diffMins} minuto${diffMins > 1 ? "s" : ""}`;
  }

  if (diffHours < 24) {
    return `Hace ${diffHours} hora${diffHours > 1 ? "s" : ""}`;
  }

  if (diffDays === 1) {
    return "Ayer";
  }

  if (diffDays < 7) {
    return `Hace ${diffDays} dias`;
  }

  return date.toLocaleDateString("es-ES", {
    day: "numeric",
    month: "short",
  });
}

function buildSavedNote(
  id: string,
  title: string,
  content: string,
  lessonId: string,
  timestamp: string,
  tags: string[],
  options: {
    isAutoGenerated?: boolean;
    source?: LearnSavedNote["source"];
    generationStatus?: LearnSavedNote["generationStatus"];
  } = {}
): LearnSavedNote {
  // Normalize every note at the client boundary. Generated notes get their
  // semantic sections/index, while older manual/chat notes still become
  // paragraphs and lists instead of rendering as one flat text node.
  const formattedContent =
    options.source === "lesson_auto_note" ||
    options.source === "course_compendium"
      ? normalizeGeneratedNoteHtml(content, options.source)
      : normalizeNoteContentHtml(content);

  return {
    id,
    title,
    content: generateNotePreview(formattedContent, 50),
    timestamp,
    lessonId,
    fullContent: formattedContent,
    isAutoGenerated: options.isAutoGenerated,
    source: options.source,
    generationStatus: options.generationStatus,
    tags,
  };
}

export function mapApiNoteToSavedNote(note: unknown): LearnSavedNote | null {
  if (!isRecord(note)) {
    return null;
  }

  const id = getString(note, "note_id");
  const title = getString(note, "note_title");
  const lessonId = getString(note, "lesson_id");
  const content = getString(note, "note_content") || "";
  const source = getNoteSource(note);
  const timestampSource =
    getString(note, "updated_at") || getString(note, "created_at");

  if (!id || !title || !lessonId) {
    return null;
  }

  return buildSavedNote(
    id,
    title,
    content,
    lessonId,
    formatNoteTimestamp(timestampSource || new Date().toISOString()),
    getStringArray(note, "note_tags") || [],
    {
      isAutoGenerated: getBoolean(note, "is_auto_generated"),
      source,
      generationStatus: getGenerationStatus(note),
    }
  );
}

export function buildSavedNoteFromMutation(
  note: unknown,
  lessonId: string
): LearnSavedNote | null {
  if (!isRecord(note)) {
    return null;
  }

  const id = getString(note, "note_id") || getString(note, "id");
  const title = getString(note, "note_title") || getString(note, "title");
  const content = getString(note, "note_content") || getString(note, "content") || "";

  if (!id || !title) {
    return null;
  }

  return buildSavedNote(
    id,
    title,
    content,
    lessonId,
    "Ahora",
    getStringArray(note, "note_tags") || getStringArray(note, "tags") || [],
    {
      isAutoGenerated:
        getBoolean(note, "is_auto_generated") ?? getBoolean(note, "isAutoGenerated"),
      source: getNoteSource(note) || "manual",
      generationStatus: getGenerationStatus(note),
    }
  );
}

function getGenerationStatus(
  record: Record<string, unknown>
): LearnSavedNote["generationStatus"] | undefined {
  const direct = getString(record, "generation_status");
  const nested = isRecord(record.generation_state)
    ? getString(record.generation_state, "status")
    : undefined;
  const value = direct || nested;
  return value === "queued" ||
    value === "processing" ||
    value === "partial" ||
    value === "ready" ||
    value === "failed" ||
    value === "stale"
    ? value
    : undefined;
}

export function getNotePreviewText(note: LearnNoteListItem): string {
  return note.content || generateNotePreview(note.fullContent || "", 50);
}

function buildLiaNoteTitle(lessonTitle?: string): string {
  if (!lessonTitle?.trim()) {
    return "Nota de SofLIA";
  }

  return `SofLIA: ${lessonTitle.trim()}`;
}

export function buildLiaDraftNote(
  content: string,
  options: {
    chatProvenance?: LearnEditableNote["chatProvenance"];
    lessonId?: string;
    lessonTitle?: string;
    question?: string;
  } = {}
): LearnEditableNote {
  const escapedQuestion = (options.question || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\"/g, "&quot;")
    .replace(/'/g, "&#39;");
  const qaContent = escapedQuestion
    ? normalizeGeneratedNoteHtml(
        `<h2>Mi pregunta</h2><p>${escapedQuestion}</p><h2>Respuesta de SofLIA</h2>${content}`,
        "lesson_auto_note"
      )
    : content;

  return {
    chatProvenance: options.chatProvenance,
    id: "",
    lessonId: options.lessonId,
    title: buildLiaNoteTitle(options.lessonTitle),
    content: qaContent,
    sourceType: "chat",
    tags: ["SofLIA", "Clase"],
  };
}

export function normalizeNoteFormData(noteData: LearnNoteFormData) {
  const sourceType = noteData.sourceType || "manual";

  return {
    note_title: noteData.title.trim(),
    note_content: noteData.content.trim(),
    note_tags: noteData.tags || [],
    source_type: sourceType,
    ...(sourceType === "chat" && noteData.chatProvenance
      ? {
          chat_provenance: {
            conversation_id: noteData.chatProvenance.conversationId,
            user_message_id: noteData.chatProvenance.userMessageId,
            assistant_message_id: noteData.chatProvenance.assistantMessageId,
          },
        }
      : {}),
  };
}
