import DOMPurify, { type Config } from 'dompurify'

const SAFE_RICH_HTML_CONFIG: Config = {
  ALLOW_DATA_ATTR: false,
  ALLOWED_ATTR: [
    'alt',
    'class',
    'colspan',
    'href',
    'rel',
    'rowspan',
    'scope',
    'src',
    'target',
    'title',
  ],
  ALLOWED_TAGS: [
    'a',
    'abbr',
    'b',
    'blockquote',
    'br',
    'caption',
    'code',
    'del',
    'div',
    'em',
    'figcaption',
    'figure',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hr',
    'i',
    'img',
    'li',
    'ol',
    'p',
    'pre',
    'span',
    'strong',
    'sub',
    'sup',
    'table',
    'tbody',
    'td',
    'tfoot',
    'th',
    'thead',
    'tr',
    'u',
    'ul',
  ],
  ALLOWED_URI_REGEXP: /^(?:(?:https?|mailto):|\/(?!\/)|#)/i,
  FORBID_ATTR: ['style', 'srcset'],
  FORBID_TAGS: ['button', 'embed', 'form', 'iframe', 'input', 'math', 'object', 'script', 'select', 'style', 'svg', 'textarea'],
}

export function sanitizeRichHtml(html: string): string {
  return DOMPurify.sanitize(html, SAFE_RICH_HTML_CONFIG)
}
