export const FALLBACK_TEXT_ES = {
  learningTitle: 'Aprendizaje y finalizacion',
  adoptionTitle: 'Adopcion de IA y notas',
  qualityTitle: 'Calidad de respuestas',
  metricProgress: 'Progreso y cierre',
  metricSoflia: 'Adopcion SofLIA',
  metricQuality: 'Calidad operativa',
  actionPlanTitle: 'Plan de accion sugerido',
  noHierarchy: 'No hay jerarquia suficiente para comparar regiones, zonas o areas.',
  noRiskCourse: 'No hay cursos con senales criticas en el periodo filtrado.',
  noSegment: 'No hay segmentos suficientes para comparar calidad.',
  recommendSoflia: 'Refuerza el uso de SofLIA en los segmentos con menor adopcion y cruza el seguimiento con avance de curso.',
  recommendHierarchy: 'Usa el cuadro de honor por region, zona y area para replicar practicas de los equipos con mejor score.',
  recommendQuality: 'Revisa actividades con baja calidad y alto uso de ayuda para ajustar instrucciones, ejemplos y criterios.',
  actionPlanSegment: 'Prioriza segmentos con baja calidad o bajo avance antes de ampliar nuevas asignaciones.',
  actionPlanCourse: 'Revisa cursos con mayor riesgo operativo y cruza avance, vencimientos y ayuda solicitada.',
  actionPlanData: 'Completa datos demograficos faltantes para mejorar precision estadistica de RRHH.',
  summary: (quality: number, progress: number) => `Lectura automatica: la calidad global es ${quality}% y el progreso promedio es ${progress}%.`,
  metricProgressDetail: (completion: number, days: number) => `Finalizacion ${completion}% y mediana de cierre ${days} dias.`,
  metricSofliaDetail: (conversations: number, messages: number) => `${conversations} conversaciones y ${messages} mensajes analizados.`,
  metricQualityDetail: (quiz: number, activity: number, soflia: number) => `Evaluaciones ${quiz}%, actividades ${activity}% y SofLIA ${soflia}%.`,
  learningPoint: (completion: number, days: number) => `La finalizacion global es ${completion}% y el tiempo promedio de cierre es ${days} dias.`,
  riskCourse: (title: string, overdue: number) => `${title} concentra riesgo operativo con ${overdue} vencimientos.`,
  adoptionPoint: (soflia: number, notes: number) => `La adopcion de SofLIA es ${soflia}% y la adopcion de notas es ${notes}%.`,
  bestRegion: (name: string, score: number) => `${name} lidera el ranking regional con score ${score}%.`,
  qualityPoint: (quality: number, offTopic: number) => `El score de calidad es ${quality}% y la tasa fuera de tema es ${offTopic}%.`,
  segmentPoint: (label: string, score: number) => `${label} requiere revision: registra score de calidad ${score}%.`,
  riskQuality: (help: number) => `Usuarios que piden ayuda en actividades: ${help}%.`,
  riskData: (completion: number) => `Demografia completa: ${completion}%. Los faltantes reducen precision estadistica.`,
}
