export const FALLBACK_TEXT_EN = {
  learningTitle: 'Learning and completion',
  adoptionTitle: 'AI and notes adoption',
  qualityTitle: 'Response quality',
  metricProgress: 'Progress and closure',
  metricSoflia: 'SofLIA adoption',
  metricQuality: 'Operational quality',
  actionPlanTitle: 'Suggested action plan',
  noHierarchy: 'There is not enough hierarchy data to compare regions, zones, or areas.',
  noRiskCourse: 'No course shows critical risk signals in the filtered period.',
  noSegment: 'There are not enough segments to compare quality.',
  recommendSoflia: 'Increase SofLIA adoption in lower-adoption segments and cross-check it with course progress.',
  recommendHierarchy: 'Use the leaderboard by region, zone, and area to replicate practices from top scoring teams.',
  recommendQuality: 'Review activities with low quality and high help usage to adjust instructions, examples, and criteria.',
  actionPlanSegment: 'Prioritize follow-up for segments with low quality or low progress before expanding new assignments.',
  actionPlanCourse: 'Review highest-risk courses and compare progress, overdue work, and help requests.',
  actionPlanData: 'Complete missing demographic data to improve HR statistical precision.',
  summary: (quality: number, progress: number) => `Automatic read: overall quality is ${quality}% and average progress is ${progress}%.`,
  metricProgressDetail: (completion: number, days: number) => `Completion ${completion}% and median closure ${days} days.`,
  metricSofliaDetail: (conversations: number, messages: number) => `${conversations} conversations and ${messages} messages analyzed.`,
  metricQualityDetail: (quiz: number, activity: number, soflia: number) => `Assessments ${quiz}%, activities ${activity}%, and SofLIA ${soflia}%.`,
  learningPoint: (completion: number, days: number) => `Overall completion is ${completion}% and average closing time is ${days} days.`,
  riskCourse: (title: string, overdue: number) => `${title} concentrates operational risk with ${overdue} overdue items.`,
  adoptionPoint: (soflia: number, notes: number) => `SofLIA adoption is ${soflia}% and notes adoption is ${notes}%.`,
  bestRegion: (name: string, score: number) => `${name} leads the regional ranking with a ${score}% score.`,
  qualityPoint: (quality: number, offTopic: number) => `Quality score is ${quality}% and off-topic rate is ${offTopic}%.`,
  segmentPoint: (label: string, score: number) => `${label} needs review: quality score is ${score}%.`,
  riskQuality: (help: number) => `Users needing activity help: ${help}%.`,
  riskData: (completion: number) => `Complete demographics: ${completion}%. Missing fields reduce statistical precision.`,
}
