export const FALLBACK_TEXT_PT = {
  learningTitle: 'Aprendizagem e conclusao',
  adoptionTitle: 'Adocao de IA e notas',
  qualityTitle: 'Qualidade das respostas',
  metricProgress: 'Progresso e fechamento',
  metricSoflia: 'Adocao SofLIA',
  metricQuality: 'Qualidade operacional',
  actionPlanTitle: 'Plano de acao sugerido',
  noHierarchy: 'Nao ha hierarquia suficiente para comparar regioes, zonas ou areas.',
  noRiskCourse: 'Nenhum curso mostra sinais criticos no periodo filtrado.',
  noSegment: 'Nao ha segmentos suficientes para comparar qualidade.',
  recommendSoflia: 'Reforce o uso do SofLIA nos segmentos com menor adocao e cruze com progresso de curso.',
  recommendHierarchy: 'Use o quadro de honra por regiao, zona e area para replicar praticas dos melhores times.',
  recommendQuality: 'Revise atividades com baixa qualidade e alto uso de ajuda para ajustar instrucoes, exemplos e criterios.',
  actionPlanSegment: 'Priorize segmentos com baixa qualidade ou baixo progresso antes de ampliar novas atribuicoes.',
  actionPlanCourse: 'Revise cursos de maior risco e compare progresso, vencimentos e pedidos de ajuda.',
  actionPlanData: 'Complete dados demograficos faltantes para melhorar a precisao estatistica de RH.',
  summary: (quality: number, progress: number) => `Leitura automatica: a qualidade global e ${quality}% e o progresso medio e ${progress}%.`,
  metricProgressDetail: (completion: number, days: number) => `Conclusao ${completion}% e mediana de fechamento ${days} dias.`,
  metricSofliaDetail: (conversations: number, messages: number) => `${conversations} conversas e ${messages} mensagens analisadas.`,
  metricQualityDetail: (quiz: number, activity: number, soflia: number) => `Avaliacoes ${quiz}%, atividades ${activity}% e SofLIA ${soflia}%.`,
  learningPoint: (completion: number, days: number) => `A conclusao global e ${completion}% e o tempo medio de fechamento e ${days} dias.`,
  riskCourse: (title: string, overdue: number) => `${title} concentra risco operacional com ${overdue} vencimentos.`,
  adoptionPoint: (soflia: number, notes: number) => `A adocao do SofLIA e ${soflia}% e a adocao de notas e ${notes}%.`,
  bestRegion: (name: string, score: number) => `${name} lidera o ranking regional com score ${score}%.`,
  qualityPoint: (quality: number, offTopic: number) => `O score de qualidade e ${quality}% e a taxa fora de tema e ${offTopic}%.`,
  segmentPoint: (label: string, score: number) => `${label} requer revisao: registra score de qualidade ${score}%.`,
  riskQuality: (help: number) => `Usuarios que pedem ajuda em atividades: ${help}%.`,
  riskData: (completion: number) => `Demografia completa: ${completion}%. Campos faltantes reduzem a precisao estatistica.`,
}
