'use client'

import { BookOpen, Users } from 'lucide-react'
import type { ReportsAnalyticsResponse } from '../../types/reports-analytics.types'
import type { ReportsAnalyticsT, ThemeTokens } from './types'

const AUTO_COLOR = '#3b82f6'
const MANUAL_COLOR = '#10b981'

const R = 42
const CX = 60
const CY = 60
const CIRC = 2 * Math.PI * R

function DonutArc({ pct, color, offsetPct }: { pct: number; color: string; offsetPct: number }) {
  if (pct <= 0) return null
  const dash = (pct / 100) * CIRC
  const gap = CIRC - dash
  const rotation = (offsetPct / 100) * 360 - 90
  return (
    <circle
      cx={CX} cy={CY} r={R}
      fill="none"
      stroke={color}
      strokeWidth="14"
      strokeLinecap="round"
      strokeDasharray={`${dash} ${gap}`}
      style={{ transform: `rotate(${rotation}deg)`, transformOrigin: `${CX}px ${CY}px` }}
    />
  )
}

function KpiCard({ value, label, icon: Icon, valueColor, theme }: {
  value: string | number
  label: string
  icon: typeof BookOpen
  valueColor?: string
  theme: ThemeTokens
}) {
  return (
    <div className="flex items-center gap-3 rounded-xl border p-4" style={{ borderColor: theme.borderColor, backgroundColor: theme.inputBg }}>
      <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg" style={{ backgroundColor: theme.hoverBg }}>
        <Icon className="h-4 w-4" style={{ color: theme.actionColor }} />
      </div>
      <div className="min-w-0">
        <p className="text-xl font-bold leading-none" style={{ color: valueColor ?? theme.textColor }}>{value}</p>
        <p className="mt-1 text-xs leading-none" style={{ color: theme.mutedTextColor }}>{label}</p>
      </div>
    </div>
  )
}

export function NotesCompositionPanel({
  data,
  theme,
  t,
}: {
  data: Pick<ReportsAnalyticsResponse, 'notes'>
  theme: ThemeTokens
  t: ReportsAnalyticsT
}) {
  const { notes } = data

  if (!notes.totalNotes) {
    return (
      <section className="rounded-lg border p-5" style={{ backgroundColor: theme.cardBg, borderColor: theme.borderColor }}>
        <h2 className="text-base font-semibold sm:text-lg" style={{ color: theme.textColor }}>
          {t('reportsAnalytics.sections.notesComposition')}
        </h2>
        <p className="mt-6 text-center text-sm" style={{ color: theme.mutedTextColor }}>
          {t('reportsAnalytics.notesPanel.noData')}
        </p>
      </section>
    )
  }

  // adoptionRate is stored as 0–100 (percentage), not 0–1
  const adoptionPct = Math.min(100, Math.round(notes.adoptionRate))
  const adoptionColor = adoptionPct >= 50 ? '#10b981' : adoptionPct >= 25 ? '#f59e0b' : '#ef4444'

  const autoPct = notes.totalNotes > 0 ? Math.round((notes.autoGenerated / notes.totalNotes) * 100) : 0
  const manualPct = 100 - autoPct

  const topCourses = [...notes.byCourse].sort((a, b) => b.value - a.value).slice(0, 5)
  const maxCourseNotes = Math.max(...topCourses.map((c) => c.value), 1)

  return (
    <section className="rounded-lg border p-5" style={{ backgroundColor: theme.cardBg, borderColor: theme.borderColor }}>
      <h2 className="text-base font-semibold sm:text-lg" style={{ color: theme.textColor }}>
        {t('reportsAnalytics.sections.notesComposition')}
      </h2>
      <p className="mt-1 text-sm" style={{ color: theme.subtextColor }}>
        {t('reportsAnalytics.sections.notesCompositionSubtitle')}
      </p>

      <div className="mt-4 grid gap-6 lg:grid-cols-2">
        {/* Left: KPI cards + donut */}
        <div className="flex flex-col gap-4">
          <div className="grid grid-cols-3 gap-3">
            <KpiCard
              value={notes.totalNotes}
              label={t('reportsAnalytics.notesPanel.totalNotes')}
              icon={BookOpen}
              theme={theme}
            />
            <KpiCard
              value={notes.usersWithNotes}
              label={t('reportsAnalytics.notesPanel.usersWithNotes')}
              icon={Users}
              theme={theme}
            />
            <KpiCard
              value={`${adoptionPct}%`}
              label={t('reportsAnalytics.notesPanel.adoptionRate')}
              icon={Users}
              valueColor={adoptionColor}
              theme={theme}
            />
          </div>

          {/* Donut with center label */}
          <div className="flex items-center gap-6 rounded-xl border p-4" style={{ borderColor: theme.borderColor }}>
            <div className="relative shrink-0">
              <svg viewBox="0 0 120 120" width="108" height="108">
                {/* track */}
                <circle cx={CX} cy={CY} r={R} fill="none" stroke={theme.hoverBg} strokeWidth="14" />
                <DonutArc pct={autoPct} color={AUTO_COLOR} offsetPct={0} />
                <DonutArc pct={manualPct} color={MANUAL_COLOR} offsetPct={autoPct} />
                {/* center text */}
                <text x={CX} y={CY - 6} textAnchor="middle" fontSize="14" fontWeight="700" fill={theme.textColor}>
                  {notes.totalNotes}
                </text>
                <text x={CX} y={CY + 10} textAnchor="middle" fontSize="8" fill={theme.mutedTextColor}>
                  notas
                </text>
              </svg>
            </div>
            <div className="space-y-4">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="h-3 w-3 rounded-full shrink-0" style={{ backgroundColor: AUTO_COLOR }} />
                  <span className="text-xs font-medium" style={{ color: theme.mutedTextColor }}>
                    {t('reportsAnalytics.notesPanel.autoGenerated')}
                  </span>
                </div>
                <p className="text-lg font-bold" style={{ color: theme.textColor }}>
                  {notes.autoGenerated}
                  <span className="ml-1.5 text-sm font-normal" style={{ color: theme.mutedTextColor }}>({autoPct}%)</span>
                </p>
              </div>
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="h-3 w-3 rounded-full shrink-0" style={{ backgroundColor: MANUAL_COLOR }} />
                  <span className="text-xs font-medium" style={{ color: theme.mutedTextColor }}>
                    {t('reportsAnalytics.notesPanel.manual')}
                  </span>
                </div>
                <p className="text-lg font-bold" style={{ color: theme.textColor }}>
                  {notes.manual}
                  <span className="ml-1.5 text-sm font-normal" style={{ color: theme.mutedTextColor }}>({manualPct}%)</span>
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Right: notes by course */}
        {topCourses.length > 0 && (
          <div className="rounded-xl border p-4" style={{ borderColor: theme.borderColor }}>
            <p className="mb-4 text-xs font-semibold uppercase tracking-wide" style={{ color: theme.mutedTextColor }}>
              {t('reportsAnalytics.notesPanel.byCourse')}
            </p>
            <div className="space-y-4">
              {topCourses.map((course, i) => {
                const barPct = Math.round((course.value / maxCourseNotes) * 100)
                const rankColor = i === 0 ? theme.actionColor : theme.accentColor
                return (
                  <div key={course.key}>
                    <div className="mb-1.5 flex items-start justify-between gap-3">
                      <p
                        className="line-clamp-2 text-sm leading-5"
                        style={{ color: theme.textColor }}
                        title={course.label}
                      >
                        {course.label}
                      </p>
                      <span
                        className="shrink-0 rounded-full px-2 py-0.5 text-xs font-bold"
                        style={{ backgroundColor: rankColor + '20', color: rankColor }}
                      >
                        {course.value}
                      </span>
                    </div>
                    <div className="h-1.5 w-full overflow-hidden rounded-full" style={{ backgroundColor: theme.hoverBg }}>
                      <div
                        className="h-full rounded-full transition-all duration-500"
                        style={{ width: `${barPct}%`, backgroundColor: rankColor + 'CC' }}
                      />
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        )}
      </div>
    </section>
  )
}
