import type { NotebookItem, NotebookNotesResponse } from '../types'

export type NotebookCursor = {
  id: string
  kind: NotebookItem['kind']
  updatedAt: string
}

export function getNotebookItemIdentity(item: NotebookItem) {
  return item.kind === 'manual_note' ? item.noteId : item.summaryId
}

export function encodeNotebookCursor(item: NotebookItem): string {
  return Buffer.from(
    JSON.stringify({
      id: getNotebookItemIdentity(item),
      kind: item.kind,
      updatedAt: item.updatedAt,
    }),
    'utf8',
  ).toString('base64url')
}

export function decodeNotebookCursor(rawCursor?: string): NotebookCursor | null {
  if (!rawCursor) return null

  try {
    const parsed = JSON.parse(
      Buffer.from(rawCursor, 'base64url').toString('utf8'),
    ) as Partial<NotebookCursor>

    if (
      typeof parsed.id !== 'string' ||
      (parsed.kind !== 'manual_note' && parsed.kind !== 'soflia_summary') ||
      typeof parsed.updatedAt !== 'string' ||
      Number.isNaN(new Date(parsed.updatedAt).getTime())
    ) {
      return null
    }

    return {
      id: parsed.id,
      kind: parsed.kind,
      updatedAt: parsed.updatedAt,
    }
  } catch {
    return null
  }
}

export function compareNotebookItems(left: NotebookItem, right: NotebookItem) {
  const timestampComparison =
    new Date(right.updatedAt).getTime() - new Date(left.updatedAt).getTime()

  if (timestampComparison !== 0) {
    return timestampComparison
  }

  const kindComparison = left.kind.localeCompare(right.kind)
  if (kindComparison !== 0) {
    return kindComparison
  }

  return getNotebookItemIdentity(right).localeCompare(getNotebookItemIdentity(left))
}

function buildCursorItem(cursor: NotebookCursor): NotebookItem {
  if (cursor.kind === 'manual_note') {
    return {
      kind: 'manual_note',
      noteId: cursor.id,
      title: '',
      contentPreview: '',
      content: '',
      tags: [],
      sourceType: 'manual',
      isAutoGenerated: false,
      lessonId: '',
      lessonTitle: '',
      moduleTitle: '',
      courseId: '',
      courseTitle: '',
      organizationId: null,
      createdAt: '',
      updatedAt: cursor.updatedAt,
    }
  }

  return {
    kind: 'soflia_summary',
    summaryId: cursor.id,
    title: '',
    contentPreview: '',
    contentHtml: '',
    contentMarkdown: '',
    status: 'ready',
    version: 1,
    moduleId: '',
    moduleTitle: '',
    courseId: '',
    courseTitle: '',
    organizationId: null,
    generatedAt: null,
    createdAt: '',
    updatedAt: cursor.updatedAt,
  }
}

function isAfterCursor(item: NotebookItem, cursor: NotebookCursor | null) {
  if (!cursor) return true
  return compareNotebookItems(item, buildCursorItem(cursor)) > 0
}

export function mergeNotebookSourcesPage(
  manualNotes: NotebookItem[],
  sofliaSummaries: NotebookItem[],
  limit: number,
  cursor: NotebookCursor | null,
): NotebookNotesResponse {
  const merged = [...manualNotes, ...sofliaSummaries]
    .filter((item) => isAfterCursor(item, cursor))
    .sort(compareNotebookItems)

  const page = merged.slice(0, limit)
  const hasMore = merged.length > limit

  return {
    items: page,
    nextCursor: hasMore && page.length > 0 ? encodeNotebookCursor(page[page.length - 1]) : null,
    totalCount: page.length,
  }
}
