/**
 * Notebook — Pure tree builder & row mappers.
 *
 * No server/database dependencies, so it can be unit-tested in isolation.
 * Groups flat note rows (with nested lesson/module/course) into the
 * Course -> Lesson -> Notes structure, ordered by module/lesson order.
 */

import type { Json } from '@/lib/supabase/types'
import type {
  NotebookCourseNode,
  NotebookLessonNode,
  NotebookNoteDetail,
  NotebookNoteSource,
  NotebookNoteSummary,
  NotebookTree,
} from '../types'

export interface NestedCourse {
  id: string
  title: string
  slug: string | null
}

export interface NestedModule {
  course_id: string
  module_order_index: number | null
  courses: NestedCourse | null
}

export interface NestedLesson {
  lesson_id: string
  lesson_title: string
  lesson_order_index: number | null
  course_modules: NestedModule | null
}

export interface TreeNoteRow {
  note_id: string
  note_title: string
  note_tags: Json
  source_type: string | null
  is_auto_generated: boolean | null
  created_at: string | null
  updated_at: string | null
  course_lessons: NestedLesson | null
}

export interface DetailRow {
  note_id: string
  note_title: string
  note_content: string
  note_tags: Json
  source_type: string | null
  is_auto_generated: boolean | null
  created_at: string | null
  updated_at: string | null
  user_id: string
  lesson_id: string
  organization_id: string | null
  course_lessons: {
    lesson_id: string
    lesson_title: string
    course_modules: {
      course_id: string
      courses: NestedCourse | null
    } | null
  } | null
}

export function parseTags(value: Json): string[] {
  if (!Array.isArray(value)) return []
  return value.filter((tag): tag is string => typeof tag === 'string')
}

export function parseSource(value: string | null): NotebookNoteSource {
  return value === 'chat' ||
    value === 'import' ||
    value === 'manual' ||
    value === 'lesson_auto_note'
    ? value
    : 'manual'
}

export function toSummary(row: TreeNoteRow): NotebookNoteSummary {
  return {
    noteId: row.note_id,
    title: row.note_title,
    tags: parseTags(row.note_tags),
    source: parseSource(row.source_type),
    isAutoGenerated: row.is_auto_generated ?? false,
    createdAt: row.created_at ?? '',
    updatedAt: row.updated_at ?? '',
  }
}

export function toNoteDetail(row: DetailRow): NotebookNoteDetail {
  const lesson = row.course_lessons
  const course = lesson?.course_modules?.courses
  return {
    noteId: row.note_id,
    title: row.note_title,
    content: row.note_content,
    tags: parseTags(row.note_tags),
    source: parseSource(row.source_type),
    isAutoGenerated: row.is_auto_generated ?? false,
    createdAt: row.created_at ?? '',
    updatedAt: row.updated_at ?? '',
    lessonId: row.lesson_id,
    lessonTitle: lesson?.lesson_title ?? '',
    courseId: lesson?.course_modules?.course_id ?? course?.id ?? '',
    courseTitle: course?.title ?? '',
    courseSlug: course?.slug ?? null,
  }
}

/**
 * Groups note rows into a Course -> Lesson -> Notes tree. Rows missing their
 * course/lesson relations are skipped. Lessons are ordered by module then
 * lesson order; courses alphabetically; notes by most recently updated.
 */
export function buildNotebookTree(rows: TreeNoteRow[]): NotebookTree {
  const courseMap = new Map<
    string,
    {
      node: NotebookCourseNode
      lessons: Map<string, { node: NotebookLessonNode; moduleOrder: number }>
    }
  >()

  let totalNotes = 0

  for (const row of rows) {
    const lesson = row.course_lessons
    const module = lesson?.course_modules
    const course = module?.courses
    if (!lesson || !module || !course) continue

    totalNotes += 1

    let courseEntry = courseMap.get(course.id)
    if (!courseEntry) {
      courseEntry = {
        node: {
          courseId: course.id,
          title: course.title,
          slug: course.slug,
          totalNotes: 0,
          lessons: [],
        },
        lessons: new Map(),
      }
      courseMap.set(course.id, courseEntry)
    }

    let lessonEntry = courseEntry.lessons.get(lesson.lesson_id)
    if (!lessonEntry) {
      lessonEntry = {
        node: {
          lessonId: lesson.lesson_id,
          title: lesson.lesson_title,
          orderIndex: lesson.lesson_order_index ?? 0,
          notes: [],
        },
        moduleOrder: module.module_order_index ?? 0,
      }
      courseEntry.lessons.set(lesson.lesson_id, lessonEntry)
    }

    lessonEntry.node.notes.push(toSummary(row))
    courseEntry.node.totalNotes += 1
  }

  const courses: NotebookCourseNode[] = Array.from(courseMap.values())
    .map((entry) => {
      entry.node.lessons = Array.from(entry.lessons.values())
        .sort((a, b) =>
          a.moduleOrder !== b.moduleOrder
            ? a.moduleOrder - b.moduleOrder
            : a.node.orderIndex - b.node.orderIndex,
        )
        .map((lessonEntry) => lessonEntry.node)
      return entry.node
    })
    .sort((a, b) => a.title.localeCompare(b.title))

  return { courses, totalNotes }
}
