import type { BlueprintCopy } from '../types'

export const enBlueprintCopy: BlueprintCopy = {
  executive: 'SofLIA Summary',
  executivePurpose: 'Executive narrative, findings, risks, and recommended actions.',
  dashboard: 'Dashboard',
  dashboardPurpose: 'Leadership-ready key indicators.',
  trends: 'Trends',
  trendsPurpose: 'Time evolution of learning and SofLIA usage.',
  courses: 'Courses',
  coursesPurpose: 'Course progress and risk.',
  users: 'Users',
  usersPurpose: 'Authorized exportable user detail.',
  segments: 'Segments',
  segmentsPurpose: 'Comparison by age, gender, job title, and role.',
  quality: 'Quality',
  qualityPurpose: 'Response, assessment, and activity quality.',
  rawData: 'Raw data',
  rawDataPurpose: 'Clean tables for audit and BI.',
  progress: 'Average progress',
  soflia: 'SofLIA adoption',
  learningFinding: 'Learning and progress',
  segmentFinding: 'Segments and data quality',
  noCourseRisk: 'No course shows clear operational risk in the period.',
  noSegmentRisk: 'There are not enough segments to prioritize an action.',
  recommendSoflia: 'Reinforce SofLIA usage where progress or quality is low.',
  recommendCourse: 'Prioritize courses with overdue work or low progress before assigning new content.',
  recommendData: 'Complete demographic data to improve comparisons and segmentation.',
  summary: (progress, quality) => `SofLIA prepared a report with ${progress}% average progress and ${quality}% overall quality.`,
  completionDetail: (completion) => `Course completion: ${completion}%.`,
  sofliaDetail: (conversations, messages) => `${conversations} conversations and ${messages} messages.`,
  qualityDetail: (evidence) => `${evidence} evidence points analyzed.`,
  learningPoint: (completed, assigned) => `${completed} of ${assigned} assigned courses are completed.`,
  courseRisk: (course, overdue) => `${course} needs follow-up due to ${overdue} overdue assignments.`,
  segmentRisk: (segment, quality) => `${segment} records ${quality}% quality and needs review.`,
  dataQualityPoint: (completion) => `Demographic completeness is ${completion}%.`,
  overdueRisk: (overdue) => `Overdue assignments: ${overdue}.`,
  helpRisk: (helpRate) => `Users needing help: ${helpRate}%.`,
}
