import type { BlueprintCopy } from '../types'

export const esBlueprintCopy: BlueprintCopy = {
  executive: 'Resumen SofLIA',
  executivePurpose: 'Narrativa ejecutiva, hallazgos, riesgos y acciones recomendadas.',
  dashboard: 'Dashboard',
  dashboardPurpose: 'Indicadores clave listos para direccion.',
  trends: 'Tendencias',
  trendsPurpose: 'Evolucion temporal de aprendizaje y uso de SofLIA.',
  courses: 'Cursos',
  coursesPurpose: 'Riesgo y avance por curso.',
  users: 'Usuarios',
  usersPurpose: 'Detalle exportable de usuarios autorizados.',
  segments: 'Segmentos',
  segmentsPurpose: 'Comparacion por edad, genero, puesto y rol.',
  quality: 'Calidad',
  qualityPurpose: 'Calidad de respuestas, evaluaciones y actividad.',
  rawData: 'Datos crudos',
  rawDataPurpose: 'Tablas limpias para auditoria y BI.',
  progress: 'Progreso promedio',
  soflia: 'Adopcion SofLIA',
  learningFinding: 'Aprendizaje y avance',
  segmentFinding: 'Segmentos y calidad de datos',
  noCourseRisk: 'No hay cursos con riesgo operativo evidente en el periodo.',
  noSegmentRisk: 'No hay segmentos suficientes para priorizar una accion.',
  recommendSoflia: 'Refuerza el uso de SofLIA donde hay bajo avance o baja calidad.',
  recommendCourse: 'Prioriza cursos con vencimientos o bajo progreso antes de asignar contenido nuevo.',
  recommendData: 'Completa datos demograficos para mejorar comparaciones y segmentacion.',
  summary: (progress, quality) => `SofLIA preparo un reporte con progreso promedio de ${progress}% y calidad global de ${quality}%.`,
  completionDetail: (completion) => `Finalizacion de cursos: ${completion}%.`,
  sofliaDetail: (conversations, messages) => `${conversations} conversaciones y ${messages} mensajes.`,
  qualityDetail: (evidence) => `${evidence} evidencias analizadas.`,
  learningPoint: (completed, assigned) => `${completed} de ${assigned} cursos asignados estan completados.`,
  courseRisk: (course, overdue) => `${course} requiere seguimiento por ${overdue} asignaciones vencidas.`,
  segmentRisk: (segment, quality) => `${segment} registra calidad de ${quality}% y requiere revision.`,
  dataQualityPoint: (completion) => `La completitud demografica es ${completion}%.`,
  overdueRisk: (overdue) => `Asignaciones vencidas: ${overdue}.`,
  helpRisk: (helpRate) => `Usuarios que necesitaron ayuda: ${helpRate}%.`,
}
