import type { BlueprintCopy } from '../types'

export const ptBlueprintCopy: BlueprintCopy = {
  executive: 'Resumo SofLIA',
  executivePurpose: 'Narrativa executiva, achados, riscos e acoes recomendadas.',
  dashboard: 'Dashboard',
  dashboardPurpose: 'Indicadores principais para lideranca.',
  trends: 'Tendencias',
  trendsPurpose: 'Evolucao temporal de aprendizagem e uso do SofLIA.',
  courses: 'Cursos',
  coursesPurpose: 'Risco e progresso por curso.',
  users: 'Usuarios',
  usersPurpose: 'Detalhe autorizado e exportavel de usuarios.',
  segments: 'Segmentos',
  segmentsPurpose: 'Comparacao por idade, genero, cargo e funcao.',
  quality: 'Qualidade',
  qualityPurpose: 'Qualidade de respostas, avaliacoes e atividade.',
  rawData: 'Dados brutos',
  rawDataPurpose: 'Tabelas limpas para auditoria e BI.',
  progress: 'Progresso medio',
  soflia: 'Adocao SofLIA',
  learningFinding: 'Aprendizagem e progresso',
  segmentFinding: 'Segmentos e qualidade dos dados',
  noCourseRisk: 'Nenhum curso mostra risco operacional evidente no periodo.',
  noSegmentRisk: 'Nao ha segmentos suficientes para priorizar uma acao.',
  recommendSoflia: 'Reforce o uso do SofLIA onde ha baixo progresso ou baixa qualidade.',
  recommendCourse: 'Priorize cursos com vencimentos ou baixo progresso antes de atribuir novo conteudo.',
  recommendData: 'Complete dados demograficos para melhorar comparacoes e segmentacao.',
  summary: (progress, quality) => `SofLIA preparou um relatorio com progresso medio de ${progress}% e qualidade geral de ${quality}%.`,
  completionDetail: (completion) => `Conclusao de cursos: ${completion}%.`,
  sofliaDetail: (conversations, messages) => `${conversations} conversas e ${messages} mensagens.`,
  qualityDetail: (evidence) => `${evidence} evidencias analisadas.`,
  learningPoint: (completed, assigned) => `${completed} de ${assigned} cursos atribuidos estao concluidos.`,
  courseRisk: (course, overdue) => `${course} requer acompanhamento por ${overdue} atribuicoes vencidas.`,
  segmentRisk: (segment, quality) => `${segment} registra qualidade de ${quality}% e requer revisao.`,
  dataQualityPoint: (completion) => `A completude demografica e ${completion}%.`,
  overdueRisk: (overdue) => `Atribuicoes vencidas: ${overdue}.`,
  helpRisk: (helpRate) => `Usuarios que precisaram de ajuda: ${helpRate}%.`,
}
