export enum StudyPlannerPhase {
  WELCOME = 0,
  CONTEXT_ANALYSIS = 1,
  COURSE_SELECTION = 2,
  CALENDAR_INTEGRATION = 3,
  TIME_CONFIGURATION = 4,
  BREAK_CONFIGURATION = 5,
  SCHEDULE_CONFIGURATION = 6,
  SUMMARY = 7,
  COMPLETE = 8,
}
