import { clampPercentage } from '../reports-analytics.helpers'
import { ensureCourse } from './ensure-course'
import { getCourseIdFromLesson } from './get-course-id-from-lesson'
import { pushAiSample } from './push-ai-sample'
import { pushLastActivity } from './push-last-activity'
import { shouldIncludeEngagementRecord } from './should-include-engagement-record'
import { stringifySampleContent } from './stringify-sample-content'
import type { BuildContext } from './build-context'
import type { LessonNoteRecord } from './lesson-note-record'

export function applyLessonNotes(context: BuildContext, records: LessonNoteRecord[]): void {
  records.forEach((record) => {
    const courseId = getCourseIdFromLesson(record.course_lessons)
    if (
      !shouldIncludeEngagementRecord(context, record.user_id, courseId, [
        record.created_at,
        record.updated_at,
      ])
    ) {
      return
    }

    const user = context.users.get(record.user_id)
    if (!user) return

    const course = ensureCourse(context, courseId, null)
    user.notesQualityScores.push(record.note_content ? clampPercentage(Math.min(record.note_content.length / 8, 100)) : 0)
    user.detail.notesCreated += 1
    course.notesCount += 1
    course.activeLearners.add(record.user_id)
    pushLastActivity(user, record.created_at, record.updated_at)
    pushAiSample(context, {
      source: 'note',
      userId: record.user_id,
      courseId,
      courseTitle: context.courses.get(courseId)?.courseTitle,
      text: stringifySampleContent([record.note_title, record.note_content].filter(Boolean).join('\n')),
      signals: {
        autoGenerated: record.is_auto_generated,
        sourceType: record.source_type,
      },
    })
  })
}
