import type { ReportsAnalyticsNotes } from '../../../types/reports-analytics.types'
import { buildBreakdown, calculatePercentage, incrementMap } from '../reports-analytics.helpers'
import { getCourseIdFromLesson } from './get-course-id-from-lesson'
import { shouldIncludeEngagementRecord } from './should-include-engagement-record'
import type { BuildContext } from './build-context'
import type { LessonNoteRecord } from './lesson-note-record'

export function buildNotes(context: BuildContext, notes: LessonNoteRecord[], totalUsers: number): ReportsAnalyticsNotes {
  const usersWithNotes = new Set<string>()
  const byCourse = new Map<string, number>()
  const courseLabels = new Map<string, string>()
  let totalNotes = 0
  let autoGenerated = 0

  notes.forEach((note) => {
    const courseId = getCourseIdFromLesson(note.course_lessons)
    if (
      !shouldIncludeEngagementRecord(context, note.user_id, courseId, [
        note.created_at,
        note.updated_at,
      ])
    ) {
      return
    }

    const course = context.courses.get(courseId)
    totalNotes += 1
    usersWithNotes.add(note.user_id)
    if (note.is_auto_generated || note.source_type === 'auto') autoGenerated += 1
    incrementMap(byCourse, courseId)
    courseLabels.set(courseId, course?.courseTitle || courseId)
  })

  return {
    totalNotes,
    usersWithNotes: usersWithNotes.size,
    adoptionRate: calculatePercentage(usersWithNotes.size, totalUsers),
    autoGenerated,
    manual: Math.max(totalNotes - autoGenerated, 0),
    byCourse: buildBreakdown(byCourse, totalNotes, courseLabels),
  }
}
