export const SELECT_COLUMNS = {
  admin_dashboard_layouts: 'id, user_id, name, layout_config, is_default, created_at, updated_at',
  admin_dashboard_preferences: 'id, user_id, activity_period, growth_chart_metrics, created_at, updated_at',
  adopcion_genai: 'id, pais, indice_aipi, fuente, fecha_fuente',
  ai_moderation_pending_review: 'categories, confidence_score, content_id, content_preview, content_type, created_at, email, is_flagged, log_id, reasoning, user_id, user_warning_count, username',
  audit_logs: 'id, user_id, admin_user_id, action, table_name, record_id, old_values, new_values, ip_address, user_agent, created_at',
  bulk_invite_links: 'id, organization_id, created_by, token, name, max_uses, current_uses, role, expires_at, status, metadata, created_at, updated_at',
  calendar_integrations: 'id, user_id, provider, access_token, refresh_token, expires_at, scope, metadata, created_at, updated_at',
  certificate_templates: 'id, organization_id, name, description, design_config, is_default, is_active, created_at, updated_at',
  communities: '*',
  community_comments: 'id, post_id, community_id, user_id, content, parent_comment_id, is_deleted, created_at',
  community_members: '*',
  community_post_reports: '*',
  content_translations: 'id, entity_type, entity_id, language_code, translations, created_at, updated_at, created_by',
  course_modules: 'module_id, module_title, module_description, module_order_index, module_duration_minutes, is_required, is_published, created_at, updated_at, course_id',
  courses: 'id, title, description, category, level, instructor_id, duration_total_minutes, thumbnail_url, slug, is_active, created_at, updated_at, price, average_rating, student_count, review_count, learning_objectives, approval_status, approved_by, approved_at, rejection_reason',
  courses_staging: 'id, course_id, source_slug, artifact_id, payload, submitted_at, updated_at, status, is_update, reviewed_by, reviewed_at, rejection_reason',
  dashboard_layouts: 'id, organization_id, name, layout_config, is_default, created_at, updated_at',
  hierarchy_chat_participants: 'id, chat_id, user_id, organization_id, is_active, joined_at, left_at, last_read_at, unread_count, created_at, updated_at',
  hierarchy_chats: 'id, organization_id, chat_type, entity_type, entity_id, level_role, name, description, is_active, created_at, updated_at, last_message_at',
  lesson_activities: 'activity_id, activity_title, activity_description, activity_type, activity_content, ai_prompts, activity_order_index, is_required, created_at, lesson_id, estimated_time_minutes, activity_schema_version, activity_config, requires_soflia_validation, external_tool_key',
  lesson_checkpoints: 'checkpoint_id, checkpoint_time_seconds, checkpoint_label, checkpoint_description, is_required_completion, checkpoint_order_index, created_at, lesson_id',
  lesson_materials: 'material_id, material_title, material_description, material_type, file_url, external_url, content_data, material_order_index, is_downloadable, created_at, lesson_id, estimated_time_minutes',
  lesson_tracking: 'id, user_id, lesson_id, session_id, plan_id, status, started_at, start_trigger, video_started_at, video_ended_at, lia_first_message_at, lia_last_message_at, post_content_start_at, last_activity_at, next_analysis_at, completed_at, end_trigger, t_lesson_minutes, t_video_minutes, t_materials_minutes, t_restante_minutes, created_at, updated_at, organization_id, video_checkpoint_seconds, video_max_seconds, video_total_duration_seconds, video_playback_rate',
  lia_activity_performance: 'activity_id, activity_title, activity_type, avg_attempts, avg_time_seconds, completed_count, completion_rate_percentage, course_id, course_title, help_needed_count, total_attempts, unique_users',
  lia_common_questions: 'activity_id, best_response, best_response_rating, context_type, created_at, first_asked_at, last_asked_at, lesson_id, question_id, question_text, times_asked, updated_at',
  lia_conversation_analytics: 'avg_response_time_ms, context_type, conversation_completed, conversation_id, course_id, course_title, duration_seconds, ended_at, lesson_id, lesson_title, module_id, module_title, primary_model, started_at, total_cost_usd, total_lia_messages, total_messages, total_tokens, total_user_messages, user_abandoned, user_avatar, user_email, user_id, user_name',
  lia_conversations: 'conversation_id, user_id, context_type, course_id, module_id, lesson_id, activity_id, started_at, ended_at, duration_seconds, total_messages, total_user_messages, total_lia_messages, conversation_completed, user_abandoned, device_type, browser, ip_address, created_at, updated_at, conversation_title, organization_id',
  lia_personalization_settings: 'id, user_id, base_style, is_friendly, is_enthusiastic, custom_instructions, nickname, voice_enabled, dictation_enabled, created_at, updated_at',
  notification_settings: 'id, organization_id, event_type, enabled, channels, template, created_at, updated_at',
  news: '*',
  oauth_accounts: 'id, user_id, provider, provider_account_id, access_token, refresh_token, token_expires_at, scope, token_type, created_at, updated_at',
  organization_nodes: 'id, structure_id, organization_id, parent_id, name, type, code, manager_id, properties, path, depth, position, created_at, updated_at',
  organization_regions: 'id, organization_id, name, description, code, is_active, metadata, created_by, created_at, updated_at, address, city, state, country, postal_code, latitude, longitude, phone, email, manager_id, logo_url, banner_url',
  organization_structures: 'id, organization_id, name, description, template, metadata, is_default, created_by, created_at, updated_at',
  organization_subscriptions: '*',
  organization_teams: 'id, organization_id, zone_id, name, description, code, max_members, is_active, metadata, created_by, created_at, updated_at, address, city, state, country, postal_code, latitude, longitude, phone, email, leader_id, target_goal, monthly_target, logo_url, banner_url',
  organization_zones: 'id, organization_id, region_id, name, description, code, is_active, metadata, created_by, created_at, updated_at, address, city, state, country, postal_code, latitude, longitude, phone, email, manager_id, logo_url, banner_url',
  organizations: 'billing_cycle, brand_banner_url, brand_color_accent, brand_color_primary, brand_color_secondary, brand_favicon_url, brand_font_family, brand_logo_url, company_country, company_mission, company_size, company_type, contact_email, contact_phone, created_at, description, google_login_enabled, id, industry, is_active, login_styles, logo_url, max_users, microsoft_login_enabled, name, panel_styles, selected_theme, show_navbar_name, slug, subscription_end_date, subscription_plan, subscription_start_date, subscription_status, updated_at, user_dashboard_styles, website_url',
  preguntas: 'id, codigo, section, bloque, area_id, exclusivo_rol_id, texto, tipo, opciones, locale, peso, escala, scoring, created_at, respuesta_correcta, dimension, exclusivo_nivel_id, dificultad',
  reportes_con_usuario: 'admin_asignado, admin_nombre, categoria, comportamiento_esperado, created_at, descripcion, display_name, email, estado, id, metadata, navegador, notas_admin, pagina_url, pasos_reproducir, pathname, prioridad, resuelto_at, screen_resolution, screenshot_url, titulo, updated_at, user_agent, user_id, user_role, username',
  scorm_attempts: 'id, user_id, package_id, attempt_number, lesson_status, lesson_location, credit, entry, exit_type, score_raw, score_min, score_max, score_scaled, total_time, session_time, suspend_data, started_at, last_accessed_at, completed_at',
  scorm_packages: 'id, organization_id, course_id, title, description, version, manifest_data, entry_point, storage_path, file_size, status, created_by, created_at, updated_at',
  skills: 'skill_id, name, slug, description, category, icon_url, icon_type, icon_name, color, level, is_active, display_order, created_at, updated_at',
  soflia_dialogue_evaluations: 'evaluation_id, session_id, turn_id, model_name, overall_score, decision, recommended_next_state, criteria_met, criteria_missing, dimension_scores, flags, feedback_for_tutor, backend_notes, evidence_quotes, raw_payload, created_at',
  soflia_dialogue_results: 'result_id, session_id, activity_id, user_id, enrollment_id, activity_result, score, criteria_met, criteria_missing, student_feedback, instructor_summary, analytics_tags, payload, created_at',
  soflia_dialogue_sessions: 'session_id, activity_id, course_id, lesson_id, enrollment_id, organization_id, user_id, state, current_score, turns_count, hints_used, low_evidence_turns, criteria_met, criteria_missing, activity_config_snapshot, schema_version, rubric_version, prompt_version, started_at, completed_at, updated_at, active_seconds, active_seconds_reason, active_seconds_updated_at',
  soflia_dialogue_turns: 'turn_id, session_id, role, content, turn_number, client_turn_id, state_before, state_after, metadata, created_at',
  study_sessions: 'actual_duration_minutes, break_duration_minutes, calendar_conflict_checked, calendar_provider, calendar_synced_at, completed_at, completion_method, course_complexity, course_id, created_at, description, due_date, duration_minutes, end_time, external_event_id, focus_area, id, is_ai_generated, lesson_id, lesson_min_time_minutes, lia_suggested, metrics, notes, organization_id, plan_id, recurrence, rescheduled_from, self_evaluation, session_type, start_time, started_at, status, streak_day, title, updated_at, user_id, was_rescheduled',
  subscriptions: 'subscription_id, subscription_type, subscription_status, price_cents, start_date, end_date, next_billing_date, created_at, updated_at, user_id, course_id, plan_id',
  user_calendar_events: 'id, user_id, title, description, start_time, end_time, location, is_all_day, provider, source, google_event_id, microsoft_event_id, color, created_at, updated_at',
  user_group_members: '*',
  user_groups: '*',
  user_invitations: 'id, email, token, role, organization_id, status, expires_at, created_at, created_by, accepted_at, metadata',
  user_perfil: 'id, user_id, cargo_titulo, rol_id, nivel_id, area_id, relacion_id, tamano_id, sector_id, pais, creado_en, actualizado_en, dificultad_id, uso_ia_respuesta',
  user_streaks: 'user_id, current_streak, longest_streak, last_session_date, total_sessions_completed, total_study_minutes, total_sessions_missed, total_sessions_rescheduled, weekly_sessions_completed, weekly_study_minutes, week_start_date, monthly_sessions_completed, monthly_study_minutes, month_start_date, created_at, updated_at, id, organization_id',
  user_tour_progress: 'id, user_id, tour_id, completed_at, skipped_at, step_reached, created_at, updated_at',
  // OJO: la columna `type_rol` fue eliminada de la base pero seguía listada
  // aquí, y PostgREST rechaza el SELECT entero con "column users.type_rol does
  // not exist". Eso dejaba rotos el update y el delete de usuarios del panel de
  // administración, que usan esta constante.
  users: 'ban_reason, banned_at, bio, platform_role, country_code, created_at, date_of_birth, display_name, email, email_verified, email_verified_at, first_name, gender, id, is_banned, last_activity_at, last_login_at, last_name, location, notification_community_updates, notification_course_updates, notification_email, notification_marketing, notification_push, phone, profile_picture_url, signature_name, signature_url, updated_at, username',
} as const
