import type { StudySessionRow } from './study-sessions.fields'

export type StudySessionInsert = {
  actual_duration_minutes?: StudySessionRow['actual_duration_minutes']
  break_duration_minutes?: StudySessionRow['break_duration_minutes']
  calendar_conflict_checked?: StudySessionRow['calendar_conflict_checked']
  calendar_provider?: StudySessionRow['calendar_provider']
  calendar_synced_at?: StudySessionRow['calendar_synced_at']
  completed_at?: StudySessionRow['completed_at']
  completion_method?: StudySessionRow['completion_method']
  course_complexity?: StudySessionRow['course_complexity']
  course_id?: StudySessionRow['course_id']
  created_at?: StudySessionRow['created_at']
  description?: StudySessionRow['description']
  due_date?: StudySessionRow['due_date']
  duration_minutes?: StudySessionRow['duration_minutes']
  end_time: StudySessionRow['end_time']
  external_event_id?: StudySessionRow['external_event_id']
  focus_area?: StudySessionRow['focus_area']
  id?: StudySessionRow['id']
  is_ai_generated?: StudySessionRow['is_ai_generated']
  lesson_id?: StudySessionRow['lesson_id']
  lesson_min_time_minutes?: StudySessionRow['lesson_min_time_minutes']
  lia_suggested?: StudySessionRow['lia_suggested']
  metrics?: StudySessionRow['metrics']
  notes?: StudySessionRow['notes']
  organization_id?: StudySessionRow['organization_id']
  plan_id?: StudySessionRow['plan_id']
  recurrence?: StudySessionRow['recurrence']
  rescheduled_from?: StudySessionRow['rescheduled_from']
  self_evaluation?: StudySessionRow['self_evaluation']
  session_type?: StudySessionRow['session_type']
  start_time: StudySessionRow['start_time']
  started_at?: StudySessionRow['started_at']
  status?: StudySessionRow['status']
  streak_day?: StudySessionRow['streak_day']
  title: StudySessionRow['title']
  updated_at?: StudySessionRow['updated_at']
  user_id: StudySessionRow['user_id']
  was_rescheduled?: StudySessionRow['was_rescheduled']
}

export type StudySessionUpdate = Partial<StudySessionRow>
