import { describe, expect, it } from 'vitest';

import { buildNotePdfDefinition } from '../shared/notes-pdf-definition.service';
import { parseNoteHtmlToPdfBlocks } from '../shared/notes-pdf-content-parser.service';
import { generateNotePdfMakeBuffer } from '../shared/notes-pdf-pdfmake.service';
import type { NoteDraft } from '../types';

const labels = {
  generatedBy: 'Generated by SofLIA',
  page: 'Page',
  tags: 'Tags:',
  untitled: 'Untitled note',
};

function buildLongTranscript(paragraphCount: number): string {
  return Array.from({ length: paragraphCount }, (_, index) => {
    const minute = String(index).padStart(2, '0');

    return `<p>[${minute}:00] This is a long transcript paragraph with enough content to wrap naturally in the generated PDF. It should keep reading order, preserve page flow, and never depend on manual coordinates for text placement.</p>`;
  }).join('');
}

describe('parseNoteHtmlToPdfBlocks', () => {
  it('separates transcript timestamps that arrive in a single block', () => {
    const blocks = parseNoteHtmlToPdfBlocks(
      '<div>[00:00] Intro text. [00:45] Second section. [02:00] Third section.</div>'
    );

    expect(blocks).toEqual([
      expect.objectContaining({ type: 'paragraph' }),
      expect.objectContaining({ type: 'paragraph' }),
      expect.objectContaining({ type: 'paragraph' }),
    ]);
    expect(blocks.map((block) => ('runs' in block ? block.runs[0]?.text : ''))).toEqual([
      '[00:00] Intro text.',
      '[00:45] Second section.',
      '[02:00] Third section.',
    ]);
  });

  it('keeps headings, lists, valid links and inline emphasis', () => {
    const blocks = parseNoteHtmlToPdfBlocks(`
      <h1>Workshop summary</h1>
      <p>Read <strong>official</strong> <a href="sof-lia.com/resource">resource</a></p>
      <ul><li>First item</li><li><em>Second</em> item</li></ul>
    `);

    expect(blocks).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ level: 1, type: 'heading' }),
        expect.objectContaining({ type: 'paragraph' }),
        expect.objectContaining({ ordered: false, type: 'list' }),
      ])
    );

    const paragraph = blocks.find((block) => block.type === 'paragraph');
    expect(paragraph && 'runs' in paragraph ? paragraph.runs : []).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ bold: true, text: 'official' }),
        expect.objectContaining({
          link: 'https://sof-lia.com/resource',
          text: 'resource',
        }),
      ])
    );
  });

  it('drops scripts, styles and unsafe links', () => {
    const blocks = parseNoteHtmlToPdfBlocks(`
      <p>Safe <a href="javascript:alert(1)">link text</a></p>
      <script>alert('no')</script>
      <style>body { display: none; }</style>
    `);
    const serialized = JSON.stringify(blocks);

    expect(serialized).not.toContain('script');
    expect(serialized).not.toContain('display: none');
    expect(serialized).not.toContain('javascript:');
    expect(serialized).toContain('link text');
  });
});

describe('buildNotePdfDefinition', () => {
  it('builds a declarative document definition with footer, lists and links', () => {
    const definition = buildNotePdfDefinition(
      {
        content: `
          <h2>Next steps</h2>
          <ol><li>Review notes</li><li>Open <a href="https://sof-lia.com">SofLIA</a></li></ol>
        `,
        tags: ['workshop', 'notes'],
        title: 'Learning note',
      },
      {
        generatedAt: new Date('2026-04-29T16:56:00.000Z'),
        labels,
        locale: 'en-US',
      }
    );
    const serialized = JSON.stringify(definition);

    expect(definition.pageSize).toBe('A4');
    expect(definition.footer).toBeTypeOf('function');
    expect(serialized).toContain('"ol"');
    expect(serialized).toContain('"https://sof-lia.com"');
    expect(serialized).toContain('Tags:');
    expect(serialized).not.toContain('<h2>');
  });
});

describe('generateNotePdfMakeBuffer', () => {
  it('generates a valid multi-page PDF buffer for long notes', async () => {
    const noteDraft: NoteDraft = {
      content: buildLongTranscript(80),
      tags: ['transcript', 'automatic'],
      title: 'Transcript: ChatGPT vs. Atlas',
    };
    const buffer = await generateNotePdfMakeBuffer(noteDraft, {
      generatedAt: new Date('2026-04-29T16:56:00.000Z'),
      labels,
      locale: 'en-US',
    });
    const pdfText = buffer.toString('latin1');
    const pageCount = (pdfText.match(/\/Type\s*\/Page\b/g) || []).length;

    expect(pdfText.startsWith('%PDF')).toBe(true);
    expect(pageCount).toBeGreaterThan(1);
    expect(pdfText).not.toContain('<script>');
  });
});
