'use client';

import { useStudyPlannerCourseSelectionFlow } from '../../hooks/useStudyPlannerCourseSelectionFlow';
import { useStudyPlannerCalendarUiFlow } from '../../hooks/useStudyPlannerCalendarUiFlow';
import { useStudyPlanPersistence } from '../../hooks/useStudyPlanPersistence';
import { useStudyPlannerCalendarActions } from './useStudyPlannerCalendarActions';
import type { UseStudyPlannerLIAPlanningFlowParams } from './useStudyPlannerLIAPlanningFlow.types';

export function useStudyPlannerLIAPlanningFlow({
  assignedCourses,
  availableCourses,
  calendarSkipped,
  connectedCalendar,
  conversationHistory,
  getAnalyzeCalendarAndSuggest,
  isAudioEnabled,
  isProcessing,
  onDuplicatePlan,
  pendingLessonsRef,
  pendingLessonsWithNames,
  savedLessonDistribution,
  savedPlanId,
  savedTargetDate,
  selectedCourseIds,
  setCalendarSkipped,
  setConnectedCalendar,
  setConversationHistory,
  setCurrentMonth,
  setAvailableCourses,
  setHasAskedApproach,
  setHasAskedTargetDate,
  setHasConfiguredCalendars,
  setIsConnectingCalendar,
  setIsLoadingCourses,
  setIsProcessing,
  setIsVisible,
  setPendingLessonsWithNames,
  setSavedCalendarData,
  setSavedLessonDistribution,
  setSavedPlanId,
  setSavedTargetDate,
  setSavedTotalLessons,
  setSelectedCourseIds,
  setSelectedDate,
  setShowApproachButtons,
  setShowApproachModal,
  setShowCalendarConfig,
  setShowCalendarModal,
  setShowConversation,
  setShowCourseSelector,
  setShowDateModal,
  setStudyApproach,
  setTargetDate,
  setUserContext,
  speakText,
  stopAllAudio,
  studyApproach,
  targetDate,
  userContext,
  userId,
}: UseStudyPlannerLIAPlanningFlowParams) {
  const { saveStudyPlan: persistStudyPlan } = useStudyPlanPersistence({
    availableCourses,
    connectedCalendar,
    isAudioEnabled,
    savedLessonDistribution,
    savedPlanId,
    savedTargetDate,
    selectedCourseIds,
    setConnectedCalendar,
    setConversationHistory,
    setIsProcessing,
    setSavedLessonDistribution,
    setSavedPlanId,
    speakText,
    studyApproach,
    userType: userContext?.userType === 'b2b' ? 'b2b' : null,
    onDuplicatePlan,
  });

  const calendarUiFlow = useStudyPlannerCalendarUiFlow({
    assignedCourses,
    calendarSkipped,
    connectedCalendar,
    conversationHistory,
    getAnalyzeCalendarAndSuggest,
    isAudioEnabled,
    setConnectedCalendar,
    setConversationHistory,
    setCurrentMonth,
    setHasAskedTargetDate,
    setHasConfiguredCalendars,
    setIsConnectingCalendar,
    setIsProcessing,
    setSelectedDate,
    setShowApproachButtons,
    setShowApproachModal,
    setShowCalendarConfig,
    setShowCalendarModal,
    setShowDateModal,
    setStudyApproach,
    setTargetDate,
    speakText,
    studyApproach,
    targetDate,
    userContext,
  });

  const courseSelectionFlow = useStudyPlannerCourseSelectionFlow({
    assignedCourses,
    availableCourses,
    isAudioEnabled,
    selectedCourseIds,
    setAvailableCourses,
    setConversationHistory,
    setHasAskedApproach,
    setIsLoadingCourses,
    setIsProcessing,
    setIsVisible,
    setSelectedCourseIds,
    setShowApproachButtons,
    setShowConversation,
    setShowCourseSelector,
    speakText,
    stopAllAudio,
  });

  const calendarActions = useStudyPlannerCalendarActions({
    availableCourses,
    assignedCourses,
    isAudioEnabled,
    isProcessing,
    pendingLessonsRef,
    pendingLessonsWithNames,
    selectedCourseIds,
    setCalendarSkipped,
    setConnectedCalendar,
    setConversationHistory,
    setIsConnectingCalendar,
    setIsProcessing,
    setPendingLessonsWithNames,
    setSavedCalendarData,
    setSavedLessonDistribution,
    setSavedTargetDate,
    setSavedTotalLessons,
    setSelectedCourseIds,
    setShowCalendarModal,
    setTargetDate,
    setUserContext,
    speakText,
    studyApproach,
    targetDate,
    userContext,
    userId,
  });

  return {
    ...calendarUiFlow,
    ...courseSelectionFlow,
    ...calendarActions,
    persistStudyPlan,
  };
}
