'use client';

import { useEffect } from 'react';
import { useStudyPlannerMessageHandler } from '../../hooks/useStudyPlannerMessageHandler';
import { useStudyPlannerVoiceQuestionHandler } from '../../hooks/useStudyPlannerVoiceQuestionHandler';
import { useStudyPlannerNavigationHandlers } from './useStudyPlannerNavigationHandlers';
import type { UseStudyPlannerLIAInteractionHandlersParams } from './useStudyPlannerLIAInteractionHandlers.types';

export function useStudyPlannerLIAInteractionHandlers({
  availableCourses,
  assignedCourses,
  clearStudyPlannerSessionStorage,
  connectedCalendar,
  conversationHistory,
  conversationHistoryRef,
  currentStep,
  executePlanSave,
  handleApproachSelection,
  handleComplete,
  handleTargetDateResponse,
  handleVoiceQuestionRef,
  hasAskedApproach,
  hasAskedTargetDate,
  hasShownFinalSummary,
  hasUserInteracted,
  isAudioEnabled,
  isProcessing,
  lastVoiceQuestionRef,
  liaConversationId,
  liaData,
  loadUserCourses,
  orgSlug,
  pendingLessonsRef,
  processingRef,
  router,
  savedCalendarData,
  savedLessonDistribution,
  savedPlanId,
  savedTargetDate,
  savedTotalLessons,
  scheduleStudyPlannerRedirect,
  selectedCourseIds,
  setConversationHistory,
  setCurrentStep,
  setHasShownFinalSummary,
  setHasUserInteracted,
  setIsAudioEnabled,
  setIsProcessing,
  setLiaConversationId,
  setSavedLessonDistribution,
  setSavedPlanId,
  setStudyApproach,
  setTargetDate,
  showDateModal,
  speakText,
  stopAllAudio,
  studyApproach,
  targetDate,
  userContext,
}: UseStudyPlannerLIAInteractionHandlersParams) {
  const navigationHandlers = useStudyPlannerNavigationHandlers({
    clearStudyPlannerSessionStorage,
    currentStep,
    handleApproachSelection,
    handleComplete,
    handleTargetDateResponse,
    hasUserInteracted,
    isAudioEnabled,
    loadUserCourses: () => {
      void loadUserCourses();
    },
    orgSlug,
    persistStudyPlan: executePlanSave,
    router,
    scheduleStudyPlannerRedirect,
    setCurrentStep,
    setHasUserInteracted,
    setIsAudioEnabled,
    setIsProcessing,
    setStudyApproach,
    setTargetDate,
    speakText,
    stopAllAudio,
  });

  const { handleVoiceQuestion } = useStudyPlannerVoiceQuestionHandler({
    assignedCourses,
    connectedCalendar,
    conversationHistoryRef,
    getLessonsForPrompt: liaData.getLessonsForPrompt,
    hasAskedApproach,
    hasAskedTargetDate,
    isAudioEnabled,
    lastVoiceQuestionRef,
    lessons: liaData.lessons,
    lessonsAreReady: liaData.isReady,
    onCourseSelectorRequested: navigationHandlers.handleVoiceCourseSelectorRequest,
    onStudyApproachDetected: navigationHandlers.handleVoiceStudyApproachDetected,
    onTargetDateDetected: navigationHandlers.handleVoiceTargetDateDetected,
    pendingLessonsRef,
    processingRef,
    savedLessonDistribution,
    selectedCourseIds,
    setConversationHistory,
    setIsProcessing,
    showDateModal,
    speakText,
    stopAllAudio,
    studyApproach,
    targetDate,
    totalPendingLessons: liaData.totalPending || pendingLessonsRef.current.length,
    userContext,
  });

  useEffect(() => {
    handleVoiceQuestionRef.current = handleVoiceQuestion;
  }, [handleVoiceQuestion, handleVoiceQuestionRef]);

  const { handleSendMessage } = useStudyPlannerMessageHandler({
    availableCourses,
    assignedCourses,
    connectedCalendar,
    conversationHistory,
    executeFinalPlanSave: navigationHandlers.executeFinalPlanSave,
    hasAskedApproach,
    hasAskedTargetDate,
    hasShownFinalSummary,
    isAudioEnabled,
    isProcessing,
    liaConversationId,
    liaData,
    loadUserCourses: () => {
      void loadUserCourses();
    },
    onStudyApproachResponse: navigationHandlers.handleStudyApproachResponse,
    onTargetDateResponse: handleTargetDateResponse,
    pendingLessonsRef,
    savedCalendarData,
    savedLessonDistribution,
    savedPlanId,
    savedTargetDate,
    savedTotalLessons,
    selectedCourseIds,
    setConversationHistory,
    setHasShownFinalSummary,
    setIsProcessing,
    setLiaConversationId,
    setSavedLessonDistribution,
    setSavedPlanId,
    setStudyApproach,
    setTargetDate,
    showDateModal,
    speakText,
    stopAllAudio,
    studyApproach,
    targetDate,
    userContext,
  });

  return {
    ...navigationHandlers,
    handleSendMessage,
    handleVoiceQuestion,
  };
}
