export const SOFLIA_ADMIN_COLORS = {
  primary: '#0A2540',
  accent: '#00D4B3',
  accentLight: '#00E5C4',
  info: '#3B82F6',
  success: '#10B981',
  warning: '#F59E0B',
  error: '#EF4444',
  pending: '#F97316',
  purple: '#8B5CF6',
  rose: '#EC4899',
  teal: '#14B8A6',
  cyan: '#06B6D4',
  lime: '#84CC16',
  bgPrimary: '#0F1419',
  bgSecondary: '#1E2329',
  bgTertiary: '#0A0D12',
  grayLight: '#E9ECEF',
  grayMedium: '#6C757D',
  white: '#FFFFFF',
  surfaceDark: '#1a1f2e',
  textDark: '#333333',
  modalBackdrop: 'rgba(0, 0, 0, 0.6)',
} as const

export const SOFLIA_ADMIN_CHART_COLORS = [
  SOFLIA_ADMIN_COLORS.info,
  SOFLIA_ADMIN_COLORS.success,
  SOFLIA_ADMIN_COLORS.warning,
  SOFLIA_ADMIN_COLORS.error,
  SOFLIA_ADMIN_COLORS.purple,
  SOFLIA_ADMIN_COLORS.rose,
  SOFLIA_ADMIN_COLORS.teal,
  SOFLIA_ADMIN_COLORS.pending,
  SOFLIA_ADMIN_COLORS.cyan,
  SOFLIA_ADMIN_COLORS.lime,
] as const
