export const SOFLIA_ADMIN_COLORS = {
  primary: 'var(--color-primary)',
  accent: 'var(--color-accent)',
  accentLight: 'var(--color-legacy-00e5c4)',
  info: 'var(--color-info)',
  success: 'var(--color-success)',
  warning: 'var(--color-warning)',
  error: 'var(--color-error)',
  pending: 'var(--color-legacy-f97316)',
  purple: 'var(--color-secondary)',
  rose: 'var(--color-legacy-ec4899)',
  teal: 'var(--color-legacy-14b8a6)',
  cyan: 'var(--color-legacy-06b6d4)',
  lime: 'var(--color-legacy-84cc16)',
  bgPrimary: 'var(--color-bg-dark)',
  bgSecondary: 'var(--color-gray-800)',
  bgTertiary: 'var(--color-gray-950)',
  grayLight: 'var(--color-gray-200)',
  grayMedium: 'var(--color-gray-500)',
  white: 'var(--color-bg-light)',
  surfaceDark: 'var(--color-legacy-1a1f2e)',
  textDark: 'var(--color-legacy-333333)',
  modalBackdrop: 'rgba(0, 0, 0, 0.6)',
} as const

export const SOFLIA_ADMIN_CHART_COLORS = [
  SOFLIA_ADMIN_COLORS.info,
  SOFLIA_ADMIN_COLORS.success,
  SOFLIA_ADMIN_COLORS.warning,
  SOFLIA_ADMIN_COLORS.error,
  SOFLIA_ADMIN_COLORS.purple,
  SOFLIA_ADMIN_COLORS.rose,
  SOFLIA_ADMIN_COLORS.teal,
  SOFLIA_ADMIN_COLORS.pending,
  SOFLIA_ADMIN_COLORS.cyan,
  SOFLIA_ADMIN_COLORS.lime,
] as const
