-- Lesson auto-notes generated by SofLIA after all required lesson quizzes pass.
--
-- Add an explicit source_type value and enforce a single generated lesson note
-- per user/enrollment/lesson. The partial unique index keeps manual/chat/import
-- notes unrestricted while making the automatic flow idempotent.

begin;

alter table public.user_lesson_notes
  drop constraint if exists user_lesson_notes_source_type_check;

alter table public.user_lesson_notes
  add constraint user_lesson_notes_source_type_check
  check (
    source_type::text = any (
      array[
        'manual'::text,
        'chat'::text,
        'import'::text,
        'lesson_auto_note'::text
      ]
    )
  );

create unique index if not exists idx_user_lesson_notes_auto_lesson_unique
  on public.user_lesson_notes (
    user_id,
    coalesce(enrollment_id, '00000000-0000-0000-0000-000000000000'::uuid),
    lesson_id
  )
  where source_type = 'lesson_auto_note'
    and is_auto_generated is true;

comment on index public.idx_user_lesson_notes_auto_lesson_unique is
  'Ensures SofLIA creates at most one automatic lesson note per user/enrollment/lesson.';

commit;
