-- Course compendium notes ("libreta") generated by SofLIA when a user
-- completes a course (100% progress).
--
-- Compendium rows are course-scoped: lesson_id is null and course_id is set.
-- Every other note type keeps requiring lesson_id (back-compat enforced by
-- user_lesson_notes_scope_check). The partial unique index makes the
-- automatic generation idempotent (one compendium per user/enrollment/course).

begin;

alter table public.user_lesson_notes
  alter column lesson_id drop not null;

alter table public.user_lesson_notes
  add column if not exists course_id uuid
    references public.courses(id) on delete cascade;

alter table public.user_lesson_notes
  drop constraint if exists user_lesson_notes_source_type_check;

alter table public.user_lesson_notes
  add constraint user_lesson_notes_source_type_check
  check (
    source_type::text = any (
      array[
        'manual'::text,
        'chat'::text,
        'import'::text,
        'lesson_auto_note'::text,
        'course_compendium'::text
      ]
    )
  );

alter table public.user_lesson_notes
  drop constraint if exists user_lesson_notes_scope_check;

alter table public.user_lesson_notes
  add constraint user_lesson_notes_scope_check
  check (
    (
      source_type = 'course_compendium'
      and course_id is not null
      and lesson_id is null
    )
    or (
      source_type is distinct from 'course_compendium'
      and lesson_id is not null
    )
  );

create unique index if not exists idx_user_lesson_notes_compendium_unique
  on public.user_lesson_notes (
    user_id,
    coalesce(enrollment_id, '00000000-0000-0000-0000-000000000000'::uuid),
    course_id
  )
  where source_type = 'course_compendium'
    and is_auto_generated is true;

comment on index public.idx_user_lesson_notes_compendium_unique is
  'Ensures SofLIA creates at most one course compendium per user/enrollment/course.';

create index if not exists idx_user_lesson_notes_course_id
  on public.user_lesson_notes (course_id)
  where course_id is not null;

commit;
