import type { DeleteTableConfig } from './delete-user.config'

export const USER_SIMPLE_DELETE_TABLES: DeleteTableConfig[] = [
  { tableName: 'lia_user_feedback' },
  { tableName: 'lia_activity_completions' },
  { tableName: 'lia_conversations' },
  { tableName: 'user_course_certificates' },
  { tableName: 'user_quiz_submissions' },
  { tableName: 'lesson_tracking' },
  { tableName: 'user_lesson_progress' },
  { tableName: 'daily_progress' },
  { tableName: 'user_lesson_notes' },
  { tableName: 'study_sessions' },
  { tableName: 'calendar_sync_history' },
  { tableName: 'study_plans' },
  { tableName: 'study_preferences' },
  { tableName: 'user_streaks' },
  { tableName: 'organization_course_assignments' },
  { tableName: 'organization_course_assignments', column: 'assigned_by' },
  { tableName: 'organization_course_purchases', column: 'purchased_by' },
  { tableName: 'course_question_reactions' },
  { tableName: 'course_question_responses' },
  { tableName: 'course_questions' },
  { tableName: 'course_reviews' },
  { tableName: 'lesson_feedback' },
  { tableName: 'notification_email_queue' },
  { tableName: 'notification_push_subscriptions' },
  { tableName: 'notification_stats' },
  { tableName: 'user_notification_preferences' },
  { tableName: 'user_notifications' },
  { tableName: 'user_calendar_events' },
  { tableName: 'calendar_subscription_tokens' },
  { tableName: 'calendar_integrations' },
  { tableName: 'transactions' },
  { tableName: 'subscriptions' },
  { tableName: 'payment_methods' },
  { tableName: 'oauth_accounts' },
  { tableName: 'password_reset_tokens' },
  { tableName: 'refresh_tokens' },
  { tableName: 'user_session' },
  { tableName: 'reportes_problemas' },
  { tableName: 'user_perfil' },
  { tableName: 'user_activity_log' },
  { tableName: 'user_tour_progress' },
  { tableName: 'user_warnings' },
  { tableName: 'ai_moderation_logs' },
  { tableName: 'audit_logs' },
  { tableName: 'audit_logs', column: 'admin_user_id' },
  { tableName: 'user_favorite_tools' },
  { tableName: 'hierarchy_chat_messages', column: 'sender_id' },
  { tableName: 'hierarchy_chat_participants' },
  { tableName: 'hierarchy_course_assignments', column: 'assigned_by' },
  { tableName: 'organization_node_users' },
  { tableName: 'organization_join_requests' },
  { tableName: 'lia_personalization_settings' },
  { tableName: 'bulk_invite_links', column: 'created_by' },
  { tableName: 'bulk_invite_registrations' },
  { tableName: 'user_invitations', column: 'created_by' },
  { tableName: 'user_course_enrollments' },
  { tableName: 'organization_users' },
]
