export interface DeleteTableConfig {
  tableName: string
  column?: string
}

export const USER_SIMPLE_DELETE_TABLES: DeleteTableConfig[] = [
  { tableName: 'lia_user_feedback' },
  { tableName: 'lia_activity_completions' },
  { tableName: 'lia_conversations' },
  { tableName: 'user_course_certificates' },
  { tableName: 'user_quiz_submissions' },
  { tableName: 'lesson_tracking' },
  { tableName: 'user_lesson_progress' },
  { tableName: 'daily_progress' },
  { tableName: 'user_lesson_notes' },
  { tableName: 'study_sessions' },
  { tableName: 'calendar_sync_history' },
  { tableName: 'study_plans' },
  { tableName: 'organization_course_assignments' },
  { tableName: 'organization_course_assignments', column: 'assigned_by' },
  { tableName: 'course_question_reactions' },
  { tableName: 'course_question_responses' },
  { tableName: 'course_questions' },
  { tableName: 'course_reviews' },
  { tableName: 'lesson_feedback' },
  { tableName: 'notification_email_queue' },
  { tableName: 'notification_push_subscriptions' },
  { tableName: 'notification_stats' },
  { tableName: 'user_notification_preferences' },
  { tableName: 'user_notifications' },
  { tableName: 'user_calendar_events' },
  { tableName: 'calendar_subscription_tokens' },
  { tableName: 'calendar_integrations' },
  { tableName: 'transactions' },
  { tableName: 'subscriptions' },
  { tableName: 'payment_methods' },
  { tableName: 'oauth_accounts' },
  { tableName: 'password_reset_tokens' },
  { tableName: 'refresh_tokens' },
  { tableName: 'user_session' },
  { tableName: 'work_team_feedback', column: 'from_user_id' },
  { tableName: 'work_team_feedback', column: 'to_user_id' },
  { tableName: 'work_team_messages', column: 'sender_id' },
  { tableName: 'work_team_objectives', column: 'created_by' },
  { tableName: 'work_team_course_assignments', column: 'assigned_by' },
  { tableName: 'work_team_members' },
  { tableName: 'reportes_problemas' },
  { tableName: 'admin_dashboard_layouts' },
  { tableName: 'admin_dashboard_preferences' },
  { tableName: 'study_preferences' },
  { tableName: 'user_streaks' },
  { tableName: 'user_activity_log' },
  { tableName: 'user_tour_progress' },
  { tableName: 'user_warnings' },
  { tableName: 'ai_moderation_logs' },
  { tableName: 'audit_logs' },
  { tableName: 'audit_logs', column: 'admin_user_id' },
  { tableName: 'user_favorites' },
  { tableName: 'app_favorites' },
  { tableName: 'notes' },
  { tableName: 'community_reactions' },
  { tableName: 'community_post_reactions' },
  { tableName: 'community_comment_reactions' },
  { tableName: 'community_comments' },
  { tableName: 'community_posts' },
  { tableName: 'community_members' },
  { tableName: 'community_access_requests', column: 'requester_id' },
  { tableName: 'organization_node_users' },
  { tableName: 'organization_users' },
  { tableName: 'organization_course_purchases', column: 'purchased_by' },
]

export const USER_NULL_UPDATE_TABLES: DeleteTableConfig[] = [
  { tableName: 'work_teams', column: 'team_leader_id' },
  { tableName: 'work_teams', column: 'created_by' },
  { tableName: 'reportes_problemas', column: 'admin_asignado' },
  { tableName: 'community_access_requests', column: 'reviewed_by' },
  { tableName: 'organization_nodes', column: 'manager_id' },
  { tableName: 'organization_users', column: 'invited_by' },
  { tableName: 'courses', column: 'instructor_id' },
  { tableName: 'courses', column: 'approved_by' },
  { tableName: 'news', column: 'created_by' },
  { tableName: 'content_translations', column: 'created_by' },
  { tableName: 'scorm_packages', column: 'created_by' },
]
