import type { NotificationCategory } from './notification-categories.types'

export const NOTIFICATION_TYPE_CATEGORY_MAP: Record<
  string,
  NotificationCategory
> = {
  system_password_changed: 'system',
  system_profile_updated: 'system',
  system_login_success: 'system',
  system_login_unusual: 'system',
  system_login_failed: 'system',
  system_email_verified: 'system',
  system_security_alert: 'critical',
  questionnaire_required: 'critical',
  community_post_created: 'community',
  community_post_comment: 'community',
  community_post_reaction: 'community',
  community_member_joined: 'community',
  course_published: 'course',
  course_enrolled: 'course',
  course_activity_completed: 'course',
  course_completed: 'course',
  course_lesson_completed: 'course',
  course_question_answered: 'course',
  certificate_generated: 'course',
  learning_daily_summary: 'planner',
  news_published: 'news',
  news_featured: 'news',
  reel_created: 'reel',
  reel_liked: 'reel',
  reel_comment: 'reel',
  prompt_created: 'prompt',
  prompt_favorited: 'prompt',
  org_invitation_received: 'org',
  org_role_updated: 'org',
  org_team_assigned: 'org',
  team_assignment: 'org',
  learning_path_assigned: 'course',
  course_deadline_approaching: 'critical',
  mandatory_course_reminder: 'critical',
  hierarchy_chat_message: 'community',
  planner_rebalance_suggested: 'planner',
  study_session_overdue: 'critical',
}
