import {
  AlertCircle,
  AlertTriangle,
  Bell,
  BookOpen,
  CheckCircle2,
  Clock,
  GraduationCap,
  Key,
  LogIn,
  Mail,
  MessageSquare,
  Newspaper,
  Shield,
  Sparkles,
  User,
  UserPlus,
  Users,
  Video,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const NOTIFICATION_TYPE_ICONS: Record<string, LucideIcon> = {
  system_password_changed: Key,
  system_profile_updated: User,
  system_login_success: LogIn,
  system_login_failed: AlertTriangle,
  system_email_verified: Mail,
  system_security_alert: Shield,
  questionnaire_required: AlertCircle,
  community_post_created: MessageSquare,
  community_post_comment: MessageSquare,
  community_post_reaction: Bell,
  community_member_joined: UserPlus,
  course_published: BookOpen,
  course_enrolled: GraduationCap,
  course_completed: CheckCircle2,
  course_lesson_completed: CheckCircle2,
  course_question_answered: MessageSquare,
  news_published: Newspaper,
  news_featured: Newspaper,
  reel_created: Video,
  reel_liked: Bell,
  reel_comment: MessageSquare,
  prompt_created: Sparkles,
  prompt_favorited: Sparkles,
  org_invitation_received: UserPlus,
  org_role_updated: Shield,
  org_team_assigned: Users,
  learning_path_assigned: GraduationCap,
  course_deadline_approaching: AlertTriangle,
  mandatory_course_reminder: AlertCircle,
  hierarchy_chat_message: MessageSquare,
  planner_rebalance_suggested: Sparkles,
  study_session_overdue: Clock,
}
