/**
 * Course Compendium ("libreta") — generated by SofLIA when a user completes a
 * course (100% progress) and on demand from the notebook's regenerate action.
 *
 * The compendium note is course-scoped (lesson_id null, course_id set,
 * source_type 'course_compendium') and contains:
 *   1. An AI study synthesis (key concepts + review guide) built from the
 *      user's notes and the course outline.
 *   2. A deterministic compilation of every note (auto + manual) organized by
 *      lesson in module/lesson order.
 *
 * Pure prompt/compilation builders live in course-compendium.builder.ts.
 */

import { GoogleGenerativeAI } from '@google/generative-ai'

import { createAdminClient } from '@/lib/supabase/admin'
import type { Json } from '@/lib/supabase/types'
import { sanitizeHtml } from '@/lib/sanitize/html-sanitizer.core'
import { logger } from '@/lib/utils/logger'

import { NoteService } from './note.service'
import {
  buildCompiledNotesHtml,
  buildCourseCompendiumPrompt,
  clip,
  groupNotesByLesson,
  type CompendiumLesson,
} from './course-compendium.builder'
import { resolveLessonAutoNotePersistenceDecision } from './lesson-auto-note.service'

type AdminClient = ReturnType<typeof createAdminClient>

export type CourseCompendiumStatus = 'created' | 'updated' | 'skipped' | 'failed'

export interface CourseCompendiumResult {
  error?: string
  noteId?: string
  reason?: string
  status: CourseCompendiumStatus
}

export interface GenerateCourseCompendiumInput {
  allowUpdate: boolean
  courseId: string
  courseTitle: string
  enrollmentId: string
  organizationId: string | null
  userId: string
}

const COMPENDIUM_TAGS = ['SofLIA', 'Compendio', 'Curso']
const FALLBACK_MODEL = 'gemini-3.5-flash'
const MAX_NOTE_CONTENT = 50_000
// The AI synthesis gets a smaller cap so the compiled notes fit below it.
const AI_SYNTHESIS_MAX = 30_000
const COMPILED_SECTION_RESERVE = 500

function normalizeGeneratedHtml(value: string): string {
  return value
    .trim()
    .replace(/^```(?:html)?/i, '')
    .replace(/```$/i, '')
    .trim()
}

interface ModuleWithLessonsRow {
  module_order_index: number | null
  module_title: string
  course_lessons: Array<{
    lesson_id: string
    lesson_order_index: number | null
    lesson_title: string
  }> | null
}

interface ExistingCompendiumRow {
  note_id: string
}

async function loadOrderedLessons(
  supabase: AdminClient,
  courseId: string,
): Promise<CompendiumLesson[]> {
  // Single round-trip: modules + nested lessons (was 2 sequential queries).
  const { data: modules, error } = await supabase
    .from('course_modules')
    .select(
      'module_title, module_order_index, course_lessons(lesson_id, lesson_title, lesson_order_index)',
    )
    .eq('course_id', courseId)

  if (error) {
    throw new Error(`Error cargando lecciones del curso: ${error.message}`)
  }

  return ((modules ?? []) as ModuleWithLessonsRow[])
    .flatMap((module) =>
      (module.course_lessons ?? []).map((lesson) => ({
        lessonId: lesson.lesson_id,
        lessonTitle: lesson.lesson_title,
        moduleOrder: module.module_order_index ?? 0,
        moduleTitle: module.module_title,
        orderIndex: lesson.lesson_order_index ?? 0,
      })),
    )
    .sort((a, b) =>
      a.moduleOrder !== b.moduleOrder
        ? a.moduleOrder - b.moduleOrder
        : a.orderIndex - b.orderIndex,
    )
}

async function findExistingCompendium(
  supabase: AdminClient,
  input: Pick<GenerateCourseCompendiumInput, 'courseId' | 'enrollmentId' | 'userId'>,
): Promise<ExistingCompendiumRow | null> {
  const { data, error } = await supabase
    .from('user_lesson_notes')
    .select('note_id')
    .eq('user_id', input.userId)
    .eq('course_id', input.courseId)
    .eq('enrollment_id', input.enrollmentId)
    .eq('source_type', 'course_compendium')
    .eq('is_auto_generated', true)
    .order('updated_at', { ascending: false })
    .limit(1)
    .maybeSingle<ExistingCompendiumRow>()

  if (error) {
    throw new Error(`Error consultando compendio existente: ${error.message}`)
  }

  return data || null
}

async function generateSynthesisHtml(prompt: string): Promise<string> {
  const googleApiKey = process.env.GOOGLE_API_KEY || process.env.GEMINI_API_KEY
  if (!googleApiKey) {
    throw new Error('GEMINI_API_KEY no esta configurada.')
  }

  const genAI = new GoogleGenerativeAI(googleApiKey)
  const model = genAI.getGenerativeModel({
    model: process.env.GEMINI_MODEL || FALLBACK_MODEL,
    generationConfig: {
      maxOutputTokens: 8192,
      temperature: 0.25,
    },
  })

  const result = await model.generateContent(prompt)
  const rawHtml = normalizeGeneratedHtml(result.response.text())
  const sanitized = sanitizeHtml(rawHtml, {
    level: 'rich',
    maxLength: AI_SYNTHESIS_MAX,
  }).trim()

  if (!sanitized) {
    throw new Error('SofLIA no devolvio contenido para el compendio.')
  }

  return sanitized
}

async function persistCompendium(input: {
  content: string
  courseId: string
  enrollmentId: string
  existingNoteId: string | null
  noteTitle: string
  organizationId: string
  supabase: AdminClient
  userId: string
}): Promise<CourseCompendiumResult> {
  const now = new Date().toISOString()

  if (input.existingNoteId) {
    const { data, error } = await input.supabase
      .from('user_lesson_notes')
      .update({
        is_auto_generated: true,
        note_content: input.content,
        note_tags: COMPENDIUM_TAGS as unknown as Json,
        note_title: input.noteTitle,
        source_type: 'course_compendium',
        updated_at: now,
      })
      .eq('note_id', input.existingNoteId)
      .eq('user_id', input.userId)
      .select('note_id')
      .single<ExistingCompendiumRow>()

    if (error || !data) {
      throw new Error(
        `Error actualizando compendio: ${error?.message || 'sin respuesta'}`,
      )
    }

    return { noteId: data.note_id, status: 'updated' }
  }

  const { data, error } = await input.supabase
    .from('user_lesson_notes')
    .insert({
      course_id: input.courseId,
      enrollment_id: input.enrollmentId,
      is_auto_generated: true,
      lesson_id: null,
      note_content: input.content,
      note_tags: COMPENDIUM_TAGS as unknown as Json,
      note_title: input.noteTitle,
      organization_id: input.organizationId,
      source_type: 'course_compendium',
      updated_at: now,
      user_id: input.userId,
    })
    .select('note_id')
    .single<ExistingCompendiumRow>()

  if (error || !data) {
    throw new Error(`Error creando compendio: ${error?.message || 'sin respuesta'}`)
  }

  return { noteId: data.note_id, status: 'created' }
}

export async function generateCourseCompendium(
  input: GenerateCourseCompendiumInput,
): Promise<CourseCompendiumResult> {
  try {
    // The notebook is strictly org-scoped; a compendium without organization
    // would be invisible to the user.
    if (!input.organizationId) {
      return { reason: 'NO_ORGANIZATION', status: 'skipped' }
    }

    const supabase = createAdminClient()

    // Idempotency BEFORE any Gemini cost: the automatic trigger passes
    // allowUpdate=false (skip if it already exists); regenerate passes true.
    const existing = await findExistingCompendium(supabase, input)
    const decision = resolveLessonAutoNotePersistenceDecision({
      allowUpdate: input.allowUpdate,
      existingNoteId: existing?.note_id,
    })

    if (decision.action === 'skip') {
      return {
        noteId: decision.noteId,
        reason: 'COMPENDIUM_ALREADY_EXISTS',
        status: 'skipped',
      }
    }

    const [lessons, notes] = await Promise.all([
      loadOrderedLessons(supabase, input.courseId),
      NoteService.getNotesByCourseWithClient(
        supabase,
        input.userId,
        input.courseId,
        input.enrollmentId,
      ),
    ])
    const notesByLesson = groupNotesByLesson(notes)

    const prompt = buildCourseCompendiumPrompt({
      courseTitle: input.courseTitle,
      lessons,
      notesByLesson,
    })
    const synthesisHtml = await generateSynthesisHtml(prompt)

    const compiledBudget =
      MAX_NOTE_CONTENT - synthesisHtml.length - COMPILED_SECTION_RESERVE
    const compiledHtml = buildCompiledNotesHtml({
      budget: compiledBudget,
      lessons,
      notesByLesson,
    })

    const content = sanitizeHtml(`${synthesisHtml}${compiledHtml}`, {
      level: 'rich',
      maxLength: MAX_NOTE_CONTENT,
    }).trim()

    return persistCompendium({
      content,
      courseId: input.courseId,
      enrollmentId: input.enrollmentId,
      existingNoteId: decision.noteId ?? null,
      noteTitle: clip(`Compendio SofLIA: ${input.courseTitle}`, 240),
      organizationId: input.organizationId,
      supabase,
      userId: input.userId,
    })
  } catch (error) {
    logger.error('Course compendium generation failed', {
      courseId: input.courseId,
      error: error instanceof Error ? error.message : error,
      userId: input.userId,
    })

    return {
      error: error instanceof Error ? error.message : 'Error desconocido',
      status: 'failed',
    }
  }
}
