/**
 * Course Compendium ("libreta") — generated by SofLIA when a user completes a
 * course (100% progress) and on demand from the notebook's regenerate action.
 *
 * The compendium note is course-scoped (lesson_id null, course_id set,
 * source_type 'course_compendium') and contains:
 *   1. An AI study synthesis (key concepts + review guide) built from the
 *      user's notes and the course outline.
 *   2. A deterministic compilation of every note (auto + manual) organized by
 *      lesson in module/lesson order.
 *
 * Pure prompt/compilation builders live in course-compendium.builder.ts.
 */

import { z } from 'zod'

import { generateStructuredContent } from '@/lib/ai/structured-generation.server'
import { createAdminClient } from '@/lib/supabase/admin'
import type { Json } from '@/lib/supabase/types'
import { sanitizeHtml } from '@/lib/sanitize/html-sanitizer.core'
import { logger } from '@/lib/utils/logger'

import { NoteService } from './note.service'
import {
  buildCompiledNotesHtml,
  buildCourseCompendiumPrompt,
  buildCourseSynthesisHtmlFromModel,
  buildDeterministicCourseSynthesisHtml,
  clip,
  groupNotesByLesson,
  type CompendiumLesson,
} from './course-compendium.builder'
import { resolveLessonAutoNotePersistenceDecision } from './lesson-auto-note.service'

type AdminClient = ReturnType<typeof createAdminClient>

export type CourseCompendiumStatus = 'created' | 'updated' | 'skipped' | 'failed'

export interface CourseCompendiumResult {
  error?: string
  noteId?: string
  quality?: 'ai' | 'deterministic'
  reason?: string
  status: CourseCompendiumStatus
  warning?: string
}

export interface GenerateCourseCompendiumInput {
  allowUpdate: boolean
  courseId: string
  courseTitle: string
  enrollmentId: string
  organizationId: string | null
  userId: string
}

const COMPENDIUM_TAGS = ['SofLIA', 'Compendio', 'Curso']
const FALLBACK_MODEL = 'gemini-3.5-flash'
const MAX_NOTE_CONTENT = 50_000
// The AI synthesis gets a smaller cap so the compiled notes fit below it.
const AI_SYNTHESIS_MAX = 30_000
const COMPILED_SECTION_RESERVE = 500

const compendiumItemSchema = z.object({
  detail: z.string().min(1).max(2_500),
  label: z.string().max(160),
})
const courseSynthesisSchema = z.object({
  keyConcepts: z.array(compendiumItemSchema).min(1).max(12),
  reviewSteps: z.array(compendiumItemSchema).min(1).max(12),
  synthesis: z.array(z.string().min(1).max(3_000)).min(1).max(5),
  titles: z.object({
    concepts: z.string().min(1).max(120),
    index: z.string().min(1).max(80),
    review: z.string().min(1).max(120),
    synthesis: z.string().min(1).max(120),
  }),
})
const COURSE_SYNTHESIS_JSON_SCHEMA: Record<string, unknown> = {
  $defs: {
    item: {
      additionalProperties: false,
      properties: { detail: { type: 'string' }, label: { type: 'string' } },
      required: ['detail', 'label'],
      type: 'object',
    },
  },
  additionalProperties: false,
  properties: {
    keyConcepts: { items: { $ref: '#/$defs/item' }, minItems: 1, type: 'array' },
    reviewSteps: { items: { $ref: '#/$defs/item' }, minItems: 1, type: 'array' },
    synthesis: { items: { type: 'string' }, minItems: 1, type: 'array' },
    titles: {
      additionalProperties: false,
      properties: {
        concepts: { type: 'string' },
        index: { type: 'string' },
        review: { type: 'string' },
        synthesis: { type: 'string' },
      },
      required: ['concepts', 'index', 'review', 'synthesis'],
      type: 'object',
    },
  },
  required: ['keyConcepts', 'reviewSteps', 'synthesis', 'titles'],
  type: 'object',
}

interface ModuleWithLessonsRow {
  module_order_index: number | null
  module_title: string
  course_lessons: Array<{
    lesson_id: string
    lesson_order_index: number | null
    lesson_title: string
  }> | null
}

interface ExistingCompendiumRow {
  note_id: string
  is_user_edited?: boolean | null
}

export async function loadOrderedLessons(
  supabase: AdminClient,
  courseId: string,
): Promise<CompendiumLesson[]> {
  // Single round-trip: modules + nested lessons (was 2 sequential queries).
  const { data: modules, error } = await supabase
    .from('course_modules')
    .select(
      'module_title, module_order_index, course_lessons(lesson_id, lesson_title, lesson_order_index)',
    )
    .eq('course_id', courseId)

  if (error) {
    throw new Error(`Error cargando lecciones del curso: ${error.message}`)
  }

  return ((modules ?? []) as ModuleWithLessonsRow[])
    .flatMap((module) =>
      (module.course_lessons ?? []).map((lesson) => ({
        lessonId: lesson.lesson_id,
        lessonTitle: lesson.lesson_title,
        moduleOrder: module.module_order_index ?? 0,
        moduleTitle: module.module_title,
        orderIndex: lesson.lesson_order_index ?? 0,
      })),
    )
    .sort((a, b) =>
      a.moduleOrder !== b.moduleOrder
        ? a.moduleOrder - b.moduleOrder
        : a.orderIndex - b.orderIndex,
    )
}

async function findExistingCompendium(
  supabase: AdminClient,
  input: Pick<GenerateCourseCompendiumInput, 'courseId' | 'enrollmentId' | 'userId'>,
): Promise<ExistingCompendiumRow | null> {
  const { data, error } = await supabase
    .from('user_lesson_notes')
    .select('note_id, is_user_edited')
    .eq('user_id', input.userId)
    .eq('course_id', input.courseId)
    .eq('enrollment_id', input.enrollmentId)
    .eq('source_type', 'course_compendium')
    .eq('is_auto_generated', true)
    .order('updated_at', { ascending: false })
    .limit(1)
    .maybeSingle<ExistingCompendiumRow>()

  if (error) {
    throw new Error(`Error consultando compendio existente: ${error.message}`)
  }

  return data || null
}

async function generateSynthesisHtml(input: {
  generation: GenerateCourseCompendiumInput
  prompt: string
  untrustedText: string
}): Promise<string> {
  const result = await generateStructuredContent({
    audit: {
      action: 'notebook_course_compendium_generated',
      actorId: input.generation.userId,
      organizationId: input.generation.organizationId,
      resourceId: input.generation.courseId,
      resourceType: 'course',
    },
    jsonSchema: COURSE_SYNTHESIS_JSON_SCHEMA,
    maxOutputTokens: 8_192,
    model: process.env.GEMINI_MODEL || FALLBACK_MODEL,
    operation: 'course_compendium',
    prompt: input.prompt,
    schema: courseSynthesisSchema,
    temperature: 0.25,
    untrustedText: input.untrustedText,
  })
  const generatedHtml = buildCourseSynthesisHtmlFromModel(
    JSON.stringify(result.value),
  )
  const sanitized = sanitizeHtml(generatedHtml, {
    level: 'rich',
    maxLength: AI_SYNTHESIS_MAX,
  }).trim()

  if (!sanitized) {
    throw new Error('SofLIA no devolvio contenido para el compendio.')
  }

  return sanitized
}

async function persistCompendium(input: {
  content: string
  courseId: string
  enrollmentId: string
  existingNoteId: string | null
  noteTitle: string
  organizationId: string
  supabase: AdminClient
  userId: string
}): Promise<CourseCompendiumResult> {
  const now = new Date().toISOString()

  if (input.existingNoteId) {
    const { data, error } = await input.supabase
      .from('user_lesson_notes')
      .update({
        is_auto_generated: true,
        note_content: input.content,
        note_tags: COMPENDIUM_TAGS as unknown as Json,
        note_title: input.noteTitle,
        source_type: 'course_compendium',
        updated_at: now,
      })
      .eq('note_id', input.existingNoteId)
      .eq('user_id', input.userId)
      .select('note_id')
      .single<ExistingCompendiumRow>()

    if (error || !data) {
      throw new Error(
        `Error actualizando compendio: ${error?.message || 'sin respuesta'}`,
      )
    }

    return { noteId: data.note_id, status: 'updated' }
  }

  const { data, error } = await input.supabase
    .from('user_lesson_notes')
    .insert({
      course_id: input.courseId,
      enrollment_id: input.enrollmentId,
      is_auto_generated: true,
      lesson_id: null,
      note_content: input.content,
      note_tags: COMPENDIUM_TAGS as unknown as Json,
      note_title: input.noteTitle,
      organization_id: input.organizationId,
      source_type: 'course_compendium',
      updated_at: now,
      user_id: input.userId,
    })
    .select('note_id')
    .single<ExistingCompendiumRow>()

  if (error || !data) {
    throw new Error(`Error creando compendio: ${error?.message || 'sin respuesta'}`)
  }

  return { noteId: data.note_id, status: 'created' }
}

export async function generateCourseCompendium(
  input: GenerateCourseCompendiumInput,
): Promise<CourseCompendiumResult> {
  try {
    // The notebook is strictly org-scoped; a compendium without organization
    // would be invisible to the user.
    if (!input.organizationId) {
      return { reason: 'NO_ORGANIZATION', status: 'skipped' }
    }

    const supabase = createAdminClient()

    // Idempotency BEFORE any Gemini cost: the automatic trigger passes
    // allowUpdate=false (skip if it already exists); regenerate passes true.
    const existing = await findExistingCompendium(supabase, input)
    const decision = resolveLessonAutoNotePersistenceDecision({
      allowUpdate: input.allowUpdate,
      existingNoteId: existing?.note_id,
      // Un compendio editado por el usuario no se regenera; la ruta de
      // "Regenerar" pone is_user_edited=false antes de encolar para forzarlo.
      existingUserEdited: existing?.is_user_edited,
    })

    if (decision.action === 'skip') {
      return {
        noteId: decision.noteId,
        reason: 'COMPENDIUM_ALREADY_EXISTS',
        status: 'skipped',
      }
    }

    const [lessons, notes] = await Promise.all([
      loadOrderedLessons(supabase, input.courseId),
      NoteService.getNotesByCourseWithClient(
        supabase,
        input.userId,
        input.courseId,
        input.enrollmentId,
      ),
    ])
    const notesByLesson = groupNotesByLesson(notes)

    const prompt = buildCourseCompendiumPrompt({
      courseTitle: input.courseTitle,
      lessons,
      notesByLesson,
    })
    let quality: 'ai' | 'deterministic' = 'ai'
    let warning: string | undefined
    let synthesisHtml: string
    try {
      synthesisHtml = await generateSynthesisHtml({
        generation: input,
        prompt,
        untrustedText: notes
          .map((note) => `${note.note_title}\n${note.note_content}`)
          .join('\n')
          .slice(0, 20_000),
      })
    } catch (generationError) {
      quality = 'deterministic'
      warning =
        generationError instanceof Error
          ? generationError.message
          : 'AI generation unavailable'
      logger.warn('Using deterministic course compendium fallback', {
        courseId: input.courseId,
        reason: warning,
        userId: input.userId,
      })
      synthesisHtml = buildDeterministicCourseSynthesisHtml({
        courseTitle: input.courseTitle,
        lessons,
        notesByLesson,
      })
    }

    const compiledBudget =
      MAX_NOTE_CONTENT - synthesisHtml.length - COMPILED_SECTION_RESERVE
    const compiledHtml = buildCompiledNotesHtml({
      budget: compiledBudget,
      lessons,
      notesByLesson,
    })

    const content = sanitizeHtml(`${synthesisHtml}${compiledHtml}`, {
      level: 'rich',
      maxLength: MAX_NOTE_CONTENT,
    }).trim()

    const persisted = await persistCompendium({
      content,
      courseId: input.courseId,
      enrollmentId: input.enrollmentId,
      existingNoteId: decision.noteId ?? null,
      noteTitle: clip(`Compendio SofLIA: ${input.courseTitle}`, 240),
      organizationId: input.organizationId,
      supabase,
      userId: input.userId,
    })
    return { ...persisted, quality, warning }
  } catch (error) {
    logger.error('Course compendium generation failed', {
      courseId: input.courseId,
      error: error instanceof Error ? error.message : error,
      userId: input.userId,
    })

    return {
      error: error instanceof Error ? error.message : 'Error desconocido',
      status: 'failed',
    }
  }
}
