export const COMMON_PASSWORDS = [
  'password',
  'password123',
  '123456',
  '12345678',
  'qwerty',
  'abc123',
  'monkey',
  '1234567',
  'letmein',
  'trustno1',
  'dragon',
  'baseball',
  'iloveyou',
  'master',
  'sunshine',
  'ashley',
  'bailey',
  'passw0rd',
  'shadow',
  '123123',
  '654321',
  'superman',
  'qazwsx',
  'michael',
  'football',
  'welcome',
  'jesus',
  'ninja',
  'mustang',
  'password1',
  'admin',
  'admin123',
  'root',
  'toor',
  'pass',
  'test',
  'guest',
  'info',
  'adm',
  'mysql',
  'user',
  'administrator',
  'oracle',
  'ftp',
  'pi',
  'puppet',
  'ansible',
  'ec2-user',
  'vagrant',
  'azureuser',
  'academy',
  'aprendeaplica',
  'aprende',
  'aplica',
] as const;

export const DANGEROUS_PATTERNS = [
  /^(.)\1+$/,
  /^(01|12|23|34|45|56|67|78|89|90)+$/,
  /^(abc|bcd|cde|def|efg|fgh|ghi|hij|ijk|jkl|klm|lmn|mno|nop|opq|pqr|qrs|rst|stu|tuv|uvw|vwx|wxy|xyz)+$/i,
  /^(qwert|asdf|zxcv|qwer|werty|sdfg|xcvb)+$/i,
] as const;

export const PERSONAL_INFO_PATTERNS = [
  /usuario/i,
  /user/i,
  /admin/i,
  /correo/i,
  /email/i,
  /nombre/i,
  /name/i,
] as const;
