/**
 * Notebook Feature — Shared Types
 *
 * The Notebook ("Libro de Apuntes") organizes a user's lesson notes as a
 * two-level tree (Course -> Lesson -> Notes), strictly scoped to the user's
 * current organization. Note content is rich HTML (TipTap output).
 */

export type NotebookNoteSource =
  | 'manual'
  | 'chat'
  | 'import'
  | 'lesson_auto_note'
  | 'course_compendium'

/** Lightweight note descriptor used to render the tree and note cards. */
export interface NotebookNoteSummary {
  noteId: string
  title: string
  tags: string[]
  source: NotebookNoteSource
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
}

/**
 * Full note payload used by the dedicated editor page and hover preview.
 * Course compendium notes are course-scoped: lessonId/lessonTitle are empty.
 */
export interface NotebookNoteDetail extends NotebookNoteSummary {
  content: string
  lessonId: string
  lessonTitle: string
  courseId: string
  courseTitle: string
  courseSlug: string | null
}

export interface NotebookLessonNode {
  lessonId: string
  title: string
  orderIndex: number
  notes: NotebookNoteSummary[]
}

export interface NotebookCourseNode {
  courseId: string
  title: string
  slug: string | null
  totalNotes: number
  /** SofLIA course compendium ("libreta"), shown above the lessons. */
  compendium?: NotebookNoteSummary | null
  lessons: NotebookLessonNode[]
}

export interface NotebookTree {
  courses: NotebookCourseNode[]
  totalNotes: number
}

/** Course/lesson options for the "New note" picker. */
export interface NotebookLessonOption {
  lessonId: string
  title: string
  orderIndex: number
}

export interface NotebookCourseOption {
  courseId: string
  title: string
  slug: string | null
  lessons: NotebookLessonOption[]
}

export interface NotebookCourseOptionsResponse {
  courses: NotebookCourseOption[]
}

// --- API request payloads ---

export interface CreateNotebookNoteInput {
  courseId: string
  lessonId: string
  title?: string
  content?: string
  tags?: string[]
}

export interface UpdateNotebookNoteInput {
  title?: string
  content?: string
  tags?: string[]
}

// --- API response envelopes ---

export interface NotebookTreeResponse {
  tree: NotebookTree
}

export interface NotebookNoteResponse {
  note: NotebookNoteDetail
}

// --- AI enrichment (second-brain phase 1) ---

/** Knowledge classification suggested by AI, editable by the user. */
export type NotebookKnowledgeType =
  | 'note'
  | 'reflection'
  | 'decision'
  | 'qa'
  | 'resource'
  | 'evidence'

/** Note lifecycle; 'shared'/'promoted' are reserved for the sharing phase. */
export type NotebookLifecycleStatus =
  | 'draft'
  | 'enriched'
  | 'reviewed'
  | 'archived'
  | 'shared'
  | 'promoted'

/** AI enrichment attached to a note (1:1, from notebook_note_metadata). */
export interface NotebookNoteEnrichment {
  noteId: string
  knowledgeType: NotebookKnowledgeType
  lifecycleStatus: NotebookLifecycleStatus
  summary: string | null
  keyConcepts: string[]
  suggestedTags: string[]
  /** 0..1 — AI self-reported confidence in its classification. */
  confidence: number | null
  enrichedAt: string | null
}

export type NotebookDerivedTaskStatus = 'suggested' | 'open' | 'done' | 'dismissed'

/** Actionable item derived from a note (AI-suggested until user confirms). */
export interface NotebookDerivedTask {
  taskId: string
  noteId: string
  title: string
  status: NotebookDerivedTaskStatus
  createdBy: 'ai' | 'user'
  createdAt: string
  completedAt: string | null
}

/**
 * Aggregated queue state for a note: 'pending'/'processing' while a job is in
 * flight (UI polls), 'failed' when retries were exhausted, 'idle' otherwise.
 */
export type NotebookEnrichmentJobStatus = 'idle' | 'pending' | 'processing' | 'failed'

export interface NotebookNoteEnrichmentState {
  enrichment: NotebookNoteEnrichment | null
  tasks: NotebookDerivedTask[]
  jobStatus: NotebookEnrichmentJobStatus
}

export interface NotebookNoteEnrichmentResponse {
  state: NotebookNoteEnrichmentState
}

export interface NotebookDerivedTaskResponse {
  task: NotebookDerivedTask
}

/** Statuses a user may set on a derived task (never back to 'suggested'). */
export const NOTEBOOK_TASK_USER_STATUSES = ['open', 'done', 'dismissed'] as const

/** Maximum stored size for note HTML content (mirrors lesson-notes limit). */
export const NOTEBOOK_MAX_CONTENT_LENGTH = 50_000
/** Maximum length for a note title. */
export const NOTEBOOK_MAX_TITLE_LENGTH = 256
/** Maximum number of tags per note. */
export const NOTEBOOK_MAX_TAGS = 20
/** Default HTML used when a note is created empty (valid TipTap doc). */
export const NOTEBOOK_EMPTY_CONTENT = '<p></p>'
