/**
 * Notebook Feature — Shared Types
 *
 * The Notebook ("Libro de Apuntes") organizes a user's lesson notes as a
 * two-level tree (Course -> Lesson -> Notes), strictly scoped to the user's
 * current organization. Note content is rich HTML (TipTap output).
 */

export type NotebookNoteSource = 'manual' | 'chat' | 'import' | 'lesson_auto_note'

/** Lightweight note descriptor used to render the tree and note cards. */
export interface NotebookNoteSummary {
  noteId: string
  title: string
  tags: string[]
  source: NotebookNoteSource
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
}

/** Full note payload used by the dedicated editor page and hover preview. */
export interface NotebookNoteDetail extends NotebookNoteSummary {
  content: string
  lessonId: string
  lessonTitle: string
  courseId: string
  courseTitle: string
  courseSlug: string | null
}

export interface NotebookLessonNode {
  lessonId: string
  title: string
  orderIndex: number
  notes: NotebookNoteSummary[]
}

export interface NotebookCourseNode {
  courseId: string
  title: string
  slug: string | null
  totalNotes: number
  lessons: NotebookLessonNode[]
}

export interface NotebookTree {
  courses: NotebookCourseNode[]
  totalNotes: number
}

/** Course/lesson options for the "New note" picker. */
export interface NotebookLessonOption {
  lessonId: string
  title: string
  orderIndex: number
}

export interface NotebookCourseOption {
  courseId: string
  title: string
  slug: string | null
  lessons: NotebookLessonOption[]
}

export interface NotebookCourseOptionsResponse {
  courses: NotebookCourseOption[]
}

// --- API request payloads ---

export interface CreateNotebookNoteInput {
  courseId: string
  lessonId: string
  title?: string
  content?: string
  tags?: string[]
}

export interface UpdateNotebookNoteInput {
  title?: string
  content?: string
  tags?: string[]
}

// --- API response envelopes ---

export interface NotebookTreeResponse {
  tree: NotebookTree
}

export interface NotebookNoteResponse {
  note: NotebookNoteDetail
}

/** Maximum stored size for note HTML content (mirrors lesson-notes limit). */
export const NOTEBOOK_MAX_CONTENT_LENGTH = 50_000
/** Maximum length for a note title. */
export const NOTEBOOK_MAX_TITLE_LENGTH = 256
/** Maximum number of tags per note. */
export const NOTEBOOK_MAX_TAGS = 20
/** Default HTML used when a note is created empty (valid TipTap doc). */
export const NOTEBOOK_EMPTY_CONTENT = '<p></p>'
